(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P = (track,lvl,arr)=>{C[track]=C[track]||{};C[track][lvl]=C[track][lvl]||[];arr.forEach(x=>C[track][lvl].push(x));};
  P("reading","C1",[
    {
      id:"r3-C1-01",
      title:"The Limits of Scientific Certainty",
      text:"The popular conception of science as a relentless march toward absolute truth obscures a more subtle reality. Practising scientists rarely speak of proof; instead, they accumulate evidence that renders a hypothesis progressively more plausible while remaining, in principle, open to revision. This provisional character is not a weakness but the very engine of progress, for a theory that could never be falsified would forfeit any claim to scientific status. The philosopher Karl Popper argued that the demarcation between science and pseudoscience lies precisely in this vulnerability to refutation. Yet the matter is rarely so clean. When an experiment contradicts an established framework, researchers seldom abandon the framework outright; they more often question the experimental apparatus, the auxiliary assumptions, or the competence of the observer. Whole theoretical edifices are protected by a belt of adjustable suppositions, and only the accumulation of anomalies, coupled with a viable alternative, prompts wholesale revision. Consequently, scientific knowledge advances less through sudden conversion than through gradual erosion of confidence in prevailing models. To mistake this measured tentativeness for indecision is to misunderstand the discipline entirely. The strength of science resides not in dogmatic finality but in its disciplined willingness to be proven wrong.",
      questions:[
        { q:"What does the passage suggest about the term 'proof' in science?", options:["Scientists rarely invoke it, preferring accumulated evidence","It is the ultimate goal of every experiment","It is synonymous with falsification"], answer:0 },
        { q:"According to Popper, what distinguishes science from pseudoscience?", options:["The quantity of supporting data","Its openness to being refuted","The reputation of its practitioners"], answer:1 },
        { q:"How do researchers typically respond when an experiment contradicts an established theory?", options:["They immediately discard the theory","They question the apparatus or assumptions first","They publish a refutation at once"], answer:1 },
        { q:"What can be inferred about the author's view of scientific tentativeness?", options:["It is a regrettable flaw to be overcome","It reflects indecision among researchers","It is a genuine source of the discipline's strength"], answer:2 }
      ]
    },
    {
      id:"r3-C1-02",
      title:"The Paradox of Choice",
      text:"Modern affluence has bestowed upon consumers an abundance of options once unimaginable, yet psychologists increasingly question whether this proliferation reliably enhances wellbeing. The intuitive assumption holds that more alternatives must be preferable, since any superfluous option can simply be ignored. Empirical findings complicate this tidy logic. When confronted with an overwhelming array of possibilities, individuals frequently experience a paralysis of deliberation, postponing decisions or abandoning them altogether. Even after a choice is made, the awareness of forgone alternatives breeds a lingering dissatisfaction, as the chooser imagines the superior outcomes that might have been secured elsewhere. This phenomenon, sometimes termed the tyranny of choice, suggests that human cognition is poorly adapted to environments of unrestricted abundance. The mental effort required to evaluate countless permutations exhausts our limited attentional resources, and the resulting fatigue diminishes the satisfaction we ultimately derive. Some scholars contend that constraints, far from being oppressive, can be quietly liberating, sparing us the burden of perpetual optimisation. The implication is not that scarcity should be engineered, but that the unqualified celebration of consumer freedom rests on a shakier psychological foundation than its proponents acknowledge. Choice, in excess, may corrode the very contentment it promises to deliver.",
      questions:[
        { q:"What intuitive assumption does the passage challenge?", options:["That more options always improve wellbeing","That consumers prefer fewer brands","That affluence reduces happiness"], answer:0 },
        { q:"What effect can an overwhelming array of options produce?", options:["Faster, more confident decisions","A paralysis of deliberation","Greater loyalty to a single product"], answer:1 },
        { q:"Why does dissatisfaction linger even after a choice is made?", options:["The product usually proves defective","The chooser imagines superior forgone alternatives","Other people criticise the decision"], answer:1 },
        { q:"What is the author's overall position on consumer freedom?", options:["Scarcity should be deliberately engineered","Its celebration rests on shaky psychological ground","More choice is unambiguously beneficial"], answer:1 }
      ]
    },
    {
      id:"r3-C1-03",
      title:"The Ethics of Artificial Intelligence",
      text:"As algorithmic systems assume responsibilities once reserved for human judgement, a thorny question emerges: who bears moral accountability when such systems err? The conventional reflex is to locate blame within the chain of human actors who designed, deployed, or supervised the technology. Yet contemporary machine learning frustrates this neat attribution. A system trained on vast datasets may develop decision criteria that no engineer explicitly programmed and that even its creators cannot fully articulate. When an opaque model denies someone a loan or misidentifies a suspect, the appeal to human intention rings hollow, for the relevant intentions were diffused across data, code, and institutional incentives. Some commentators advocate treating advanced systems as moral agents in their own right, but this manoeuvre risks furnishing corporations with a convenient scapegoat, displacing responsibility onto an artefact incapable of being meaningfully punished. A more defensible position insists that accountability cannot be outsourced to a machine, however sophisticated. Those who profit from automated decisions must remain answerable for their consequences, regardless of how inscrutable the underlying mechanisms become. The challenge, then, is institutional rather than merely technical: societies must construct frameworks that preserve human responsibility even as human comprehension of these systems recedes.",
      questions:[
        { q:"Why does modern machine learning complicate the attribution of blame?", options:["Engineers deliberately conceal their reasoning","Systems may develop criteria no one explicitly programmed","The systems never actually make errors"], answer:1 },
        { q:"What risk does treating AI as a moral agent carry?", options:["It gives corporations a convenient scapegoat","It makes systems too cautious","It slows technological progress"], answer:0 },
        { q:"What does the author regard as the more defensible position?", options:["Machines should be punished for their errors","Accountability cannot be outsourced to a machine","Human judgement should never be automated"], answer:1 },
        { q:"How does the author characterise the central challenge?", options:["Primarily a matter of faster hardware","Institutional rather than merely technical","Impossible to address in any form"], answer:1 }
      ]
    },
    {
      id:"r3-C1-04",
      title:"Memory and the Reconstruction of the Past",
      text:"We tend to regard memory as a faithful archive, a repository from which past experiences can be retrieved intact. Decades of cognitive research have dismantled this comforting metaphor. Remembering is not the replay of a recording but an act of reconstruction, in which fragmentary traces are assembled anew each time we recall an event. This reconstructive process is exquisitely susceptible to distortion. The questions we are asked, the expectations we hold, and the narratives prevailing in our surroundings can all insinuate themselves into the recollection, subtly altering its content without our awareness. Experiments have demonstrated that people can be led to remember, with vivid conviction, events that never occurred, complete with sensory detail and emotional texture. The implications extend well beyond the laboratory. Legal systems that accord eyewitness testimony a near-sacred authority must reckon with the malleability of the very faculty they rely upon. Yet the reconstructive nature of memory is not purely a liability. The same flexibility that renders us vulnerable to false recollection also permits us to integrate new understanding into our sense of the past, weaving disparate experiences into a coherent self. Memory, in this light, serves less as a chronicle than as an ongoing interpretation.",
      questions:[
        { q:"What metaphor does the passage reject?", options:["Memory as an ongoing interpretation","Memory as a faithful archive","Memory as a creative act"], answer:1 },
        { q:"What can influence the content of a reconstructed memory?", options:["Only the original event itself","Questions, expectations, and surrounding narratives","Nothing, once the event has occurred"], answer:1 },
        { q:"Why is the malleability of memory significant for legal systems?", options:["It speeds up trials considerably","Eyewitness testimony is granted near-sacred authority","Juries ignore testimony entirely"], answer:1 },
        { q:"What positive aspect of reconstructive memory does the author note?", options:["It allows integration of new understanding into the self","It guarantees perfect recall over time","It prevents any form of distortion"], answer:0 }
      ]
    },
    {
      id:"r3-C1-05",
      title:"The Commons and Collective Action",
      text:"When a resource is shared by many and owned by none, the logic of individual self-interest can drive its ruin. Each user, reasoning that personal restraint will scarcely affect the whole while sacrificing immediate gain, is tempted to extract as much as possible. If everyone reasons thus, the resource is depleted to the detriment of all. This bleak scenario, famously dubbed the tragedy of the commons, was long invoked to justify either privatisation or centralised state control as the only escape. Subsequent scholarship has substantially qualified that pessimism. Detailed studies of fisheries, irrigation networks, and grazing lands reveal that communities have repeatedly devised durable arrangements for managing shared resources without recourse to private ownership or external coercion. The key ingredients include clearly defined boundaries, rules tailored to local conditions, mechanisms for monitoring compliance, and graduated sanctions imposed by the users themselves. Such self-governance flourishes where participants can communicate, build trust, and anticipate continued interaction over time. The tragedy, it transpires, is not inevitable but contingent upon the absence of institutions capable of aligning individual incentives with collective welfare. The lesson reaches beyond pastures and fisheries to the gravest commons of all, the planetary climate.",
      questions:[
        { q:"What drives the depletion in the tragedy of the commons?", options:["A shortage of available resources","Individual self-interest amid shared ownership","Government over-regulation"], answer:1 },
        { q:"What two solutions were traditionally proposed?", options:["Privatisation or centralised state control","Taxation or subsidies","Education or persuasion"], answer:0 },
        { q:"What did later scholarship reveal about communities?", options:["They always require external coercion","They can self-govern shared resources durably","They invariably exhaust their resources"], answer:1 },
        { q:"What broader conclusion does the author draw?", options:["The tragedy is inevitable everywhere","The tragedy is contingent on absent institutions","Climate cannot be treated as a commons"], answer:1 }
      ]
    },
    {
      id:"r3-C1-06",
      title:"The Aesthetics of Imperfection",
      text:"Western aesthetic traditions have frequently equated beauty with symmetry, polish, and the suppression of flaws, an ideal exemplified by the gleaming marble of classical sculpture. A contrasting sensibility, cultivated most deliberately in certain Japanese arts, locates beauty precisely in transience, asymmetry, and the marks of wear. According to this outlook, an object becomes more compelling, not less, when it bears the evidence of its history: the crack mended with visible gold, the glaze that pooled unevenly, the weathered surface that records the passage of seasons. Such an aesthetic resists the tyranny of the flawless, which it regards as sterile and faintly inhuman. Perfection, after all, admits no further development; it stands complete and therefore inert. Imperfection, by contrast, gestures toward process, toward the ceaseless becoming that characterises all living things. To embrace the broken and the incomplete is to reconcile oneself with impermanence rather than to deny it through futile pursuit of an unchanging ideal. This is no mere stylistic preference but a quiet philosophical stance, one that finds in the contingent and the ephemeral a deeper resonance than the manufactured perfection that increasingly surrounds us. The cherished imperfection reminds us that we, too, are unfinished.",
      questions:[
        { q:"What ideal have Western traditions often equated with beauty?", options:["Transience and asymmetry","Symmetry, polish, and the suppression of flaws","The marks of wear and history"], answer:1 },
        { q:"Why might a repaired object be considered more compelling?", options:["It bears the evidence of its history","It hides all signs of damage","It costs more to produce"], answer:0 },
        { q:"Why does the author describe perfection as 'inert'?", options:["It is expensive to maintain","It admits no further development","It is rarely achieved in practice"], answer:1 },
        { q:"What deeper attitude does this aesthetic express?", options:["A denial of impermanence","A reconciliation with impermanence","A preference for mass production"], answer:1 }
      ]
    },
    {
      id:"r3-C1-07",
      title:"Language and the Boundaries of Thought",
      text:"Does the language we speak shape the way we think, or does thought proceed independently of the words used to express it? This question, debated for over a century, has oscillated between bold claims and sceptical retreats. The strongest version of linguistic relativity holds that the categories embedded in a language determine the cognitive horizons of its speakers, such that ideas readily expressed in one tongue become literally inconceivable in another. Few researchers now defend so uncompromising a thesis, since speakers plainly grasp concepts their language lacks convenient labels for. A more modest formulation has nevertheless gained empirical traction. Careful experiments suggest that linguistic habits exert a measurable, if subtle, influence on perception, memory, and attention. Speakers of languages that grammatically encode the direction of motion, or that divide the colour spectrum at unfamiliar junctures, display correspondingly distinctive patterns of discrimination and recall. The effect is one of inflection rather than imprisonment: language nudges cognition along certain grooves without sealing off alternatives. To overstate the influence courts mysticism; to deny it altogether ignores accumulating evidence. The truth, as so often, occupies a contested middle ground, where the structure of speech and the structure of thought engage in reciprocal, partial, and endlessly fascinating influence.",
      questions:[
        { q:"What does the strongest version of linguistic relativity claim?", options:["Language has no effect on cognition","Language determines the cognitive horizons of its speakers","Thought always precedes language"], answer:1 },
        { q:"Why do few researchers defend the strongest version?", options:["Speakers can grasp concepts their language lacks labels for","No experiments have ever been conducted","All languages share identical categories"], answer:0 },
        { q:"How does the author describe the more modest formulation's effect?", options:["Inflection rather than imprisonment","Total determination of thought","No measurable effect at all"], answer:0 },
        { q:"What is the author's concluding stance on the debate?", options:["Language fully imprisons thought","The truth lies in a contested middle ground","Language and thought are entirely unrelated"], answer:1 }
      ]
    },
    {
      id:"r3-C1-08",
      title:"The Economics of Attention",
      text:"In an era of informational superabundance, the scarce resource is no longer content but the human attention required to consume it. This inversion has profound consequences for how digital enterprises generate revenue. Where attention is the commodity, the imperative is to capture and retain it for as long as possible, and the tools deployed to that end have grown formidably sophisticated. Interfaces are engineered to exploit the predictable biases of human psychology, dispensing intermittent rewards that mimic the mechanisms underlying compulsive behaviour. The result is an environment optimised not for the user's considered interests but for the maximisation of engagement, a metric that correlates only loosely with genuine satisfaction. Critics argue that this arrangement constitutes a quiet expropriation, harvesting a finite and irreplaceable human faculty for commercial ends while externalising the costs onto users in the form of distraction and diminished autonomy. Defenders counter that participation is voluntary and the services provided in exchange are valuable. Yet the language of free choice sits uneasily beside design practices expressly calibrated to circumvent deliberate decision-making. The deeper question is whether a marketplace built upon the systematic exploitation of cognitive vulnerability can be reconciled with any robust conception of consumer autonomy, or whether new safeguards have become indispensable.",
      questions:[
        { q:"What is identified as the truly scarce resource today?", options:["Available content","Human attention","Digital infrastructure"], answer:1 },
        { q:"How are interfaces engineered, according to the passage?", options:["To minimise time spent on the platform","To exploit predictable psychological biases","To prioritise the user's considered interests"], answer:1 },
        { q:"Why do critics call the arrangement a 'quiet expropriation'?", options:["It charges hidden subscription fees","It harvests a finite human faculty for commercial ends","It steals users' personal property"], answer:1 },
        { q:"Why does the author find the 'free choice' defence uneasy?", options:["The services are entirely without value","Designs are calibrated to circumvent deliberate decision-making","Users are legally prohibited from leaving"], answer:1 }
      ]
    },
    {
      id:"r3-C1-09",
      title:"Biodiversity and the Web of Dependence",
      text:"The loss of a single species can seem a regrettable but contained misfortune, a discrete subtraction from nature's ledger. Ecological science reveals a far more entangled reality, in which organisms are bound together by intricate webs of dependence whose ramifications are difficult to foresee. The removal of a so-called keystone species, one whose influence on its ecosystem vastly exceeds its abundance, can precipitate cascading collapses that reconfigure an entire landscape. Predators suppress populations that would otherwise overgraze vegetation; pollinators sustain the plants on which countless other creatures rely; decomposers recycle nutrients without which the whole edifice would falter. Disturb one strand and the reverberations propagate through the system in ways that defy simple prediction. This interdependence renders biodiversity not a luxury to be preserved for its own sake alone, but a form of insurance against the shocks that ecosystems inevitably encounter. A diverse community contains redundancy, multiple species capable of fulfilling overlapping functions, so that the failure of one need not doom the whole. Homogenised systems, by contrast, are brittle, their stability hostage to the fate of a few dominant players. To erode biodiversity, therefore, is not merely to impoverish the world aesthetically but to dismantle the very resilience upon which our own survival ultimately depends.",
      questions:[
        { q:"What is a keystone species?", options:["The most abundant species in an ecosystem","One whose influence vastly exceeds its abundance","A species with no ecological role"], answer:1 },
        { q:"Why does removing one species have unpredictable effects?", options:["Organisms are bound by intricate webs of dependence","Species are entirely independent of one another","Ecosystems are simple and easy to model"], answer:0 },
        { q:"How does the author characterise the value of biodiversity?", options:["A purely aesthetic luxury","A form of insurance against ecological shocks","An obstacle to ecosystem stability"], answer:1 },
        { q:"Why are homogenised systems described as brittle?", options:["They contain too much redundancy","Their stability is hostage to a few dominant players","They have too many keystone species"], answer:1 }
      ]
    },
    {
      id:"r3-C1-10",
      title:"The Myth of the Lone Genius",
      text:"Popular accounts of intellectual achievement gravitate toward the figure of the solitary genius, the singular mind that, through sheer brilliance, wrests revolutionary insight from the void. This romantic image flatters our appetite for heroes, but it distorts the actual texture of discovery. Innovations almost never spring fully formed from an isolated intellect; they emerge from dense networks of collaboration, correspondence, and incremental contribution, much of it unacknowledged. The celebrated breakthrough typically rests upon a scaffolding of prior work, assembled by predecessors whose names history has forgotten and refined by contemporaries whose roles the official narrative elides. Even the most original thinkers are, in a profound sense, products of their intellectual milieu, drawing upon the available stock of concepts, instruments, and questions that their era makes thinkable. The phenomenon of simultaneous independent discovery, in which the same idea surfaces in several minds at once, attests to the degree to which insight is conditioned by shared circumstance rather than individual exceptionality. To venerate the lone genius is thus to misunderstand creativity as an attribute of persons rather than a property of communities. Recognising the collective foundations of achievement need not diminish individual brilliance, but it does relocate that brilliance within the social fabric that makes it possible.",
      questions:[
        { q:"What does the romantic image of the lone genius distort?", options:["The actual collaborative texture of discovery","The intelligence of famous thinkers","The importance of formal education"], answer:0 },
        { q:"What does simultaneous independent discovery suggest?", options:["Geniuses copy one another's work","Insight is conditioned by shared circumstance","Original ideas can never recur"], answer:1 },
        { q:"How does the author view creativity?", options:["As an attribute solely of exceptional persons","As partly a property of communities","As impossible without isolation"], answer:1 },
        { q:"What does recognising collective foundations achieve, per the author?", options:["It eliminates the notion of individual brilliance","It relocates brilliance within a social fabric","It proves geniuses do not exist"], answer:1 }
      ]
    },
    {
      id:"r3-C1-11",
      title:"Privacy in the Age of Data",
      text:"The traditional conception of privacy as the right to be left alone, to seclude oneself from unwanted observation, has been quietly outpaced by the realities of a data-saturated society. The threat to contemporary privacy arises less from any single intrusive gaze than from the aggregation of countless innocuous fragments. A solitary purchase, location ping, or search query reveals little; assembled and cross-referenced at scale, however, such fragments compose a portrait of startling intimacy, exposing habits, beliefs, and vulnerabilities their subject never knowingly disclosed. This aggregative power confounds the consent-based frameworks that govern data collection, for individuals cannot meaningfully consent to inferences they cannot foresee, drawn from combinations they never contemplated. Moreover, privacy has historically been treated as an individual prerogative, yet the modern reality is irreducibly social. The data I surrender about myself frequently implicates others who share my characteristics, my contacts, or my circumstances, rendering personal control an inadequate safeguard. To insist that privacy is merely the concern of those with something to hide misconstrues its function. Privacy underwrites the freedom to experiment, to dissent, and to form one's identity beyond the chilling pressure of perpetual scrutiny. Its erosion threatens not only individuals but the very conditions under which an open society sustains itself.",
      questions:[
        { q:"From what does the modern threat to privacy chiefly arise?", options:["A single intrusive observer","The aggregation of countless innocuous fragments","The absence of any data collection"], answer:1 },
        { q:"Why do consent-based frameworks struggle?", options:["People cannot foresee the inferences drawn from combined data","Consent forms are too short","Nobody ever agrees to anything"], answer:0 },
        { q:"Why is personal control described as inadequate?", options:["Data about oneself often implicates others","Individuals always act recklessly","Privacy is unimportant socially"], answer:0 },
        { q:"What broader function of privacy does the author emphasise?", options:["It shields wrongdoers from justice","It underwrites freedom to dissent and form identity","It mainly protects commercial secrets"], answer:1 }
      ]
    },
    {
      id:"r3-C1-12",
      title:"The Problem of Free Will",
      text:"Few philosophical puzzles prove as stubbornly resistant to resolution as the question of free will. If the universe unfolds according to deterministic laws, with each event the inevitable consequence of antecedent causes, then our choices would appear to be the predetermined outputs of prior states, no freer than the trajectory of a falling stone. Introducing randomness offers scant relief, for an action issuing from sheer chance seems no more authored by us than one dictated by necessity. The dilemma thus appears to foreclose freedom whether the world is deterministic or not. Compatibilists endeavour to dissolve rather than solve this impasse, arguing that the freedom worth wanting was never freedom from causation in the first place. On their account, an action is free when it flows from one's own deliberation, desires, and character, unimpeded by external compulsion, regardless of whether those very desires were themselves caused. Critics retort that this redefinition merely renames the problem, leaving untouched the unsettling intuition that we could not have done otherwise. Whatever its eventual verdict, the debate carries weight far beyond the seminar room, for our practices of praise, blame, and punishment rest upon assumptions about responsibility that the spectre of determinism threatens to undermine.",
      questions:[
        { q:"Why does determinism seem to threaten free will?", options:["Choices appear to be predetermined outputs of prior causes","The universe contains too much randomness","Laws of nature do not exist"], answer:0 },
        { q:"Why does adding randomness fail to rescue free will?", options:["Random actions still feel predetermined","An action from sheer chance is no more authored by us","Randomness restores full determinism"], answer:1 },
        { q:"How do compatibilists approach the problem?", options:["They prove the universe is not deterministic","They redefine the freedom worth wanting","They deny that choices exist"], answer:1 },
        { q:"Why does the debate matter beyond philosophy?", options:["It determines the laws of physics","Practices of praise, blame, and punishment rest on responsibility","It has no practical consequences whatsoever"], answer:1 }
      ]
    }
  ]);
})();
