(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P = (track,lvl,arr)=>{C[track]=C[track]||{};C[track][lvl]=C[track][lvl]||[];arr.forEach(x=>C[track][lvl].push(x));};
  P("vocab","C2",[
    { id:"v3-C2-01", en:"perspicacious", ru:"проницательный, дальновидный", ex:"Her perspicacious analysis exposed flaws no one else had noticed." },
    { id:"v3-C2-02", en:"obfuscate", ru:"намеренно запутывать, затемнять смысл", ex:"The report seemed designed to obfuscate rather than to clarify." },
    { id:"v3-C2-03", en:"sycophant", ru:"подхалим, льстец", ex:"The minister surrounded himself with sycophants who never dared disagree." },
    { id:"v3-C2-04", en:"ineffable", ru:"невыразимый словами", ex:"She described an ineffable joy that no language could capture." },
    { id:"v3-C2-05", en:"pusillanimous", ru:"малодушный, трусливый", ex:"His pusillanimous retreat from the debate disappointed his supporters." },
    { id:"v3-C2-06", en:"sangfroid", ru:"хладнокровие, самообладание", ex:"She handled the crisis with remarkable sangfroid." },
    { id:"v3-C2-07", en:"recondite", ru:"малопонятный, эзотерический", ex:"The lecture descended into recondite details only specialists could follow." },
    { id:"v3-C2-08", en:"limn", ru:"живописать, изображать (словами)", ex:"The novel limns provincial life with quiet precision." },
    { id:"v3-C2-09", en:"truculent", ru:"задиристый, агрессивно-враждебный", ex:"He grew truculent whenever his authority was questioned." },
    { id:"v3-C2-10", en:"obsequious", ru:"раболепный, угодливый", ex:"The waiter's obsequious manner made the guests uncomfortable." },
    { id:"v3-C2-11", en:"perfidious", ru:"вероломный, предательский", ex:"His perfidious conduct cost him every remaining ally." },
    { id:"v3-C2-12", en:"quotidian", ru:"повседневный, будничный", ex:"She found poetry in the quotidian routines of the household." },
    { id:"v3-C2-13", en:"susurration", ru:"шёпот, шелест", ex:"A faint susurration of leaves filled the empty courtyard." },
    { id:"v3-C2-14", en:"vituperative", ru:"бранный, поносящий", ex:"The critic's vituperative review bordered on the cruel." },
    { id:"v3-C2-15", en:"nugatory", ru:"ничтожный, никчёмный", ex:"The committee dismissed his objection as nugatory." },
    { id:"v3-C2-16", en:"propitiate", ru:"умилостивлять, задабривать", ex:"They offered gifts to propitiate the offended elder." },
    { id:"v3-C2-17", en:"lugubrious", ru:"мрачный, скорбный (порой комично)", ex:"He delivered the news in a lugubrious tone better suited to a funeral." },
    { id:"v3-C2-18", en:"effulgence", ru:"сияние, лучезарность", ex:"The dawn cast an effulgence over the snow-covered peaks." },
    { id:"v3-C2-19", en:"mendacity", ru:"лживость, склонность ко лжи", ex:"The trial revealed the witness's habitual mendacity." },
    { id:"v3-C2-20", en:"saturnine", ru:"угрюмый, мрачно-задумчивый", ex:"His saturnine expression discouraged any small talk." },
    { id:"v3-C2-21", en:"peregrination", ru:"странствие, скитание", ex:"His youthful peregrinations took him across three continents." },
    { id:"v3-C2-22", en:"contumacious", ru:"непокорный, упорно строптивый", ex:"The contumacious defendant refused every order of the court." },
    { id:"v3-C2-23", en:"apotheosis", ru:"апофеоз, высшая точка", ex:"The festival was the apotheosis of the city's cultural ambitions." },
    { id:"v3-C2-24", en:"fulminate", ru:"громогласно осуждать, метать громы", ex:"The editorial fulminated against the new tax for weeks." },
    { id:"v3-C2-25", en:"diaphanous", ru:"прозрачный, полупрозрачный (о ткани)", ex:"She wore a diaphanous gown that shimmered in the candlelight." },
    { id:"v3-C2-26", en:"animadversion", ru:"порицание, критическое замечание", ex:"His memoir is full of sharp animadversions on his rivals." },
    { id:"v3-C2-27", en:"vicissitude", ru:"превратность, перемена судьбы", ex:"He endured the vicissitudes of fortune with stoic calm." },
    { id:"v3-C2-28", en:"perspicuity", ru:"ясность, вразумительность (изложения)", ex:"The treatise is admired for its perspicuity and elegance." },
    { id:"v3-C2-29", en:"sesquipedalian", ru:"многосложный, любящий длинные слова", ex:"His sesquipedalian prose obscured an otherwise simple idea." },
    { id:"v3-C2-30", en:"velleity", ru:"слабое желание без воли к действию", ex:"His ambition never rose above a vague velleity." },
    { id:"v3-C2-31", en:"objurgate", ru:"бранить, сурово отчитывать", ex:"The headmaster objurgated the boys for their negligence." },
    { id:"v3-C2-32", en:"caliginous", ru:"тёмный, туманный, мглистый", ex:"They groped through the caliginous corridors of the old mine." },
    { id:"v3-C2-33", en:"hebetude", ru:"тупость, умственная вялость", ex:"The afternoon heat induced a general hebetude in the office." },
    { id:"v3-C2-34", en:"adumbrate", ru:"набрасывать в общих чертах, предвещать", ex:"The opening chapter adumbrates the tragedy to come." },
    { id:"v3-C2-35", en:"luculent", ru:"ясный, прозрачный (о мысли, изложении)", ex:"Her luculent summary made the contract intelligible to laymen." },
    { id:"v3-C2-36", en:"pellucid", ru:"кристально ясный, прозрачный", ex:"His pellucid explanation dispelled every doubt in the room." },
    { id:"v3-C2-37", en:"farrago", ru:"мешанина, бессвязное нагромождение", ex:"The speech was a farrago of clichés and half-truths." },
    { id:"v3-C2-38", en:"refulgent", ru:"лучезарный, ослепительно яркий", ex:"The cathedral's refulgent windows blazed in the morning sun." },
    { id:"v3-C2-39", en:"importunate", ru:"назойливый, докучливый", ex:"He grew weary of the importunate demands of his creditors." },
    { id:"v3-C2-40", en:"sempiternal", ru:"вечный, нескончаемый", ex:"They spoke of love as if it were sempiternal." },
    { id:"v3-C2-41", en:"deliquesce", ru:"расплываться, таять, растворяться", ex:"Her resolve seemed to deliquesce under his steady gaze." },
    { id:"v3-C2-42", en:"opprobrium", ru:"позор, публичное осуждение", ex:"The scandal heaped opprobrium on the once-revered institution." },
    { id:"v3-C2-43", en:"jejune", ru:"пресный, незрелый, скудный", ex:"Critics found his early poems jejune and derivative." },
    { id:"v3-C2-44", en:"cynosure", ru:"центр всеобщего внимания", ex:"In her crimson dress she was the cynosure of the gala." },
    { id:"v3-C2-45", en:"insouciance", ru:"беспечность, беззаботность", ex:"He shrugged off the rebuke with characteristic insouciance." },
    { id:"v3-C2-46", en:"maunder", ru:"бессвязно болтать, бродить без цели", ex:"The old man would maunder for hours about his youth." },
    { id:"v3-C2-47", en:"trenchant", ru:"острый, проницательный (о критике)", ex:"Her trenchant wit left no pretension unpunctured." },
    { id:"v3-C2-48", en:"palliate", ru:"смягчать, облегчать (не устраняя)", ex:"The measures merely palliate the symptoms of a deeper crisis." },
    { id:"v3-C2-49", en:"esculent", ru:"съедобный, годный в пищу", ex:"They foraged for esculent roots along the riverbank." },
    { id:"v3-C2-50", en:"recrudescence", ru:"возобновление, рецидив (нежелательного)", ex:"The treaty failed to prevent a recrudescence of hostilities." },
    { id:"v3-C2-51", en:"supererogatory", ru:"сверхдолжный, излишний", ex:"His apology was generous to the point of being supererogatory." },
    { id:"v3-C2-52", en:"pertinacious", ru:"упорный, цепкий, настойчивый", ex:"Her pertinacious questioning eventually wore down the witness." },
    { id:"v3-C2-53", en:"crepuscular", ru:"сумеречный", ex:"The forest took on a crepuscular gloom long before sunset." },
    { id:"v3-C2-54", en:"emolument", ru:"вознаграждение, жалованье", ex:"He accepted the post for its prestige rather than its emoluments." },
    { id:"v3-C2-55", en:"feculent", ru:"мутный, грязный, нечистый", ex:"The river ran feculent and dark below the abandoned mills." },
    { id:"v3-C2-56", en:"gasconade", ru:"бахвальство, хвастовство", ex:"His memoir reads more as gasconade than as honest reflection." },
    { id:"v3-C2-57", en:"inanition", ru:"истощение, изнеможение (от голода)", ex:"The survivors were near inanition when the rescuers arrived." },
    { id:"v3-C2-58", en:"obnubilate", ru:"затуманивать, заволакивать", ex:"Fatigue began to obnubilate his usually sharp judgment." },
    { id:"v3-C2-59", en:"pleonasm", ru:"плеоназм, речевая избыточность", ex:"\"Free gift\" is a pleonasm that editors quietly delete." },
    { id:"v3-C2-60", en:"quiescent", ru:"бездействующий, покоящийся", ex:"The volcano had remained quiescent for over a century." },
    { id:"v3-C2-61", en:"rebarbative", ru:"отталкивающий, неприятный", ex:"His rebarbative manner alienated even his closest colleagues." },
    { id:"v3-C2-62", en:"susurrous", ru:"шелестящий, шепчущий", ex:"A susurrous breeze drifted through the orchard at dusk." },
    { id:"v3-C2-63", en:"thaumaturgy", ru:"чудотворство, магия", ex:"To the villagers, his medicine seemed closer to thaumaturgy." },
    { id:"v3-C2-64", en:"umbrageous", ru:"тенистый; обидчивый", ex:"They rested in the umbrageous shade of the old oaks." },
    { id:"v3-C2-65", en:"verisimilitude", ru:"правдоподобие, достоверность", ex:"The film's verisimilitude owed much to its meticulous research." },
    { id:"v3-C2-66", en:"wonted", ru:"привычный, обыкновенный", ex:"He returned to his wonted seat by the window." },
    { id:"v3-C2-67", en:"abnegation", ru:"самоотречение, отказ от своего", ex:"Her life of abnegation inspired generations of disciples." },
    { id:"v3-C2-68", en:"bowdlerize", ru:"выхолащивать, цензурировать текст", ex:"Editors bowdlerized the play to suit a timid audience." },
    { id:"v3-C2-69", en:"comminatory", ru:"угрожающий, грозящий карой", ex:"The decree was couched in comminatory, almost biblical language." },
    { id:"v3-C2-70", en:"desuetude", ru:"неупотребление, забвение", ex:"The custom fell into desuetude after the war." },
    { id:"v3-C2-71", en:"eleemosynary", ru:"благотворительный", ex:"The hospital was founded on purely eleemosynary principles." },
    { id:"v3-C2-72", en:"fissiparous", ru:"раскольнический, склонный к дроблению", ex:"The movement grew fissiparous, splintering into rival factions." },
    { id:"v3-C2-73", en:"grandiloquent", ru:"высокопарный, напыщенный", ex:"His grandiloquent toast outlasted the patience of every guest." },
    { id:"v3-C2-74", en:"hagiography", ru:"житие; некритично хвалебная биография", ex:"The biography reads as hagiography, blind to its subject's faults." },
    { id:"v3-C2-75", en:"imbroglio", ru:"запутанное затруднительное положение", ex:"The merger collapsed amid a legal imbroglio." },
    { id:"v3-C2-76", en:"lachrymose", ru:"слезливый, плаксивый", ex:"The film's lachrymose finale struck many as manipulative." },
    { id:"v3-C2-77", en:"mellifluous", ru:"сладкозвучный, медоточивый", ex:"Her mellifluous voice held the entire hall in thrall." },
    { id:"v3-C2-78", en:"nescience", ru:"невежество, неведение", ex:"He confessed a cheerful nescience of modern art." },
    { id:"v3-C2-79", en:"obstreperous", ru:"шумный, буйный, несдержанный", ex:"The obstreperous crowd refused to let the speaker continue." },
    { id:"v3-C2-80", en:"pulchritude", ru:"физическая красота", ex:"The poem extols the pulchritude of the northern coast." }
  ]);
})();
