(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("vocab","B2",[
    // мнения/аргументы
    { id:"v4-B2-01", en:"to put it bluntly", ru:"если говорить прямо", ex:"To put it bluntly, the plan was never going to work." },
    { id:"v4-B2-02", en:"compelling argument", ru:"убедительный аргумент", ex:"She made a compelling argument for raising taxes." },
    { id:"v4-B2-03", en:"to concede a point", ru:"признать правоту в споре", ex:"He was reluctant to concede the point, but the evidence was clear." },
    { id:"v4-B2-04", en:"to play devil's advocate", ru:"спорить ради спора", ex:"Let me play devil's advocate for a moment and challenge that idea." },
    { id:"v4-B2-05", en:"flawed reasoning", ru:"ошибочная логика", ex:"The whole proposal rests on flawed reasoning." },
    { id:"v4-B2-06", en:"to take issue with", ru:"не соглашаться с", ex:"I take issue with the assumption that growth is always good." },
    { id:"v4-B2-07", en:"a valid point", ru:"справедливое замечание", ex:"You raise a valid point about the cost." },
    { id:"v4-B2-08", en:"to overstate the case", ru:"преувеличивать", ex:"Critics tend to overstate the case against nuclear power." },
    { id:"v4-B2-09", en:"on closer inspection", ru:"при ближайшем рассмотрении", ex:"On closer inspection, the figures don't add up." },
    { id:"v4-B2-10", en:"to back up a claim", ru:"подкрепить утверждение", ex:"You need data to back up that claim." },

    // абстрактные понятия
    { id:"v4-B2-11", en:"ambiguity", ru:"двусмысленность", ex:"The contract was full of ambiguity that lawyers later exploited." },
    { id:"v4-B2-12", en:"paradox", ru:"парадокс", ex:"It's a paradox that the more we connect online, the lonelier we feel." },
    { id:"v4-B2-13", en:"nuance", ru:"нюанс, оттенок", ex:"The translation lost the nuance of the original poem." },
    { id:"v4-B2-14", en:"premise", ru:"исходная посылка", ex:"The argument fails because its premise is wrong." },
    { id:"v4-B2-15", en:"connotation", ru:"коннотация, подтекст", ex:"The word 'cheap' carries a negative connotation." },
    { id:"v4-B2-16", en:"dichotomy", ru:"дихотомия, противопоставление", ex:"The false dichotomy between work and family ignores other options." },
    { id:"v4-B2-17", en:"abstraction", ru:"абстракция", ex:"Freedom is an abstraction until you actually lose it." },
    { id:"v4-B2-18", en:"implication", ru:"следствие, подтекст", ex:"The implications of the discovery are far-reaching." },
    { id:"v4-B2-19", en:"notion", ru:"понятие, представление", ex:"The notion that money buys happiness is widely debated." },
    { id:"v4-B2-20", en:"prerequisite", ru:"необходимое условие", ex:"Trust is a prerequisite for any lasting partnership." },

    // наука/исследования
    { id:"v4-B2-21", en:"hypothesis", ru:"гипотеза", ex:"The hypothesis was confirmed after years of testing." },
    { id:"v4-B2-22", en:"to conduct a study", ru:"проводить исследование", ex:"Researchers conducted a study on sleep deprivation." },
    { id:"v4-B2-23", en:"correlation", ru:"корреляция, взаимосвязь", ex:"Correlation does not imply causation." },
    { id:"v4-B2-24", en:"empirical evidence", ru:"эмпирические данные", ex:"There is little empirical evidence to support the theory." },
    { id:"v4-B2-25", en:"sample size", ru:"размер выборки", ex:"The results are unreliable due to a small sample size." },
    { id:"v4-B2-26", en:"peer-reviewed", ru:"прошедший рецензирование", ex:"The findings were published in a peer-reviewed journal." },
    { id:"v4-B2-27", en:"to replicate results", ru:"воспроизвести результаты", ex:"Other labs failed to replicate the original results." },
    { id:"v4-B2-28", en:"breakthrough", ru:"прорыв", ex:"The vaccine was a major breakthrough in medicine." },
    { id:"v4-B2-29", en:"variable", ru:"переменная", ex:"They controlled for every variable in the experiment." },
    { id:"v4-B2-30", en:"to yield findings", ru:"дать результаты", ex:"The survey yielded surprising findings." },

    // общество/политика
    { id:"v4-B2-31", en:"social cohesion", ru:"социальная сплочённость", ex:"Migration can either strengthen or weaken social cohesion." },
    { id:"v4-B2-32", en:"to enact a law", ru:"принять закон", ex:"Parliament enacted a law banning single-use plastics." },
    { id:"v4-B2-33", en:"polarisation", ru:"поляризация", ex:"Political polarisation has deepened over the last decade." },
    { id:"v4-B2-34", en:"grassroots movement", ru:"низовое движение", ex:"The campaign began as a grassroots movement of volunteers." },
    { id:"v4-B2-35", en:"the electorate", ru:"электорат, избиратели", ex:"The party lost touch with the electorate." },
    { id:"v4-B2-36", en:"civil liberties", ru:"гражданские свободы", ex:"The new law threatens basic civil liberties." },
    { id:"v4-B2-37", en:"to hold accountable", ru:"привлекать к ответственности", ex:"Voters can hold politicians accountable at the ballot box." },
    { id:"v4-B2-38", en:"vested interest", ru:"корыстный интерес", ex:"Oil companies have a vested interest in delaying reform." },
    { id:"v4-B2-39", en:"social mobility", ru:"социальная мобильность", ex:"Education is meant to improve social mobility." },
    { id:"v4-B2-40", en:"to mobilise support", ru:"мобилизовать поддержку", ex:"The leader mobilised support among young voters." },

    // бизнес/экономика
    { id:"v4-B2-41", en:"market share", ru:"доля рынка", ex:"The company doubled its market share in two years." },
    { id:"v4-B2-42", en:"to scale up", ru:"масштабировать", ex:"They struggled to scale up production fast enough." },
    { id:"v4-B2-43", en:"profit margin", ru:"норма прибыли", ex:"Rising costs squeezed the firm's profit margins." },
    { id:"v4-B2-44", en:"supply and demand", ru:"спрос и предложение", ex:"Prices are driven by supply and demand." },
    { id:"v4-B2-45", en:"to diversify", ru:"диверсифицировать", ex:"Investors are advised to diversify their portfolios." },
    { id:"v4-B2-46", en:"competitive edge", ru:"конкурентное преимущество", ex:"Innovation gives the startup a competitive edge." },
    { id:"v4-B2-47", en:"overheads", ru:"накладные расходы", ex:"Working remotely cut the company's overheads." },
    { id:"v4-B2-48", en:"to break even", ru:"выйти в ноль", ex:"The business expects to break even within a year." },
    { id:"v4-B2-49", en:"recession", ru:"рецессия, спад", ex:"Many firms went bankrupt during the recession." },
    { id:"v4-B2-50", en:"return on investment", ru:"окупаемость вложений", ex:"The campaign delivered a strong return on investment." },

    // тонкое описание характера
    { id:"v4-B2-51", en:"meticulous", ru:"дотошный, скрупулёзный", ex:"She is meticulous about every detail of her work." },
    { id:"v4-B2-52", en:"aloof", ru:"отстранённый, холодный", ex:"He came across as aloof at the party." },
    { id:"v4-B2-53", en:"down-to-earth", ru:"приземлённый, простой", ex:"Despite her fame, she stays down-to-earth." },
    { id:"v4-B2-54", en:"self-effacing", ru:"скромный, не выпячивающий себя", ex:"His self-effacing humour made him likeable." },
    { id:"v4-B2-55", en:"opinionated", ru:"имеющий твёрдое мнение, упрямый", ex:"He's too opinionated to admit he might be wrong." },
    { id:"v4-B2-56", en:"resourceful", ru:"находчивый", ex:"A resourceful manager finds solutions with limited budgets." },
    { id:"v4-B2-57", en:"complacent", ru:"самодовольный, благодушный", ex:"The team grew complacent after a few easy wins." },
    { id:"v4-B2-58", en:"perceptive", ru:"проницательный", ex:"She made a perceptive remark about his real motives." },
    { id:"v4-B2-59", en:"reserved", ru:"сдержанный, замкнутый", ex:"He's quite reserved until you get to know him." },
    { id:"v4-B2-60", en:"tenacious", ru:"упорный, цепкий", ex:"Her tenacious attitude helped her finish the project." },

    // эмоции/психология
    { id:"v4-B2-61", en:"overwhelmed", ru:"подавленный, перегруженный", ex:"He felt overwhelmed by the workload." },
    { id:"v4-B2-62", en:"resentment", ru:"обида, негодование", ex:"Years of unfair treatment bred deep resentment." },
    { id:"v4-B2-63", en:"apprehensive", ru:"тревожный, опасающийся", ex:"She was apprehensive about the interview." },
    { id:"v4-B2-64", en:"coping mechanism", ru:"механизм совладания", ex:"Exercise is his main coping mechanism for stress." },
    { id:"v4-B2-65", en:"to come to terms with", ru:"смириться с", ex:"It took years to come to terms with the loss." },
    { id:"v4-B2-66", en:"self-conscious", ru:"стесняющийся, неловкий", ex:"He felt self-conscious about his accent." },
    { id:"v4-B2-67", en:"elation", ru:"восторг, ликование", ex:"A wave of elation swept over the crowd." },
    { id:"v4-B2-68", en:"to bottle up emotions", ru:"подавлять эмоции", ex:"Bottling up emotions can harm your health." },
    { id:"v4-B2-69", en:"vulnerable", ru:"уязвимый", ex:"Sharing your fears can make you feel vulnerable." },
    { id:"v4-B2-70", en:"resilience", ru:"стрессоустойчивость, жизнестойкость", ex:"Children show remarkable resilience after hardship." },

    // коллокации
    { id:"v4-B2-71", en:"to make a profound impact", ru:"оказать глубокое влияние", ex:"The teacher made a profound impact on her students." },
    { id:"v4-B2-72", en:"to draw a conclusion", ru:"делать вывод", ex:"It's too early to draw any firm conclusions." },
    { id:"v4-B2-73", en:"to meet a deadline", ru:"уложиться в срок", ex:"We worked all night to meet the deadline." },
    { id:"v4-B2-74", en:"to pose a threat", ru:"представлять угрозу", ex:"Climate change poses a serious threat to coastal cities." },
    { id:"v4-B2-75", en:"to strike a balance", ru:"найти баланс", ex:"It's hard to strike a balance between work and rest." },
    { id:"v4-B2-76", en:"to raise awareness", ru:"повышать осведомлённость", ex:"The charity works to raise awareness of mental health." },
    { id:"v4-B2-77", en:"to take into account", ru:"принимать во внимание", ex:"We must take the side effects into account." },
    { id:"v4-B2-78", en:"to gain momentum", ru:"набирать обороты", ex:"The movement is gaining momentum across Europe." },
    { id:"v4-B2-79", en:"to bear the brunt", ru:"принять основной удар", ex:"Low-income families bear the brunt of inflation." },
    { id:"v4-B2-80", en:"to set a precedent", ru:"создать прецедент", ex:"The ruling set a precedent for future cases." },

    // синонимы частых слов
    { id:"v4-B2-81", en:"crucial", ru:"крайне важный (важный)", ex:"Timing is crucial in negotiations." },
    { id:"v4-B2-82", en:"substantial", ru:"значительный (большой)", ex:"They made a substantial profit last year." },
    { id:"v4-B2-83", en:"to obtain", ru:"получать (get)", ex:"You must obtain permission before filming." },
    { id:"v4-B2-84", en:"to demonstrate", ru:"показывать (show)", ex:"The study demonstrates a clear link between diet and health." },
    { id:"v4-B2-85", en:"numerous", ru:"многочисленный (many)", ex:"There are numerous reasons to be optimistic." },
    { id:"v4-B2-86", en:"to acquire", ru:"приобретать (get)", ex:"She acquired fluency in three languages." },
    { id:"v4-B2-87", en:"adequate", ru:"достаточный (enough)", ex:"The funding is barely adequate for the project." },
    { id:"v4-B2-88", en:"to highlight", ru:"подчёркивать (show)", ex:"The report highlights the need for reform." },
    { id:"v4-B2-89", en:"significant", ru:"существенный (important)", ex:"There was a significant drop in sales." },
    { id:"v4-B2-90", en:"to comprehend", ru:"понимать (understand)", ex:"It's hard to comprehend the scale of the disaster." },

    // фразы для дискуссии
    { id:"v4-B2-91", en:"as far as I'm concerned", ru:"что касается меня", ex:"As far as I'm concerned, the matter is settled." },
    { id:"v4-B2-92", en:"there's no denying that", ru:"нельзя отрицать, что", ex:"There's no denying that the situation has improved." },
    { id:"v4-B2-93", en:"to be fair", ru:"справедливости ради", ex:"To be fair, he did warn us in advance." },
    { id:"v4-B2-94", en:"that said", ru:"тем не менее, при этом", ex:"The plan is risky. That said, it could pay off." },
    { id:"v4-B2-95", en:"it could be argued that", ru:"можно утверждать, что", ex:"It could be argued that the policy did more harm than good." },
    { id:"v4-B2-96", en:"on the one hand", ru:"с одной стороны", ex:"On the one hand it's cheaper, on the other it's slower." },
    { id:"v4-B2-97", en:"I'm inclined to think", ru:"я склонен думать", ex:"I'm inclined to think we should wait." },
    { id:"v4-B2-98", en:"to put things in perspective", ru:"взглянуть трезво, расставить по местам", ex:"To put things in perspective, this is a minor setback." },
    { id:"v4-B2-99", en:"having said that", ru:"и всё же, при этом", ex:"Having said that, I do see your point." },
    { id:"v4-B2-100", en:"more often than not", ru:"чаще всего", ex:"More often than not, simple solutions work best." },

    // природа/климат
    { id:"v4-B2-101", en:"carbon footprint", ru:"углеродный след", ex:"Flying less is one way to cut your carbon footprint." },
    { id:"v4-B2-102", en:"biodiversity", ru:"биоразнообразие", ex:"Deforestation threatens local biodiversity." },
    { id:"v4-B2-103", en:"renewable energy", ru:"возобновляемая энергия", ex:"The country now runs largely on renewable energy." },
    { id:"v4-B2-104", en:"to deplete resources", ru:"истощать ресурсы", ex:"Overfishing depletes ocean resources." },
    { id:"v4-B2-105", en:"emissions", ru:"выбросы", ex:"Governments pledged to halve emissions by 2030." },
    { id:"v4-B2-106", en:"ecosystem", ru:"экосистема", ex:"A single species can keep an entire ecosystem in balance." },
    { id:"v4-B2-107", en:"sustainable", ru:"устойчивый, экологичный", ex:"They promote sustainable farming practices." },
    { id:"v4-B2-108", en:"extreme weather", ru:"экстремальная погода", ex:"Extreme weather events are becoming more frequent." },
    { id:"v4-B2-109", en:"to offset emissions", ru:"компенсировать выбросы", ex:"The airline offsets emissions by planting trees." },
    { id:"v4-B2-110", en:"habitat loss", ru:"утрата среды обитания", ex:"Habitat loss is the main cause of extinction." },

    // культура/искусство
    { id:"v4-B2-111", en:"thought-provoking", ru:"заставляющий задуматься", ex:"It was a thought-provoking documentary." },
    { id:"v4-B2-112", en:"masterpiece", ru:"шедевр", ex:"The novel is widely regarded as a masterpiece." },
    { id:"v4-B2-113", en:"to convey meaning", ru:"передавать смысл", ex:"The painting conveys a sense of loneliness." },
    { id:"v4-B2-114", en:"avant-garde", ru:"авангардный", ex:"Her avant-garde designs shocked the critics." },
    { id:"v4-B2-115", en:"cultural heritage", ru:"культурное наследие", ex:"The site is part of the country's cultural heritage." },
    { id:"v4-B2-116", en:"to resonate with", ru:"находить отклик у", ex:"The story resonated with millions of readers." },
    { id:"v4-B2-117", en:"contemporary art", ru:"современное искусство", ex:"The gallery specialises in contemporary art." },
    { id:"v4-B2-118", en:"overrated", ru:"переоценённый", ex:"Many critics think the film is overrated." },
    { id:"v4-B2-119", en:"to push boundaries", ru:"раздвигать границы", ex:"The artist constantly pushes creative boundaries." },
    { id:"v4-B2-120", en:"acclaimed", ru:"признанный, отмеченный критиками", ex:"The director's acclaimed debut won several awards." },

    // СМИ/реклама
    { id:"v4-B2-121", en:"target audience", ru:"целевая аудитория", ex:"The ad missed its target audience completely." },
    { id:"v4-B2-122", en:"to go viral", ru:"стать вирусным", ex:"The video went viral overnight." },
    { id:"v4-B2-123", en:"clickbait", ru:"кликбейт", ex:"The headline turned out to be pure clickbait." },
    { id:"v4-B2-124", en:"biased coverage", ru:"предвзятое освещение", ex:"Readers accused the paper of biased coverage." },
    { id:"v4-B2-125", en:"brand awareness", ru:"узнаваемость бренда", ex:"The campaign boosted brand awareness significantly." },
    { id:"v4-B2-126", en:"to manipulate public opinion", ru:"манипулировать общественным мнением", ex:"Some outlets manipulate public opinion through fear." },
    { id:"v4-B2-127", en:"endorsement", ru:"одобрение, реклама знаменитостью", ex:"The product got a celebrity endorsement." },
    { id:"v4-B2-128", en:"misinformation", ru:"дезинформация", ex:"Social media spreads misinformation rapidly." },
    { id:"v4-B2-129", en:"to sensationalise", ru:"подавать сенсационно, раздувать", ex:"Tabloids tend to sensationalise minor events." },
    { id:"v4-B2-130", en:"subscription model", ru:"модель подписки", ex:"The newspaper switched to a subscription model." },

    // право/преступность
    { id:"v4-B2-131", en:"to commit a crime", ru:"совершить преступление", ex:"He was accused of committing a serious crime." },
    { id:"v4-B2-132", en:"to convict", ru:"признать виновным", ex:"She was convicted of fraud last year." },
    { id:"v4-B2-133", en:"deterrent", ru:"сдерживающий фактор", ex:"Harsh sentences act as a deterrent to some criminals." },
    { id:"v4-B2-134", en:"to file a lawsuit", ru:"подать иск", ex:"The customer filed a lawsuit against the company." },
    { id:"v4-B2-135", en:"verdict", ru:"вердикт, приговор", ex:"The jury reached a unanimous verdict." },
    { id:"v4-B2-136", en:"to be acquitted", ru:"быть оправданным", ex:"He was acquitted due to lack of evidence." },
    { id:"v4-B2-137", en:"liability", ru:"ответственность (юр.)", ex:"The firm denied any liability for the accident." },
    { id:"v4-B2-138", en:"to enforce the law", ru:"обеспечивать соблюдение закона", ex:"Police struggle to enforce the new law." },
    { id:"v4-B2-139", en:"miscarriage of justice", ru:"судебная ошибка", ex:"His release exposed a shocking miscarriage of justice." },
    { id:"v4-B2-140", en:"to press charges", ru:"выдвигать обвинения", ex:"The victim decided not to press charges." },

    // технологии/ИИ
    { id:"v4-B2-141", en:"machine learning", ru:"машинное обучение", ex:"Machine learning powers most recommendation systems." },
    { id:"v4-B2-142", en:"to automate", ru:"автоматизировать", ex:"The factory automated its packaging process." },
    { id:"v4-B2-143", en:"algorithm", ru:"алгоритм", ex:"The algorithm decides what you see in your feed." },
    { id:"v4-B2-144", en:"data privacy", ru:"конфиденциальность данных", ex:"Users are increasingly worried about data privacy." },
    { id:"v4-B2-145", en:"to train a model", ru:"обучать модель", ex:"They trained the model on millions of images." },
    { id:"v4-B2-146", en:"bias in AI", ru:"предвзятость ИИ", ex:"Bias in AI can reinforce existing inequalities." },
    { id:"v4-B2-147", en:"cutting-edge", ru:"передовой", ex:"The lab uses cutting-edge technology." },
    { id:"v4-B2-148", en:"to disrupt an industry", ru:"перевернуть отрасль", ex:"Streaming disrupted the entire music industry." },
    { id:"v4-B2-149", en:"surveillance", ru:"слежка, наблюдение", ex:"Facial recognition raises concerns about surveillance." },
    { id:"v4-B2-150", en:"obsolete", ru:"устаревший", ex:"Many skills become obsolete within a decade." },

    // здоровье/медицина
    { id:"v4-B2-151", en:"chronic illness", ru:"хроническое заболевание", ex:"Managing a chronic illness requires daily care." },
    { id:"v4-B2-152", en:"to diagnose", ru:"диагностировать", ex:"The doctor diagnosed her with diabetes." },
    { id:"v4-B2-153", en:"immune system", ru:"иммунная система", ex:"Sleep strengthens the immune system." },
    { id:"v4-B2-154", en:"side effect", ru:"побочный эффект", ex:"The drug has few side effects." },
    { id:"v4-B2-155", en:"to be prone to", ru:"быть подверженным", ex:"Smokers are prone to lung disease." },
    { id:"v4-B2-156", en:"preventive care", ru:"профилактика", ex:"Preventive care reduces long-term costs." },
    { id:"v4-B2-157", en:"sedentary lifestyle", ru:"малоподвижный образ жизни", ex:"A sedentary lifestyle increases health risks." },
    { id:"v4-B2-158", en:"to recover from", ru:"выздоравливать после", ex:"It took weeks to recover from the surgery." },
    { id:"v4-B2-159", en:"mental wellbeing", ru:"психическое благополучие", ex:"Companies are investing in employees' mental wellbeing." },
    { id:"v4-B2-160", en:"outbreak", ru:"вспышка (болезни)", ex:"Health officials contained the outbreak quickly." },

    // глаголы для эссе
    { id:"v4-B2-161", en:"to illustrate", ru:"иллюстрировать, пояснять", ex:"This example illustrates the wider problem." },
    { id:"v4-B2-162", en:"to undermine", ru:"подрывать", ex:"Corruption undermines public trust." },
    { id:"v4-B2-163", en:"to advocate", ru:"выступать за", ex:"The author advocates stricter regulation." },
    { id:"v4-B2-164", en:"to attribute to", ru:"приписывать, объяснять (чем-то)", ex:"They attribute the success to teamwork." },
    { id:"v4-B2-165", en:"to exacerbate", ru:"усугублять", ex:"The drought exacerbated the food shortage." },
    { id:"v4-B2-166", en:"to alleviate", ru:"облегчать, смягчать", ex:"The policy aims to alleviate poverty." },
    { id:"v4-B2-167", en:"to contend", ru:"утверждать, доказывать", ex:"Some experts contend that the risk is overstated." },
    { id:"v4-B2-168", en:"to stem from", ru:"проистекать из", ex:"Many problems stem from poor communication." },
    { id:"v4-B2-169", en:"to outweigh", ru:"перевешивать", ex:"The benefits clearly outweigh the costs." },
    { id:"v4-B2-170", en:"to reinforce", ru:"укреплять, усиливать", ex:"The data reinforce earlier conclusions." },

    // прилагательные-оценки
    { id:"v4-B2-171", en:"detrimental", ru:"вредный, пагубный", ex:"Stress can be detrimental to your health." },
    { id:"v4-B2-172", en:"beneficial", ru:"благотворный, полезный", ex:"Regular exercise is highly beneficial." },
    { id:"v4-B2-173", en:"controversial", ru:"спорный", ex:"The decision proved deeply controversial." },
    { id:"v4-B2-174", en:"viable", ru:"жизнеспособный, осуществимый", ex:"Solar power is now a viable alternative." },
    { id:"v4-B2-175", en:"counterproductive", ru:"контрпродуктивный", ex:"Punishing mistakes can be counterproductive." },
    { id:"v4-B2-176", en:"inevitable", ru:"неизбежный", ex:"Some job losses seem inevitable." },
    { id:"v4-B2-177", en:"unprecedented", ru:"беспрецедентный", ex:"The crisis was unprecedented in scale." },
    { id:"v4-B2-178", en:"questionable", ru:"сомнительный", ex:"The data came from a questionable source." },
    { id:"v4-B2-179", en:"profound", ru:"глубокий, серьёзный", ex:"The book had a profound effect on me." },
    { id:"v4-B2-180", en:"negligible", ru:"незначительный, пренебрежимый", ex:"The difference in cost was negligible." },

    // дополнительные: мнения и абстрактные
    { id:"v4-B2-181", en:"to weigh up the pros and cons", ru:"взвесить за и против", ex:"Let's weigh up the pros and cons before deciding." },
    { id:"v4-B2-182", en:"a sweeping statement", ru:"огульное обобщение", ex:"That's a sweeping statement with no evidence." },
    { id:"v4-B2-183", en:"to read between the lines", ru:"читать между строк", ex:"You have to read between the lines of his email." },
    { id:"v4-B2-184", en:"a double-edged sword", ru:"палка о двух концах", ex:"Fame is a double-edged sword." },
    { id:"v4-B2-185", en:"to err on the side of caution", ru:"перестраховаться", ex:"We decided to err on the side of caution." },
    { id:"v4-B2-186", en:"a grey area", ru:"серая зона, неопределённость", ex:"The legality of this is a grey area." },
    { id:"v4-B2-187", en:"to take with a pinch of salt", ru:"относиться скептически", ex:"Take online reviews with a pinch of salt." },
    { id:"v4-B2-188", en:"the bigger picture", ru:"картина в целом", ex:"Try not to lose sight of the bigger picture." },
    { id:"v4-B2-189", en:"to jump to conclusions", ru:"делать поспешные выводы", ex:"Don't jump to conclusions before you hear the facts." },
    { id:"v4-B2-190", en:"a turning point", ru:"переломный момент", ex:"The election was a turning point for the country." },

    // дополнительные: общество, бизнес, психология
    { id:"v4-B2-191", en:"to bridge the gap", ru:"преодолеть разрыв", ex:"The programme aims to bridge the gap between rich and poor." },
    { id:"v4-B2-192", en:"a vicious cycle", ru:"порочный круг", ex:"Debt and poverty form a vicious cycle." },
    { id:"v4-B2-193", en:"to keep up with", ru:"успевать за, поспевать", ex:"It's hard to keep up with the pace of change." },
    { id:"v4-B2-194", en:"work-life balance", ru:"баланс работы и жизни", ex:"Remote work improved her work-life balance." },
    { id:"v4-B2-195", en:"to burn out", ru:"перегореть, выгореть", ex:"Many doctors burn out from long shifts." },
    { id:"v4-B2-196", en:"peer pressure", ru:"давление окружения", ex:"Teenagers often give in to peer pressure." },
    { id:"v4-B2-197", en:"to live up to expectations", ru:"оправдать ожидания", ex:"The sequel failed to live up to expectations." },
    { id:"v4-B2-198", en:"a wake-up call", ru:"тревожный сигнал", ex:"The accident was a wake-up call for the whole industry." },
    { id:"v4-B2-199", en:"to take a toll on", ru:"негативно сказываться на", ex:"The long hours took a toll on his health." },
    { id:"v4-B2-200", en:"to gain traction", ru:"набирать популярность", ex:"The idea is finally gaining traction among investors." }
  ]);
})();
