(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("vocab","C2",[
    { id:"v4-C2-01", en:"ineffable", ru:"невыразимый, неописуемый", ex:"She felt an ineffable joy that words could not capture." },
    { id:"v4-C2-02", en:"perspicacious", ru:"проницательный", ex:"His perspicacious analysis exposed flaws others had missed." },
    { id:"v4-C2-03", en:"obfuscate", ru:"запутывать, затемнять смысл", ex:"The report seemed designed to obfuscate rather than clarify." },
    { id:"v4-C2-04", en:"ephemeral", ru:"эфемерный, мимолётный", ex:"Fame can be ephemeral, vanishing as quickly as it came." },
    { id:"v4-C2-05", en:"sycophant", ru:"подхалим, льстец", ex:"The king was surrounded by sycophants who never told the truth." },
    { id:"v4-C2-06", en:"recalcitrant", ru:"непокорный, упрямый", ex:"The recalcitrant student refused every reasonable request." },
    { id:"v4-C2-07", en:"pellucid", ru:"кристально ясный, прозрачный", ex:"Her pellucid prose made complex ideas effortless to grasp." },
    { id:"v4-C2-08", en:"vituperative", ru:"бранный, поносящий", ex:"His vituperative review left no one in doubt of his contempt." },
    { id:"v4-C2-09", en:"sanguine", ru:"оптимистичный, жизнерадостный", ex:"Despite the setbacks, she remained sanguine about the outcome." },
    { id:"v4-C2-10", en:"querulous", ru:"ворчливый, жалующийся", ex:"The querulous old man complained about everything and everyone." },
    { id:"v4-C2-11", en:"obstreperous", ru:"шумный, буйный", ex:"The obstreperous crowd drowned out the speaker entirely." },
    { id:"v4-C2-12", en:"laconic", ru:"немногословный, лаконичный", ex:"His laconic reply conveyed more than a lengthy speech could." },
    { id:"v4-C2-13", en:"mellifluous", ru:"сладкозвучный, медоточивый", ex:"The singer's mellifluous voice enchanted the entire audience." },
    { id:"v4-C2-14", en:"truculent", ru:"воинственный, агрессивный", ex:"He grew truculent whenever his decisions were questioned." },
    { id:"v4-C2-15", en:"perfunctory", ru:"поверхностный, небрежный", ex:"She gave a perfunctory nod and walked past without stopping." },
    { id:"v4-C2-16", en:"insouciant", ru:"беспечный, беззаботный", ex:"His insouciant shrug suggested he hardly cared about the risk." },
    { id:"v4-C2-17", en:"pernicious", ru:"пагубный, разрушительный", ex:"The pernicious rumour spread through the office within hours." },
    { id:"v4-C2-18", en:"limpid", ru:"прозрачный, ясный", ex:"They gazed into the limpid waters of the mountain lake." },
    { id:"v4-C2-19", en:"obdurate", ru:"непреклонный, упорствующий", ex:"The minister remained obdurate despite mounting public pressure." },
    { id:"v4-C2-20", en:"effulgent", ru:"сияющий, лучезарный", ex:"The effulgent dawn flooded the valley with golden light." },
    { id:"v4-C2-21", en:"taciturn", ru:"молчаливый, неразговорчивый", ex:"Her taciturn husband rarely spoke at the dinner parties." },
    { id:"v4-C2-22", en:"grandiloquent", ru:"высокопарный, напыщенный", ex:"His grandiloquent speech impressed no one in the room." },
    { id:"v4-C2-23", en:"abstruse", ru:"труднопостижимый, заумный", ex:"The lecture was so abstruse that few could follow the argument." },
    { id:"v4-C2-24", en:"ebullient", ru:"кипучий, восторженный", ex:"She returned from the trip ebullient with stories to tell." },
    { id:"v4-C2-25", en:"fastidious", ru:"привередливый, дотошный", ex:"He was fastidious about every comma in the manuscript." },
    { id:"v4-C2-26", en:"inveterate", ru:"закоренелый, заядлый", ex:"An inveterate gambler, he could never resist a wager." },
    { id:"v4-C2-27", en:"trenchant", ru:"острый, проницательный (о критике)", ex:"Her trenchant critique cut straight to the heart of the matter." },
    { id:"v4-C2-28", en:"diaphanous", ru:"полупрозрачный, воздушный", ex:"She wore a diaphanous gown that shimmered in the candlelight." },
    { id:"v4-C2-29", en:"obsequious", ru:"раболепный, угодливый", ex:"The obsequious waiter hovered around the wealthy guests." },
    { id:"v4-C2-30", en:"pulchritude", ru:"красота, миловидность", ex:"The painting was celebrated for the pulchritude of its subject." },
    { id:"v4-C2-31", en:"saturnine", ru:"мрачный, угрюмый", ex:"His saturnine expression betrayed a deep inner melancholy." },
    { id:"v4-C2-32", en:"contumacious", ru:"непокорный, своевольный", ex:"The contumacious witness defied the court's every order." },
    { id:"v4-C2-33", en:"luminous", ru:"светящийся, проникновенный", ex:"Her luminous intelligence illuminated every conversation." },
    { id:"v4-C2-34", en:"pusillanimous", ru:"малодушный, трусливый", ex:"His pusillanimous retreat dismayed his loyal followers." },
    { id:"v4-C2-35", en:"redoubtable", ru:"грозный, внушающий уважение", ex:"She was a redoubtable opponent in any legal debate." },
    { id:"v4-C2-36", en:"susurrus", ru:"шёпот, шелест", ex:"A gentle susurrus of leaves accompanied the evening walk." },
    { id:"v4-C2-37", en:"vicissitude", ru:"превратность, перемена судьбы", ex:"He endured the vicissitudes of fortune with quiet dignity." },
    { id:"v4-C2-38", en:"jejune", ru:"пресный, незрелый", ex:"The novel's jejune dialogue undermined its grand ambitions." },
    { id:"v4-C2-39", en:"propitious", ru:"благоприятный, сулящий успех", ex:"The propitious weather promised a flawless launch." },
    { id:"v4-C2-40", en:"recondite", ru:"малопонятный, сокровенный", ex:"He delighted in recondite trivia that baffled his guests." },
    { id:"v4-C2-41", en:"halcyon", ru:"безмятежный, счастливый (о времени)", ex:"They reminisced about the halcyon days of their youth." },
    { id:"v4-C2-42", en:"deleterious", ru:"вредный, пагубный", ex:"Prolonged stress can have a deleterious effect on health." },
    { id:"v4-C2-43", en:"meretricious", ru:"показной, мишурный", ex:"The decor was meretricious, all glitter and no substance." },
    { id:"v4-C2-44", en:"nugatory", ru:"ничтожный, пустячный", ex:"Their objections proved nugatory once the facts emerged." },
    { id:"v4-C2-45", en:"sanctimonious", ru:"ханжеский, лицемерно-благочестивый", ex:"His sanctimonious lectures grated on everyone around him." },
    { id:"v4-C2-46", en:"pellmell", ru:"беспорядочный, сумбурный", ex:"The guests rushed pell-mell toward the buffet table." },
    { id:"v4-C2-47", en:"crepuscular", ru:"сумеречный", ex:"In the crepuscular light, the ruins took on an eerie glow." },
    { id:"v4-C2-48", en:"munificent", ru:"щедрый, великодушный", ex:"The munificent donor funded the entire scholarship programme." },
    { id:"v4-C2-49", en:"verisimilitude", ru:"правдоподобие", ex:"The film's verisimilitude made every scene feel authentic." },
    { id:"v4-C2-50", en:"cantankerous", ru:"сварливый, вздорный", ex:"The cantankerous neighbour objected to every minor noise." },
    { id:"v4-C2-51", en:"sesquipedalian", ru:"многосложный, любящий длинные слова", ex:"His sesquipedalian style made the essay nearly unreadable." },
    { id:"v4-C2-52", en:"penumbra", ru:"полутень, неясная область", ex:"The scandal cast a penumbra of doubt over the whole board." },
    { id:"v4-C2-53", en:"farrago", ru:"мешанина, всякая всячина", ex:"The report was a farrago of half-truths and conjecture." },
    { id:"v4-C2-54", en:"perspicuous", ru:"вразумительный, доходчивый", ex:"Her perspicuous explanation left no room for confusion." },
    { id:"v4-C2-55", en:"adumbrate", ru:"намечать, предвещать", ex:"The opening chapter adumbrates the tragedy to come." },
    { id:"v4-C2-56", en:"animadversion", ru:"порицание, осуждение", ex:"His animadversions on the policy were widely reported." },
    { id:"v4-C2-57", en:"coruscating", ru:"сверкающий, блистательный", ex:"She delivered a coruscating attack on the proposal." },
    { id:"v4-C2-58", en:"desuetude", ru:"состояние неупотребления, забвения", ex:"The old law fell into desuetude long before its repeal." },
    { id:"v4-C2-59", en:"effervescent", ru:"искрящийся, оживлённый", ex:"Her effervescent personality lifted the whole gathering." },
    { id:"v4-C2-60", en:"fissiparous", ru:"раскольнический, склонный к расколу", ex:"The fissiparous party splintered into rival factions." },
    { id:"v4-C2-61", en:"gossamer", ru:"тонкий, паутинный", ex:"A gossamer veil of mist hung over the silent fields." },
    { id:"v4-C2-62", en:"hortatory", ru:"увещевательный, призывающий", ex:"The general's hortatory address roused the weary troops." },
    { id:"v4-C2-63", en:"importunate", ru:"назойливый, докучливый", ex:"The importunate salesman would not take no for an answer." },
    { id:"v4-C2-64", en:"jeremiad", ru:"скорбный плач, обличительная речь", ex:"His column read like a jeremiad against modern manners." },
    { id:"v4-C2-65", en:"kakistocracy", ru:"власть худших, правление негодных", ex:"Critics derided the regime as a corrupt kakistocracy." },
    { id:"v4-C2-66", en:"lugubrious", ru:"скорбный, унылый", ex:"He spoke in a lugubrious tone about the firm's decline." },
    { id:"v4-C2-67", en:"maladroit", ru:"неловкий, бестактный", ex:"His maladroit apology only deepened the offence." },
    { id:"v4-C2-68", en:"nonpareil", ru:"бесподобный, непревзойдённый", ex:"She was regarded as a nonpareil among contemporary pianists." },
    { id:"v4-C2-69", en:"opprobrium", ru:"позор, поругание", ex:"The decision brought public opprobrium upon the company." },
    { id:"v4-C2-70", en:"parsimonious", ru:"скупой, прижимистый", ex:"The parsimonious manager grudged every penny of expenses." },
    { id:"v4-C2-71", en:"quotidian", ru:"повседневный, будничный", ex:"He found poetry in the quotidian routines of city life." },
    { id:"v4-C2-72", en:"rebarbative", ru:"отталкивающий, неприятный", ex:"His rebarbative manner alienated potential allies at once." },
    { id:"v4-C2-73", en:"scintilla", ru:"крупица, малейший след", ex:"There was not a scintilla of evidence against the accused." },
    { id:"v4-C2-74", en:"tenebrous", ru:"тёмный, мрачный", ex:"They descended into the tenebrous depths of the cavern." },
    { id:"v4-C2-75", en:"ubiquitous", ru:"вездесущий, повсеместный", ex:"Smartphones have become ubiquitous in daily life." },
    { id:"v4-C2-76", en:"vainglorious", ru:"тщеславный, хвастливый", ex:"His vainglorious boasts soon wearied his companions." },
    { id:"v4-C2-77", en:"winsome", ru:"обаятельный, привлекательный", ex:"Her winsome smile disarmed even the sternest critics." },
    { id:"v4-C2-78", en:"xenial", ru:"гостеприимный (к чужестранцам)", ex:"The xenial customs of the village welcomed every traveller." },
    { id:"v4-C2-79", en:"zephyr", ru:"лёгкий ветерок, зефир", ex:"A warm zephyr carried the scent of blossom across the lawn." },
    { id:"v4-C2-80", en:"acerbic", ru:"едкий, язвительный", ex:"Her acerbic wit could deflate the most pompous of guests." },
    { id:"v4-C2-81", en:"bombastic", ru:"напыщенный, высокопарный", ex:"His bombastic rhetoric masked a poverty of real ideas." },
    { id:"v4-C2-82", en:"cogitate", ru:"размышлять, обдумывать", ex:"She cogitated for hours over the wording of the letter." },
    { id:"v4-C2-83", en:"diffident", ru:"робкий, неуверенный в себе", ex:"Too diffident to speak up, he let the chance slip away." },
    { id:"v4-C2-84", en:"epicurean", ru:"гедонистический, любитель утончённых наслаждений", ex:"He had epicurean tastes and a cellar to match them." },
    { id:"v4-C2-85", en:"fulminate", ru:"метать громы и молнии, гневно осуждать", ex:"The editor fulminated against the new censorship laws." },
    { id:"v4-C2-86", en:"garrulous", ru:"болтливый, словоохотливый", ex:"The garrulous guide never paused for breath all afternoon." },
    { id:"v4-C2-87", en:"hagiography", ru:"житие, славословящая биография", ex:"The biography read more like hagiography than honest history." },
    { id:"v4-C2-88", en:"iconoclast", ru:"иконоборец, ниспровергатель устоев", ex:"As an iconoclast, she delighted in challenging every dogma." },
    { id:"v4-C2-89", en:"jocund", ru:"весёлый, жизнерадостный", ex:"A jocund mood prevailed throughout the harvest festival." },
    { id:"v4-C2-90", en:"kismet", ru:"судьба, рок", ex:"Their meeting felt less like chance and more like kismet." },
    { id:"v4-C2-91", en:"lachrymose", ru:"слезливый, плаксивый", ex:"The lachrymose finale left half the audience in tears." },
    { id:"v4-C2-92", en:"mendacious", ru:"лживый, ложный", ex:"His mendacious account quickly unravelled under scrutiny." },
    { id:"v4-C2-93", en:"nebulous", ru:"туманный, расплывчатый", ex:"Their plans remained nebulous well into the spring." },
    { id:"v4-C2-94", en:"obfuscation", ru:"затемнение смысла, напускание тумана", ex:"The lawyer's obfuscation only fuelled the jury's suspicion." },
    { id:"v4-C2-95", en:"palliate", ru:"смягчать, облегчать (не устраняя)", ex:"The measures palliate the symptoms but ignore the cause." },
    { id:"v4-C2-96", en:"quixotic", ru:"донкихотский, непрактично-идеалистичный", ex:"His quixotic scheme to reform the system was doomed." },
    { id:"v4-C2-97", en:"raconteur", ru:"искусный рассказчик", ex:"As a raconteur, he could hold a table spellbound for hours." },
    { id:"v4-C2-98", en:"soporific", ru:"усыпляющий, снотворный", ex:"The lecture's soporific drone lulled half the hall to sleep." },
    { id:"v4-C2-99", en:"tendentious", ru:"тенденциозный, предвзятый", ex:"The article was too tendentious to be taken as reportage." },
    { id:"v4-C2-100", en:"unctuous", ru:"елейный, приторно-любезный", ex:"His unctuous flattery made everyone vaguely uncomfortable." },
    { id:"v4-C2-101", en:"vociferous", ru:"крикливый, громогласный", ex:"The vociferous protesters demanded an immediate inquiry." },
    { id:"v4-C2-102", en:"wraith", ru:"призрак, привидение", ex:"A wraith of fog drifted between the gravestones at dusk." },
    { id:"v4-C2-103", en:"yare", ru:"проворный, легко управляемый", ex:"The little yacht proved remarkably yare in the squall." },
    { id:"v4-C2-104", en:"zealotry", ru:"фанатизм, ревностное усердие", ex:"His political zealotry blinded him to every counterargument." },
    { id:"v4-C2-105", en:"apocryphal", ru:"апокрифический, сомнительной подлинности", ex:"The anecdote is charming but almost certainly apocryphal." },
    { id:"v4-C2-106", en:"bowdlerize", ru:"выхолащивать, причёсывать (текст)", ex:"Editors bowdlerized the play to suit a timid audience." },
    { id:"v4-C2-107", en:"cacophony", ru:"какофония, разноголосица", ex:"A cacophony of horns rose from the gridlocked street." },
    { id:"v4-C2-108", en:"dilatory", ru:"медлительный, тянущий время", ex:"His dilatory tactics delayed the verdict for months." },
    { id:"v4-C2-109", en:"esoteric", ru:"эзотерический, для посвящённых", ex:"The journal published esoteric papers few could decipher." },
    { id:"v4-C2-110", en:"feckless", ru:"никчёмный, безответственный", ex:"His feckless brother squandered the family's last savings." },
    { id:"v4-C2-111", en:"gravamen", ru:"суть обвинения, главный пункт жалобы", ex:"The gravamen of her complaint was sheer negligence." },
    { id:"v4-C2-112", en:"histrionic", ru:"театральный, наигранный", ex:"His histrionic outburst convinced no one of his sincerity." },
    { id:"v4-C2-113", en:"impecunious", ru:"безденежный, нуждающийся", ex:"The impecunious poet lived on the kindness of friends." },
    { id:"v4-C2-114", en:"juxtapose", ru:"сопоставлять, помещать рядом", ex:"The exhibition juxtaposes ancient relics with modern art." },
    { id:"v4-C2-115", en:"kowtow", ru:"раболепствовать, угодничать", ex:"He refused to kowtow to the demands of his superiors." },
    { id:"v4-C2-116", en:"limn", ru:"изображать, обрисовывать", ex:"The novel limns the decline of a once-great dynasty." },
    { id:"v4-C2-117", en:"mawkish", ru:"слащавый, приторно-сентиментальный", ex:"The card's mawkish verse made her wince rather than smile." },
    { id:"v4-C2-118", en:"nadir", ru:"надир, низшая точка", ex:"The defeat marked the nadir of his political career." },
    { id:"v4-C2-119", en:"obviate", ru:"устранять, делать ненужным", ex:"The new system obviates the need for manual checks." },
    { id:"v4-C2-120", en:"pellucidity", ru:"кристальная ясность", ex:"The essay was admired for its rare pellucidity of thought." },
    { id:"v4-C2-121", en:"quagmire", ru:"трясина, безвыходное положение", ex:"The negotiations sank into a legal quagmire for years." },
    { id:"v4-C2-122", en:"ribald", ru:"непристойный, скабрёзный", ex:"His ribald jokes were unsuited to the solemn occasion." },
    { id:"v4-C2-123", en:"sagacious", ru:"мудрый, прозорливый", ex:"Her sagacious counsel steered the firm through the crisis." },
    { id:"v4-C2-124", en:"turpitude", ru:"низость, моральное падение", ex:"He was dismissed for an act of flagrant moral turpitude." },
    { id:"v4-C2-125", en:"umbrage", ru:"обида, негодование", ex:"She took umbrage at the implication of dishonesty." },
    { id:"v4-C2-126", en:"venal", ru:"продажный, корыстный", ex:"The venal official sold permits to the highest bidder." },
    { id:"v4-C2-127", en:"welter", ru:"мешанина, сумятица", ex:"He lost himself in a welter of conflicting reports." },
    { id:"v4-C2-128", en:"yoke", ru:"иго, бремя (устар.)", ex:"They longed to throw off the yoke of foreign rule." },
    { id:"v4-C2-129", en:"zenith", ru:"зенит, апогей", ex:"At the zenith of her career she walked away from it all." },
    { id:"v4-C2-130", en:"abnegation", ru:"самоотречение, отказ от благ", ex:"His life of abnegation inspired devotion in his followers." },
    { id:"v4-C2-131", en:"blandishment", ru:"лесть, обольщение", ex:"No blandishment could persuade her to change her vote." },
    { id:"v4-C2-132", en:"calumny", ru:"клевета, наговор", ex:"He sued the paper for the calumny it had printed." },
    { id:"v4-C2-133", en:"dolorous", ru:"печальный, скорбный", ex:"A dolorous bell tolled across the empty square." },
    { id:"v4-C2-134", en:"enervate", ru:"истощать, лишать сил", ex:"The relentless heat enervated even the hardiest workers." },
    { id:"v4-C2-135", en:"fecund", ru:"плодородный, плодовитый", ex:"His fecund imagination produced a new idea every day." },
    { id:"v4-C2-136", en:"gainsay", ru:"отрицать, оспаривать", ex:"No one could gainsay the brilliance of her argument." },
    { id:"v4-C2-137", en:"hebetude", ru:"тупость, вялость ума", ex:"A dull hebetude settled over the overworked clerks." },
    { id:"v4-C2-138", en:"inchoate", ru:"зачаточный, едва начавшийся", ex:"His ambitions were still inchoate and ill-defined." },
    { id:"v4-C2-139", en:"jactitation", ru:"бахвальство, хвастовство", ex:"His endless jactitation wore on his colleagues' patience." },
    { id:"v4-C2-140", en:"knell", ru:"похоронный звон, дурное предзнаменование", ex:"The verdict sounded the knell of his political hopes." },
    { id:"v4-C2-141", en:"largesse", ru:"щедрость, щедрые дары", ex:"The patron's largesse funded a generation of scholars." },
    { id:"v4-C2-142", en:"minatory", ru:"угрожающий, грозный", ex:"He fixed her with a minatory glare across the table." },
    { id:"v4-C2-143", en:"nescience", ru:"невежество, незнание", ex:"Their nescience of the law proved a costly mistake." },
    { id:"v4-C2-144", en:"obloquy", ru:"поношение, бесчестье", ex:"He bore the public obloquy with surprising composure." },
    { id:"v4-C2-145", en:"peregrination", ru:"странствие, скитание", ex:"His peregrinations took him to the remotest corners of Asia." },
    { id:"v4-C2-146", en:"quiescent", ru:"бездействующий, покоящийся", ex:"The volcano had lain quiescent for over a century." },
    { id:"v4-C2-147", en:"rebus", ru:"ребус, загадка в картинках", ex:"The manuscript's margins were filled with cryptic rebuses." },
    { id:"v4-C2-148", en:"supercilious", ru:"высокомерный, надменный", ex:"The supercilious clerk barely deigned to look up." },
    { id:"v4-C2-149", en:"timorous", ru:"боязливый, робкий", ex:"A timorous knock at the door interrupted the meeting." },
    { id:"v4-C2-150", en:"untrammelled", ru:"ничем не стеснённый, свободный", ex:"She enjoyed an untrammelled freedom to paint as she wished." },
    { id:"v4-C2-151", en:"vatic", ru:"пророческий, вещий", ex:"His vatic warnings about the crash went unheeded." },
    { id:"v4-C2-152", en:"wanton", ru:"безудержный, беспричинный", ex:"The wanton destruction of the forest appalled the village." },
    { id:"v4-C2-153", en:"zugzwang", ru:"цугцванг, безвыходное положение", ex:"Politically he was in zugzwang: every move worsened his plight." },
    { id:"v4-C2-154", en:"acumen", ru:"проницательность, сметливость", ex:"Her business acumen turned the failing shop into an empire." },
    { id:"v4-C2-155", en:"bellicose", ru:"воинственный, агрессивный", ex:"The bellicose rhetoric alarmed the neighbouring states." },
    { id:"v4-C2-156", en:"churlish", ru:"грубый, неучтивый", ex:"It would be churlish to refuse such a generous offer." },
    { id:"v4-C2-157", en:"desultory", ru:"бессистемный, отрывочный", ex:"They made desultory conversation while waiting for the train." },
    { id:"v4-C2-158", en:"execrable", ru:"отвратительный, омерзительный", ex:"The food was execrable and the service no better." },
    { id:"v4-C2-159", en:"feral", ru:"одичавший, дикий", ex:"A feral cunning gleamed in the fugitive's eyes." },
    { id:"v4-C2-160", en:"gauche", ru:"неуклюжий, бестактный", ex:"His gauche remark silenced the entire dinner table." },
    { id:"v4-C2-161", en:"hubris", ru:"гордыня, высокомерие", ex:"His downfall was the inevitable price of his hubris." },
    { id:"v4-C2-162", en:"insidious", ru:"коварный, исподволь действующий", ex:"The disease is insidious, advancing without early signs." },
    { id:"v4-C2-163", en:"jingoism", ru:"ура-патриотизм, шовинизм", ex:"The campaign degenerated into crude jingoism." },
    { id:"v4-C2-164", en:"kerfuffle", ru:"суматоха, переполох", ex:"There was quite a kerfuffle over the seating arrangements." },
    { id:"v4-C2-165", en:"limpidity", ru:"прозрачность, ясность", ex:"The composer was praised for the limpidity of his melodies." },
    { id:"v4-C2-166", en:"maelstrom", ru:"водоворот, хаос", ex:"He was swept into a maelstrom of accusation and intrigue." },
    { id:"v4-C2-167", en:"noisome", ru:"зловонный, отвратительный", ex:"A noisome odour rose from the neglected canal." },
    { id:"v4-C2-168", en:"oleaginous", ru:"маслянистый, елейный", ex:"His oleaginous compliments fooled nobody at the firm." },
    { id:"v4-C2-169", en:"plangent", ru:"заунывный, гулко-звучащий", ex:"The plangent cry of the gulls echoed over the harbour." },
    { id:"v4-C2-170", en:"quondam", ru:"бывший, прежний", ex:"He bumped into a quondam colleague at the conference." },
    { id:"v4-C2-171", en:"recrudescence", ru:"возобновление, новая вспышка", ex:"The treaty failed to prevent a recrudescence of violence." },
    { id:"v4-C2-172", en:"sybaritic", ru:"сибаритский, склонный к роскоши", ex:"He led a sybaritic life of silk sheets and rare wines." },
    { id:"v4-C2-173", en:"tergiversation", ru:"увиливание, отступничество", ex:"His constant tergiversation eroded all public trust." },
    { id:"v4-C2-174", en:"usurious", ru:"ростовщический, грабительский (о процентах)", ex:"They borrowed at usurious rates they could never repay." },
    { id:"v4-C2-175", en:"verdant", ru:"зелёный, цветущий", ex:"The verdant hills rolled away to a distant blue horizon." },
    { id:"v4-C2-176", en:"wizened", ru:"высохший, сморщенный", ex:"A wizened old gardener tended the ancient roses." },
    { id:"v4-C2-177", en:"yclept", ru:"именуемый, названный (арх.)", ex:"A knight yclept Gawain rode forth at the king's command." },
    { id:"v4-C2-178", en:"zaftig", ru:"полная и привлекательная (о фигуре)", ex:"The portrait celebrated her warm, zaftig beauty." },
    { id:"v4-C2-179", en:"approbation", ru:"одобрение, похвала", ex:"The reform won the approbation of every faction." },
    { id:"v4-C2-180", en:"bucolic", ru:"пасторальный, сельский", ex:"They retired to a bucolic cottage far from the city." },
    { id:"v4-C2-181", en:"cynosure", ru:"центр внимания, путеводная звезда", ex:"In her gown she became the cynosure of the whole ballroom." },
    { id:"v4-C2-182", en:"denouement", ru:"развязка, исход", ex:"The play's denouement caught even the critics off guard." },
    { id:"v4-C2-183", en:"effrontery", ru:"наглость, дерзость", ex:"He had the effrontery to demand a refund for the gift." },
    { id:"v4-C2-184", en:"fulsome", ru:"чрезмерный, неискренне-льстивый", ex:"His fulsome praise sounded more like mockery than tribute." },
    { id:"v4-C2-185", en:"grandiose", ru:"грандиозный, претенциозный", ex:"His grandiose plans rarely survived contact with reality." },
    { id:"v4-C2-186", en:"hidebound", ru:"закостенелый, узколобый", ex:"The hidebound committee rejected every new idea outright." },
    { id:"v4-C2-187", en:"imbroglio", ru:"запутанное положение, недоразумение", ex:"The merger collapsed amid a financial imbroglio." },
    { id:"v4-C2-188", en:"jocular", ru:"шутливый, забавный", ex:"He kept a jocular tone even in the tensest meetings." },
    { id:"v4-C2-189", en:"lassitude", ru:"усталость, апатия", ex:"A profound lassitude settled over the team after the loss." },
    { id:"v4-C2-190", en:"misprision", ru:"недонесение, пренебрежение долгом", ex:"He was charged with misprision of a serious crime." },
    { id:"v4-C2-191", en:"nonplussed", ru:"озадаченный, сбитый с толку", ex:"She was utterly nonplussed by his sudden change of heart." },
    { id:"v4-C2-192", en:"obstinacy", ru:"упрямство, упорство", ex:"His sheer obstinacy doomed the entire negotiation." },
    { id:"v4-C2-193", en:"panegyric", ru:"панегирик, хвалебная речь", ex:"The eulogy turned into a lavish panegyric to her life." },
    { id:"v4-C2-194", en:"quintessence", ru:"квинтэссенция, суть", ex:"The design was the quintessence of understated elegance." },
    { id:"v4-C2-195", en:"reticent", ru:"сдержанный, неразговорчивый", ex:"He was reticent about the details of his past." },
    { id:"v4-C2-196", en:"solipsism", ru:"солипсизм, крайний эгоцентризм", ex:"His solipsism left no room for anyone else's feelings." },
    { id:"v4-C2-197", en:"trammel", ru:"путы, помеха; стеснять", ex:"Bureaucratic trammels stifled every attempt at reform." },
    { id:"v4-C2-198", en:"uxorious", ru:"чрезмерно привязанный к жене", ex:"The uxorious husband deferred to his wife in everything." },
    { id:"v4-C2-199", en:"vacillate", ru:"колебаться, проявлять нерешительность", ex:"He vacillated for weeks before finally accepting the post." },
    { id:"v4-C2-200", en:"weltschmerz", ru:"мировая скорбь, томление духа", ex:"A vague weltschmerz colored all his later poetry." }
  ]);
})();