(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("vocab","B1",[
    // характер/внешность
    { id:"v4-B1-01", en:"reliable", ru:"надёжный", ex:"She is a reliable friend who always keeps her promises." },
    { id:"v4-B1-02", en:"stubborn", ru:"упрямый", ex:"He is too stubborn to admit that he was wrong." },
    { id:"v4-B1-03", en:"easy-going", ru:"лёгкий в общении, беспечный", ex:"My boss is easy-going and rarely gets angry." },
    { id:"v4-B1-04", en:"ambitious", ru:"амбициозный", ex:"She is ambitious and wants to run her own company one day." },
    { id:"v4-B1-05", en:"good-looking", ru:"привлекательный", ex:"He is a good-looking man in his thirties." },
    { id:"v4-B1-06", en:"self-confident", ru:"уверенный в себе", ex:"You need to be self-confident during a job interview." },
    { id:"v4-B1-07", en:"sense of humour", ru:"чувство юмора", ex:"I love people with a great sense of humour." },
    { id:"v4-B1-08", en:"sensible", ru:"благоразумный, здравомыслящий", ex:"It was a sensible decision to save some money." },
    { id:"v4-B1-09", en:"generous", ru:"щедрый", ex:"He is generous and often pays for everyone." },
    { id:"v4-B1-10", en:"well-built", ru:"крепкого телосложения", ex:"The athlete was tall and well-built." },

    // отношения/общение
    { id:"v4-B1-11", en:"get on well with", ru:"хорошо ладить с", ex:"I get on well with most of my colleagues." },
    { id:"v4-B1-12", en:"fall out with", ru:"поссориться с", ex:"They fell out with each other over money." },
    { id:"v4-B1-13", en:"acquaintance", ru:"знакомый", ex:"He is just an acquaintance, not a close friend." },
    { id:"v4-B1-14", en:"keep in touch", ru:"поддерживать связь", ex:"We promised to keep in touch after graduation." },
    { id:"v4-B1-15", en:"make up", ru:"помириться", ex:"After the argument, they quickly made up." },
    { id:"v4-B1-16", en:"have a lot in common", ru:"иметь много общего", ex:"We have a lot in common and never run out of topics." },
    { id:"v4-B1-17", en:"trust", ru:"доверять; доверие", ex:"It takes years to build trust in a relationship." },
    { id:"v4-B1-18", en:"break up", ru:"расстаться", ex:"They decided to break up after five years together." },
    { id:"v4-B1-19", en:"get to know", ru:"узнать получше (человека)", ex:"It took me a while to get to know my new neighbours." },
    { id:"v4-B1-20", en:"close-knit", ru:"сплочённый (о семье/группе)", ex:"They come from a close-knit family." },

    // эмоции
    { id:"v4-B1-21", en:"anxious", ru:"тревожный, обеспокоенный", ex:"She felt anxious before the exam results." },
    { id:"v4-B1-22", en:"thrilled", ru:"в восторге", ex:"I was thrilled to hear about your promotion." },
    { id:"v4-B1-23", en:"frustrated", ru:"раздражённый, разочарованный", ex:"He got frustrated when the computer kept crashing." },
    { id:"v4-B1-24", en:"relieved", ru:"испытывающий облегчение", ex:"I was relieved when the flight finally landed safely." },
    { id:"v4-B1-25", en:"embarrassed", ru:"смущённый", ex:"She felt embarrassed after forgetting his name." },
    { id:"v4-B1-26", en:"overwhelmed", ru:"перегруженный, подавленный", ex:"I feel overwhelmed by all this work." },
    { id:"v4-B1-27", en:"jealous", ru:"ревнивый, завистливый", ex:"He gets jealous when she talks to other men." },
    { id:"v4-B1-28", en:"grateful", ru:"благодарный", ex:"I am grateful for all your help." },
    { id:"v4-B1-29", en:"upset", ru:"расстроенный", ex:"Don't be upset about such a small mistake." },
    { id:"v4-B1-30", en:"cheer up", ru:"подбодрить(ся)", ex:"I tried to cheer her up with a funny story." },

    // работа/карьера
    { id:"v4-B1-31", en:"apply for", ru:"подавать заявку на", ex:"I want to apply for a marketing position." },
    { id:"v4-B1-32", en:"promotion", ru:"повышение", ex:"She got a promotion after two years in the company." },
    { id:"v4-B1-33", en:"deadline", ru:"крайний срок", ex:"We have to meet the deadline by Friday." },
    { id:"v4-B1-34", en:"colleague", ru:"коллега", ex:"My colleagues are friendly and supportive." },
    { id:"v4-B1-35", en:"overtime", ru:"сверхурочная работа", ex:"He works overtime almost every week." },
    { id:"v4-B1-36", en:"resign", ru:"уволиться, подать в отставку", ex:"She decided to resign and start her own business." },
    { id:"v4-B1-37", en:"workload", ru:"нагрузка, объём работы", ex:"My workload has increased since the new project started." },
    { id:"v4-B1-38", en:"shift", ru:"смена (рабочая)", ex:"He works the night shift at the hospital." },
    { id:"v4-B1-39", en:"redundant", ru:"сокращённый (уволенный)", ex:"Fifty workers were made redundant last month." },
    { id:"v4-B1-40", en:"self-employed", ru:"работающий на себя", ex:"She has been self-employed for three years." },

    // деньги/покупки
    { id:"v4-B1-41", en:"afford", ru:"позволить себе", ex:"We can't afford a new car right now." },
    { id:"v4-B1-42", en:"bargain", ru:"выгодная покупка", ex:"This jacket was a real bargain at half price." },
    { id:"v4-B1-43", en:"refund", ru:"возврат денег", ex:"They gave me a full refund for the broken item." },
    { id:"v4-B1-44", en:"on a budget", ru:"с ограниченным бюджетом", ex:"We're travelling on a tight budget this summer." },
    { id:"v4-B1-45", en:"discount", ru:"скидка", ex:"Students get a discount on train tickets." },
    { id:"v4-B1-46", en:"in debt", ru:"в долгах", ex:"Many young people are in debt after university." },
    { id:"v4-B1-47", en:"save up", ru:"копить (на что-то)", ex:"I'm saving up for a trip to Japan." },
    { id:"v4-B1-48", en:"receipt", ru:"чек, квитанция", ex:"Keep the receipt in case you want to return it." },
    { id:"v4-B1-49", en:"expense", ru:"расход", ex:"Rent is my biggest monthly expense." },
    { id:"v4-B1-50", en:"worth it", ru:"стоит того", ex:"The phone was expensive, but it was worth it." },

    // путешествия/отдых
    { id:"v4-B1-51", en:"sightseeing", ru:"осмотр достопримечательностей", ex:"We spent the whole day sightseeing in Rome." },
    { id:"v4-B1-52", en:"book in advance", ru:"бронировать заранее", ex:"It's cheaper if you book the flight in advance." },
    { id:"v4-B1-53", en:"luggage", ru:"багаж", ex:"My luggage got lost at the airport." },
    { id:"v4-B1-54", en:"check in", ru:"регистрироваться (в отеле/аэропорту)", ex:"We need to check in two hours before departure." },
    { id:"v4-B1-55", en:"destination", ru:"место назначения", ex:"Bali is a popular holiday destination." },
    { id:"v4-B1-56", en:"get away", ru:"вырваться, уехать отдохнуть", ex:"We really need to get away for the weekend." },
    { id:"v4-B1-57", en:"jet lag", ru:"смена часовых поясов (усталость)", ex:"I had terrible jet lag after the long flight." },
    { id:"v4-B1-58", en:"package holiday", ru:"путёвка (всё включено)", ex:"They booked a package holiday to Spain." },
    { id:"v4-B1-59", en:"scenery", ru:"пейзаж, виды", ex:"The mountain scenery was absolutely breathtaking." },
    { id:"v4-B1-60", en:"set off", ru:"отправиться в путь", ex:"We set off early to avoid the traffic." },

    // технологии/интернет
    { id:"v4-B1-61", en:"download", ru:"скачивать", ex:"You can download the app for free." },
    { id:"v4-B1-62", en:"log in", ru:"входить в систему", ex:"I can't log in to my account." },
    { id:"v4-B1-63", en:"upload", ru:"загружать (на сервер)", ex:"She uploaded the photos to the cloud." },
    { id:"v4-B1-64", en:"device", ru:"устройство", ex:"You can use this app on any mobile device." },
    { id:"v4-B1-65", en:"password", ru:"пароль", ex:"You should choose a strong password." },
    { id:"v4-B1-66", en:"social media", ru:"социальные сети", ex:"He spends too much time on social media." },
    { id:"v4-B1-67", en:"update", ru:"обновление; обновлять", ex:"The software needs an update to fix the bug." },
    { id:"v4-B1-68", en:"crash", ru:"зависать, ломаться (о системе)", ex:"My laptop crashed and I lost the file." },
    { id:"v4-B1-69", en:"browse", ru:"просматривать (сайты)", ex:"I like to browse the internet in the evening." },
    { id:"v4-B1-70", en:"back up", ru:"делать резервную копию", ex:"Remember to back up your files regularly." },

    // здоровье/спорт
    { id:"v4-B1-71", en:"work out", ru:"тренироваться", ex:"I work out at the gym three times a week." },
    { id:"v4-B1-72", en:"injury", ru:"травма", ex:"He missed the match because of a knee injury." },
    { id:"v4-B1-73", en:"get over", ru:"оправиться (от болезни)", ex:"It took her a week to get over the flu." },
    { id:"v4-B1-74", en:"prescription", ru:"рецепт (на лекарство)", ex:"The doctor gave me a prescription for antibiotics." },
    { id:"v4-B1-75", en:"keep fit", ru:"поддерживать форму", ex:"Cycling is a good way to keep fit." },
    { id:"v4-B1-76", en:"sprain", ru:"растяжение; растянуть", ex:"She sprained her ankle while running." },
    { id:"v4-B1-77", en:"balanced diet", ru:"сбалансированное питание", ex:"A balanced diet is important for good health." },
    { id:"v4-B1-78", en:"exhausted", ru:"измотанный", ex:"I was exhausted after the marathon." },
    { id:"v4-B1-79", en:"recover", ru:"восстанавливаться, выздоравливать", ex:"He is recovering well after the operation." },
    { id:"v4-B1-80", en:"warm up", ru:"разминаться", ex:"Always warm up before you exercise." },

    // окружающая среда
    { id:"v4-B1-81", en:"pollution", ru:"загрязнение", ex:"Air pollution is a serious problem in big cities." },
    { id:"v4-B1-82", en:"recycle", ru:"перерабатывать (вторсырьё)", ex:"We recycle paper, glass and plastic at home." },
    { id:"v4-B1-83", en:"climate change", ru:"изменение климата", ex:"Climate change affects the whole planet." },
    { id:"v4-B1-84", en:"waste", ru:"отходы; тратить впустую", ex:"Try not to waste water during the summer." },
    { id:"v4-B1-85", en:"renewable energy", ru:"возобновляемая энергия", ex:"Solar power is a form of renewable energy." },
    { id:"v4-B1-86", en:"endangered", ru:"под угрозой исчезновения", ex:"Pandas are an endangered species." },
    { id:"v4-B1-87", en:"environmentally friendly", ru:"экологичный", ex:"This packaging is environmentally friendly." },
    { id:"v4-B1-88", en:"greenhouse gas", ru:"парниковый газ", ex:"Cars produce a lot of greenhouse gases." },
    { id:"v4-B1-89", en:"cut down on", ru:"сокращать (потребление)", ex:"We should cut down on single-use plastic." },
    { id:"v4-B1-90", en:"natural resources", ru:"природные ресурсы", ex:"We must protect our natural resources." },

    // образование
    { id:"v4-B1-91", en:"degree", ru:"учёная степень, диплом", ex:"She has a degree in economics." },
    { id:"v4-B1-92", en:"take notes", ru:"делать записи", ex:"I always take notes during lectures." },
    { id:"v4-B1-93", en:"revise", ru:"повторять (материал к экзамену)", ex:"I need to revise for my history exam." },
    { id:"v4-B1-94", en:"pass an exam", ru:"сдать экзамен", ex:"She worked hard and passed all her exams." },
    { id:"v4-B1-95", en:"fail", ru:"провалить, не сдать", ex:"He was afraid he might fail the test." },
    { id:"v4-B1-96", en:"assignment", ru:"задание, работа", ex:"The assignment is due next Monday." },
    { id:"v4-B1-97", en:"tuition fees", ru:"плата за обучение", ex:"University tuition fees are very high." },
    { id:"v4-B1-98", en:"hand in", ru:"сдавать (работу)", ex:"Please hand in your essays by Friday." },
    { id:"v4-B1-99", en:"distance learning", ru:"дистанционное обучение", ex:"Many students prefer distance learning these days." },
    { id:"v4-B1-100", en:"keep up with", ru:"успевать за, не отставать", ex:"It's hard to keep up with all the homework." },

    // медиа/развлечения
    { id:"v4-B1-101", en:"plot", ru:"сюжет", ex:"The film has a complicated plot." },
    { id:"v4-B1-102", en:"subtitles", ru:"субтитры", ex:"I watch foreign films with English subtitles." },
    { id:"v4-B1-103", en:"episode", ru:"серия, эпизод", ex:"The final episode was really exciting." },
    { id:"v4-B1-104", en:"review", ru:"отзыв, рецензия", ex:"The book got excellent reviews." },
    { id:"v4-B1-105", en:"livestream", ru:"прямая трансляция", ex:"They watched the concert on a livestream." },
    { id:"v4-B1-106", en:"box office", ru:"кассовые сборы", ex:"The movie was a huge box office success." },
    { id:"v4-B1-107", en:"documentary", ru:"документальный фильм", ex:"I watched a documentary about the ocean." },
    { id:"v4-B1-108", en:"catchy", ru:"запоминающийся (о мелодии)", ex:"That song has a really catchy tune." },
    { id:"v4-B1-109", en:"binge-watch", ru:"смотреть запоем", ex:"We binge-watched the whole series in a weekend." },
    { id:"v4-B1-110", en:"audience", ru:"аудитория, зрители", ex:"The audience clapped at the end of the show." },

    // город/общество
    { id:"v4-B1-111", en:"crowded", ru:"переполненный", ex:"The streets are crowded during rush hour." },
    { id:"v4-B1-112", en:"public transport", ru:"общественный транспорт", ex:"I use public transport to get to work." },
    { id:"v4-B1-113", en:"suburb", ru:"пригород", ex:"They live in a quiet suburb outside the city." },
    { id:"v4-B1-114", en:"facilities", ru:"удобства, инфраструктура", ex:"The town has excellent sports facilities." },
    { id:"v4-B1-115", en:"traffic jam", ru:"пробка", ex:"We were stuck in a traffic jam for an hour." },
    { id:"v4-B1-116", en:"cost of living", ru:"стоимость жизни", ex:"The cost of living is high in the capital." },
    { id:"v4-B1-117", en:"pedestrian", ru:"пешеход", ex:"The city centre is mostly for pedestrians." },
    { id:"v4-B1-118", en:"neighbourhood", ru:"район, окрестности", ex:"It's a friendly neighbourhood with nice people." },
    { id:"v4-B1-119", en:"litter", ru:"мусор (на улице)", ex:"Please don't drop litter in the park." },
    { id:"v4-B1-120", en:"commute", ru:"ездить на работу; поездка на работу", ex:"My daily commute takes about an hour." },

    // еда/рестораны
    { id:"v4-B1-121", en:"starter", ru:"закуска", ex:"For my starter I'll have the soup." },
    { id:"v4-B1-122", en:"book a table", ru:"забронировать столик", ex:"Let's book a table for eight o'clock." },
    { id:"v4-B1-123", en:"vegetarian", ru:"вегетарианский; вегетарианец", ex:"Do you have any vegetarian dishes?" },
    { id:"v4-B1-124", en:"tip", ru:"чаевые", ex:"We left a generous tip for the waiter." },
    { id:"v4-B1-125", en:"tasty", ru:"вкусный", ex:"The pasta here is really tasty." },
    { id:"v4-B1-126", en:"the bill", ru:"счёт (в ресторане)", ex:"Could we have the bill, please?" },
    { id:"v4-B1-127", en:"takeaway", ru:"еда навынос", ex:"Let's order a takeaway tonight." },
    { id:"v4-B1-128", en:"course", ru:"блюдо (часть обеда)", ex:"We had a three-course dinner." },
    { id:"v4-B1-129", en:"spicy", ru:"острый", ex:"This curry is too spicy for me." },
    { id:"v4-B1-130", en:"eat out", ru:"есть вне дома, в ресторане", ex:"We eat out about once a week." },

    // дом/жильё
    { id:"v4-B1-131", en:"rent", ru:"аренда; снимать (жильё)", ex:"They rent a flat in the city centre." },
    { id:"v4-B1-132", en:"furniture", ru:"мебель", ex:"We bought some new furniture for the living room." },
    { id:"v4-B1-133", en:"move in", ru:"въезжать (в жильё)", ex:"We're going to move in next weekend." },
    { id:"v4-B1-134", en:"landlord", ru:"арендодатель, хозяин жилья", ex:"Our landlord is raising the rent again." },
    { id:"v4-B1-135", en:"tidy up", ru:"прибираться", ex:"I need to tidy up before the guests arrive." },
    { id:"v4-B1-136", en:"spacious", ru:"просторный", ex:"The new apartment is bright and spacious." },
    { id:"v4-B1-137", en:"do up", ru:"ремонтировать, отделывать", ex:"They bought an old house and did it up themselves." },
    { id:"v4-B1-138", en:"cosy", ru:"уютный", ex:"The cottage was small but very cosy." },
    { id:"v4-B1-139", en:"mortgage", ru:"ипотека", ex:"They took out a mortgage to buy their first home." },
    { id:"v4-B1-140", en:"household chores", ru:"домашние дела", ex:"We share the household chores equally." },

    // погода/природа
    { id:"v4-B1-141", en:"forecast", ru:"прогноз (погоды)", ex:"The weather forecast says it will rain tomorrow." },
    { id:"v4-B1-142", en:"freezing", ru:"очень холодный, морозный", ex:"It was freezing outside this morning." },
    { id:"v4-B1-143", en:"humid", ru:"влажный (о климате)", ex:"The weather here is hot and humid in summer." },
    { id:"v4-B1-144", en:"thunderstorm", ru:"гроза", ex:"A thunderstorm is expected this afternoon." },
    { id:"v4-B1-145", en:"breeze", ru:"лёгкий ветерок", ex:"There was a pleasant breeze by the sea." },
    { id:"v4-B1-146", en:"flood", ru:"наводнение", ex:"Heavy rain caused a flood in the village." },
    { id:"v4-B1-147", en:"clear up", ru:"проясняться (о погоде)", ex:"The sky should clear up by the evening." },
    { id:"v4-B1-148", en:"drought", ru:"засуха", ex:"The long drought damaged many crops." },
    { id:"v4-B1-149", en:"mild", ru:"мягкий (о погоде)", ex:"We had a mild winter this year." },
    { id:"v4-B1-150", en:"wildlife", ru:"дикая природа", ex:"The national park is home to a lot of wildlife." },

    // преступление/закон базово
    { id:"v4-B1-151", en:"burglary", ru:"кража со взломом", ex:"There has been a burglary in our street." },
    { id:"v4-B1-152", en:"witness", ru:"свидетель", ex:"A witness saw the whole accident." },
    { id:"v4-B1-153", en:"arrest", ru:"арестовывать; арест", ex:"The police arrested two suspects last night." },
    { id:"v4-B1-154", en:"fine", ru:"штраф", ex:"He had to pay a fine for speeding." },
    { id:"v4-B1-155", en:"guilty", ru:"виновный", ex:"The jury found him guilty of theft." },
    { id:"v4-B1-156", en:"trial", ru:"судебный процесс", ex:"The trial will begin next month." },
    { id:"v4-B1-157", en:"shoplifting", ru:"магазинная кража", ex:"She was caught shoplifting in the supermarket." },
    { id:"v4-B1-158", en:"evidence", ru:"доказательства, улики", ex:"There was not enough evidence to convict him." },
    { id:"v4-B1-159", en:"suspect", ru:"подозреваемый; подозревать", ex:"The police are questioning a suspect." },
    { id:"v4-B1-160", en:"break the law", ru:"нарушать закон", ex:"You can be punished if you break the law." },

    // частотные глаголы
    { id:"v4-B1-161", en:"avoid", ru:"избегать", ex:"Try to avoid eating too much sugar." },
    { id:"v4-B1-162", en:"realise", ru:"осознавать, понимать", ex:"I didn't realise how late it was." },
    { id:"v4-B1-163", en:"suggest", ru:"предлагать", ex:"She suggested going for a walk." },
    { id:"v4-B1-164", en:"manage", ru:"справляться, суметь", ex:"He managed to finish the project on time." },
    { id:"v4-B1-165", en:"prevent", ru:"предотвращать", ex:"Vaccines help prevent many diseases." },
    { id:"v4-B1-166", en:"deserve", ru:"заслуживать", ex:"You worked hard and deserve a break." },
    { id:"v4-B1-167", en:"admit", ru:"признавать(ся)", ex:"He admitted that he had made a mistake." },
    { id:"v4-B1-168", en:"replace", ru:"заменять", ex:"We need to replace the old printer." },
    { id:"v4-B1-169", en:"complain", ru:"жаловаться", ex:"They complained about the noisy neighbours." },
    { id:"v4-B1-170", en:"encourage", ru:"поощрять, подбадривать", ex:"My teacher encouraged me to study abroad." },

    // частотные прилагательные
    { id:"v4-B1-171", en:"convenient", ru:"удобный (по расположению/времени)", ex:"The shop is in a convenient location." },
    { id:"v4-B1-172", en:"obvious", ru:"очевидный", ex:"It was obvious that she was tired." },
    { id:"v4-B1-173", en:"impressive", ru:"впечатляющий", ex:"His knowledge of history is impressive." },
    { id:"v4-B1-174", en:"essential", ru:"необходимый, важнейший", ex:"Water is essential for life." },
    { id:"v4-B1-175", en:"reasonable", ru:"разумный, приемлемый", ex:"The prices in this restaurant are reasonable." },
    { id:"v4-B1-176", en:"worried", ru:"обеспокоенный", ex:"I'm worried about the exam tomorrow." },
    { id:"v4-B1-177", en:"unexpected", ru:"неожиданный", ex:"We had an unexpected visit from an old friend." },
    { id:"v4-B1-178", en:"appropriate", ru:"подходящий, уместный", ex:"Please wear appropriate clothes for the interview." },
    { id:"v4-B1-179", en:"valuable", ru:"ценный", ex:"She gave me some valuable advice." },
    { id:"v4-B1-180", en:"available", ru:"доступный, имеющийся в наличии", ex:"The tickets are available online." },

    // фразовые выражения
    { id:"v4-B1-181", en:"look forward to", ru:"с нетерпением ждать", ex:"I look forward to seeing you next week." },
    { id:"v4-B1-182", en:"give up", ru:"бросать, сдаваться", ex:"He gave up smoking last year." },
    { id:"v4-B1-183", en:"find out", ru:"выяснять, узнавать", ex:"I need to find out the train times." },
    { id:"v4-B1-184", en:"put off", ru:"откладывать", ex:"Don't put off your homework until the last minute." },
    { id:"v4-B1-185", en:"take part in", ru:"принимать участие в", ex:"Many students took part in the competition." },
    { id:"v4-B1-186", en:"deal with", ru:"справляться с, разбираться с", ex:"She knows how to deal with difficult customers." },
    { id:"v4-B1-187", en:"come up with", ru:"придумать (идею)", ex:"He came up with a brilliant solution." },
    { id:"v4-B1-188", en:"run out of", ru:"закончиться (о запасе)", ex:"We've run out of milk again." },
    { id:"v4-B1-189", en:"figure out", ru:"разобраться, понять", ex:"I can't figure out how this machine works." },
    { id:"v4-B1-190", en:"get rid of", ru:"избавиться от", ex:"It's time to get rid of these old clothes." },

    // наречия
    { id:"v4-B1-191", en:"eventually", ru:"в конце концов", ex:"After many attempts, she eventually succeeded." },
    { id:"v4-B1-192", en:"hardly", ru:"едва, почти не", ex:"I could hardly hear him in the noisy room." },
    { id:"v4-B1-193", en:"definitely", ru:"определённо, точно", ex:"I'll definitely be there on time." },
    { id:"v4-B1-194", en:"fortunately", ru:"к счастью", ex:"Fortunately, nobody was hurt in the accident." },
    { id:"v4-B1-195", en:"barely", ru:"едва, с трудом", ex:"He barely passed the exam." },
    { id:"v4-B1-196", en:"gradually", ru:"постепенно", ex:"The weather gradually got warmer." },
    { id:"v4-B1-197", en:"apparently", ru:"по-видимому, как говорят", ex:"Apparently, the meeting has been cancelled." },
    { id:"v4-B1-198", en:"frequently", ru:"часто", ex:"He frequently travels for work." },
    { id:"v4-B1-199", en:"roughly", ru:"приблизительно", ex:"The trip takes roughly two hours." },
    { id:"v4-B1-200", en:"meanwhile", ru:"тем временем", ex:"I'll cook dinner; meanwhile, you can set the table." }
  ]);
})();
