(() => {
  const C = window.CONTENT || (window.CONTENT = {});
  const P = (track, lvl, arr) => { C[track]=C[track]||{}; C[track][lvl]=C[track][lvl]||[]; arr.forEach(x=>C[track][lvl].push(x)); };

  P("reading","C2",[
    {
      id:"r2c-C2-01",
      title:"The Tyranny of the Measurable",
      text:"There is a quiet violence in the modern compulsion to quantify. What begins as a reasonable desire for clarity gradually hardens into a doctrine: that which cannot be counted does not count. Institutions, having learned to reward what their instruments can detect, slowly reorganise themselves around the detectable, mistaking the shadow of a thing for the thing itself. A university measures citations and forgets wisdom; a hospital measures throughput and mislays compassion; a society measures its gross product and quietly forgets to ask what the product is for. The danger is not measurement as such, which is a noble and necessary craft, but the silent inversion whereby the metric ceases to serve the value and the value is reshaped to flatter the metric. Once a number becomes a target, those subject to it grow ingenious in satisfying its letter while betraying its spirit, and the original purpose evaporates while every indicator glows reassuringly green. What is lost in this transaction is precisely the immeasurable: the texture of an unhurried conversation, the patience of genuine inquiry, the dignity that resists being scored. To recover these we need not abolish the instruments but humble them, remembering that the most consequential goods of a human life announce themselves not on dashboards but in the slow, unaudited accumulation of meaning that no quarterly report has ever managed to capture.",
      questions:[
        { q:"What does the author suggest is the central problem with measurement?", options:["The reversal in which values are reshaped to suit metrics","That instruments are too imprecise to be trusted","That measurement is inherently violent and should be abolished","That institutions lack the technology to measure properly"], answer:0 },
        { q:"The phrase 'mistaking the shadow of a thing for the thing itself' most nearly conveys that institutions:", options:["deliberately conceal their true intentions","confuse a proxy indicator with the underlying reality","prefer darkness to transparency","value appearance over efficiency"], answer:1 },
        { q:"What can be inferred about the author's view of those 'subject to' targets?", options:["They are uniquely dishonest individuals","They sabotage systems out of malice","They rationally optimise for the letter of a rule at the cost of its purpose","They are incapable of understanding the metrics imposed on them"], answer:2 },
        { q:"The concluding sentence implies that meaning is best understood as something that:", options:["accrues quietly and escapes formal accounting","can eventually be captured by better dashboards","is irrelevant to institutional life","contradicts the pursuit of dignity"], answer:0 }
      ]
    },
    {
      id:"r2c-C2-02",
      title:"On the Architecture of Forgetting",
      text:"Memory, we are fond of saying, is the storehouse of the self, yet the metaphor flatters us with a permanence that the brain never promised. Far from a vault preserving its contents intact, recollection is closer to an act of reconstruction performed afresh each time we summon it, a quiet improvisation that borrows from the present to repair the gaps of the past. Each retrieval subtly edits the original, so that the memories we trust most fervently, polished by repeated handling, may be precisely the least faithful to what occurred. Forgetting, far from a mere failure of this machinery, turns out to be one of its more elegant features. A mind that retained everything indiscriminately would drown in the undifferentiated noise of its own experience, unable to distinguish the trivial from the consequential, condemned to relive each slight and triumph with undiminished intensity. To forget is to make space for judgement, to allow the salient to rise above the forgettable like landmarks emerging from a receding tide. There is, then, a curious wisdom in oblivion, for the self we cherish is not the sum of everything that happened to us but a careful, partly fictional curation, an autobiography continually revised by an author who has conveniently forgotten that the manuscript was ever anything other than the truth.",
      questions:[
        { q:"The author's central claim about memory is that it:", options:["functions like a perfectly sealed archive","is reconstructed and altered with each act of recall","declines only with age or injury","stores emotions more reliably than facts"], answer:1 },
        { q:"Why might the most trusted memories be the least accurate?", options:["They are formed during moments of high emotion","They have been repeatedly retrieved and thus repeatedly edited","They concern events from the distant past","They are deliberately falsified by the conscious mind"], answer:1 },
        { q:"What is the author's attitude toward forgetting?", options:["It is a regrettable defect to be overcome","It is an adaptive feature enabling judgement","It is morally neutral and of no consequence","It is the principal cause of an unstable self"], answer:1 },
        { q:"The final image of the 'author' who forgets the manuscript was revised suggests that the self is:", options:["a deliberate fabrication intended to deceive others","an accurate transcript of lived events","a partly invented narrative mistaken for fact","an unchanging essence beneath experience"], answer:2 }
      ]
    },
    {
      id:"r2c-C2-03",
      title:"The Ethics of the Unborn Algorithm",
      text:"When we delegate a decision to a machine, we are tempted to imagine that we have outsourced not only the labour but the responsibility, as though moral weight could be exported along with the computation. Yet an algorithm is not a neutral arbiter descending from some realm of pure logic; it is a sediment of human choices, a frozen distillation of the values, oversights and prejudices of those who specified its objectives and curated its diet of data. Its apparent impartiality is the most seductive of its disguises, for a verdict delivered without a face invites no appeal and provokes no shame. The peril deepens because such systems generalise: a single biased model, deployed at scale, does not commit one injustice but industrialises it, replicating across millions of cases a flaw that a human clerk might have applied only once before being corrected by conscience or complaint. We comfort ourselves that the code merely reflects the world as it is, but a system trained on the past is, in effect, a machine for perpetuating it, conferring upon yesterday's inequities the unearned authority of mathematics. To govern these instruments wisely is therefore less a technical problem than a moral one, demanding that we decide, openly and in advance, not what the machine can optimise but what kind of world we are willing to have it optimise toward.",
      questions:[
        { q:"What illusion does the author warn against when decisions are delegated to machines?", options:["That machines compute faster than humans","That responsibility is transferred along with the task","That algorithms cannot handle complex data","That automation reduces overall costs"], answer:1 },
        { q:"Why is an algorithm's 'apparent impartiality' described as a disguise?", options:["It hides the embedded human values and biases within","It conceals the machine's true processing speed","It masks how expensive the system is to run","It disguises errors as deliberate features"], answer:0 },
        { q:"What does the author mean by saying biased systems 'industrialise' injustice?", options:["They make injustice profitable for corporations","They replicate a single flaw across vast numbers of cases","They require factories to operate","They eliminate human workers entirely"], answer:1 },
        { q:"The closing sentence implies that governing algorithms primarily requires:", options:["faster hardware and cleaner data","prior moral deliberation about desired outcomes","stricter limits on computational power","removing humans from the design process"], answer:1 }
      ]
    },
    {
      id:"r2c-C2-04",
      title:"The Consolations of Uncertainty",
      text:"We tend to regard doubt as a deficiency, a fog to be dispelled by the bright lamp of conviction, and certainty as the natural reward of a mind that has done its work. Yet the history of inquiry suggests an almost opposite moral: that the most catastrophic errors are committed not by those who hesitate but by those who are sure. Certainty closes the door that doubt holds open; it converts a provisional hypothesis into an article of faith and thereby exempts it from the scrutiny that might have saved us. The honest thinker, by contrast, learns to inhabit uncertainty not as a temporary discomfort but as a permanent condition of intellectual life, holding convictions firmly enough to act upon them yet loosely enough to surrender them when the evidence demands. This is a far harder discipline than dogmatism, which asks only that we stop thinking once we have found an answer that pleases us. To remain genuinely open is to accept that one's cherished beliefs are loans rather than possessions, advanced by the present state of knowledge and recallable without notice. There is a peculiar serenity available to those who make this peace with their own fallibility, for they are spared the exhausting labour of defending the indefensible, and they discover, in the very admission that they might be wrong, the only reliable path by which anyone has ever come to be a little less so.",
      questions:[
        { q:"What counterintuitive claim does the author advance about certainty?", options:["It is the proper reward for diligent thinking","It tends to produce the most serious errors","It is impossible for any thinker to achieve","It is identical to genuine knowledge"], answer:1 },
        { q:"The metaphor of beliefs as 'loans rather than possessions' implies that one should:", options:["never commit to any position whatsoever","hold beliefs while being ready to relinquish them","borrow ideas freely from other thinkers","invest emotionally in one's convictions"], answer:1 },
        { q:"Why does the author consider open-mindedness harder than dogmatism?", options:["It requires continued thinking even after an answer is found","It demands greater factual knowledge","It is socially less acceptable","It produces more anxiety and no benefit"], answer:0 },
        { q:"The 'peculiar serenity' described arises chiefly from:", options:["the certainty of having reached the truth","being freed from defending untenable positions","the admiration of one's peers","the avoidance of all difficult questions"], answer:1 }
      ]
    },
    {
      id:"r2c-C2-05",
      title:"Cities as Living Organisms",
      text:"To walk through an ancient city is to read a palimpsest in stone, a text written and overwritten by successive generations, none of whom intended the composite their additions would eventually form. No single mind designed the tangle of medieval lanes that now charms the tourist; each was the rational response of some forgotten householder to the constraints of his moment, and the whole emerged, unplanned and unforeseen, from the accumulation of countless local decisions. This is the deep paradox of urban life: that order can arise without an orderer, that a coherence no committee could have engineered may crystallise from the friction of competing intentions. The great planners of the last century, mistrusting this messy spontaneity, sought to replace it with the clean geometry of the master plan, and produced instead the sterile expanses whose very rationality rendered them uninhabitable to the human spirit. A living city, it transpires, thrives on a certain productive disorder, on the overlapping of uses and the chance encounters that a tidy zoning map forbids. Its vitality is emergent rather than imposed, the property of the whole and of no part, and it cannot be commanded into being any more than a forest can be assembled from a blueprint. The wisest planning, then, may be the most humble, content to tend conditions and trust that the city, like any living thing, will find its own way to flourish.",
      questions:[
        { q:"What does the comparison of the city to a 'palimpsest' emphasise?", options:["Its layering by successive generations without a unifying plan","The fragility of its building materials","The hidden writings buried beneath its streets","Its careful design by a single architect"], answer:0 },
        { q:"The 'deep paradox of urban life' refers to the idea that:", options:["cities are simultaneously old and new","order can emerge without anyone designing it","planners always fail in their ambitions","tourists misunderstand the cities they visit"], answer:1 },
        { q:"Why did the master plans of the last century fail, according to the author?", options:["They were too expensive to complete","Their rigid rationality made them hostile to human life","They ignored advances in engineering","They were never actually built"], answer:1 },
        { q:"What attitude toward planning does the passage ultimately endorse?", options:["Aggressive central control of all development","A humble approach that tends conditions rather than dictates form","The complete abandonment of any planning","Strict zoning to separate incompatible uses"], answer:1 }
      ]
    },
    {
      id:"r2c-C2-06",
      title:"The Paradox of the Examined Life",
      text:"Socrates left us the imperious injunction that the unexamined life is not worth living, and few maxims have been repeated with more reverence or less reflection. Yet there is a shadow that falls across the examined life as well, a danger native to introspection itself. The mind that turns relentlessly upon its own workings risks a peculiar paralysis, dissecting each impulse so thoroughly that none survives the operation, until spontaneity withers under the cold gaze of perpetual self-scrutiny. The dancer who counts every step ceases to dance; the writer who watches each sentence form forgets how to write. There is a kind of knowing that lives only in the doing, and that the act of examination, by extracting it for inspection, inevitably destroys. The wisest souls, it seems, have understood that examination is a seasonal discipline rather than a continuous state, a periodic reckoning to be undertaken and then set aside, so that the self thus interrogated may return to the unselfconscious immersion in which most of what is valuable in a life actually occurs. To examine well is therefore also to know when to stop examining, to trust the cultivated instincts that reflection has refined and then released back into the wild of ordinary action, where they do their finest and least observable work.",
      questions:[
        { q:"What 'shadow' does the author identify in the examined life?", options:["That self-scrutiny can paralyse spontaneity and action","That it requires more time than most people have","That it leads inevitably to despair","That Socrates was mistaken about its value entirely"], answer:0 },
        { q:"The examples of the dancer and the writer serve to illustrate that:", options:["practice is essential to mastery","certain skills are destroyed by conscious analysis","examination improves all forms of performance","artists are especially prone to self-doubt"], answer:1 },
        { q:"The phrase 'a seasonal discipline rather than a continuous state' suggests examination should be:", options:["practised only by trained philosophers","conducted periodically and then suspended","abandoned in favour of pure instinct","performed with maximum frequency"], answer:1 },
        { q:"What does the author imply is the proper relationship between reflection and instinct?", options:["Reflection should permanently override instinct","Instinct should be eliminated through reflection","Reflection refines instincts that are then trusted in action","The two are fundamentally incompatible"], answer:2 }
      ]
    },
    {
      id:"r2c-C2-07",
      title:"The Aesthetics of Imperfection",
      text:"The Japanese tradition of wabi-sabi locates beauty not in the flawless but in the weathered, the asymmetrical, the transient, finding in a cracked bowl or a fading blossom a poignancy that no pristine artefact can match. To the sensibility schooled in the Western ideal of perfection, this may seem a perverse celebration of failure, a romance with decay. Yet it rests on a profound intuition that our cult of the perfect quietly betrays: that flawlessness, by refusing to acknowledge time, severs the object from the only world it can actually inhabit. A perfect thing is mute about its history; it pretends to have escaped the entropy that governs everything else, and in that pretence it becomes, paradoxically, less real and less moving than the chipped cup that wears its years honestly. The crack in the glaze is not a wound to be lamented but a signature of authenticity, a trace of the object's passage through time and use, the very thing that makes it irreplaceably itself rather than one interchangeable instance of a flawless type. To love the imperfect, then, is not to lower one's standards but to raise one's vision, to perceive that what we share with the things we cherish is precisely our common vulnerability to time, and that beauty grasped in this register is not the denial of mortality but its tender, clear-eyed acceptance.",
      questions:[
        { q:"What underlying intuition does the author say wabi-sabi expresses?", options:["That flawlessness denies time and thereby diminishes reality","That Western art is inferior to Japanese art","That all objects should be deliberately damaged","That beauty is purely a matter of cultural convention"], answer:0 },
        { q:"Why does the author call a perfect thing 'mute about its history'?", options:["It cannot be described in words","It conceals the labour that produced it","It shows no trace of having passed through time","It is too fragile to handle"], answer:2 },
        { q:"The crack in the glaze is reinterpreted as:", options:["a defect that lowers the object's worth","a signature of authenticity and individuality","evidence of careless craftsmanship","a temporary flaw that can be repaired"], answer:1 },
        { q:"The final sentence implies that appreciating imperfection is ultimately a way of:", options:["rejecting all aesthetic standards","accepting our shared mortality with clear eyes","escaping the constraints of time","proving the superiority of old objects"], answer:1 }
      ]
    },
    {
      id:"r2c-C2-08",
      title:"The Future That Refuses to Arrive",
      text:"Every age imagines a future and is then quietly governed by the failure of that future to materialise. The mid-century prophets foresaw flying cars and lunar colonies, and we, inheriting their disappointment, have learned a wary scepticism toward all forecasts of transformation. Yet the deeper truth is subtler than the simple fact that prediction is hard. The future does arrive, but it arrives sideways, dressed in the unremarkable clothes of the everyday, so that we fail to recognise it as the marvel an earlier generation would have found it. We dreamed of robot servants and received instead an invisible web of computation that anticipates our desires before we have articulated them, a transformation so total that it has become atmospheric, beneath the threshold of astonishment. This is the characteristic trick of genuine change: not the spectacular rupture we are taught to expect, but a gradual normalisation so complete that the extraordinary is recategorised as the obvious almost as soon as it appears. We are, in this sense, poor witnesses to our own revolutions, perpetually scanning the horizon for a dramatic arrival while the actual future seeps in unannounced through a thousand small conveniences. To see one's own moment clearly, then, requires an almost wilful estrangement, the discipline of looking at the familiar as a visitor from the past might, and recovering thereby the wonder we have so efficiently mislaid.",
      questions:[
        { q:"What is the author's main point about how the future arrives?", options:["It never arrives as predicted and so disappoints us","It arrives gradually and becomes normalised beyond notice","It is impossible to predict by any method","It arrives only through spectacular ruptures"], answer:1 },
        { q:"Why does the author say we are 'poor witnesses to our own revolutions'?", options:["We lack the education to understand technology","We expect dramatic change and miss the gradual kind","We are too distracted by everyday tasks","We deliberately ignore important developments"], answer:1 },
        { q:"The reference to computation as 'atmospheric' chiefly conveys that it has become:", options:["harmful to the environment","so pervasive it goes unnoticed","limited to wealthy nations","increasingly unreliable"], answer:1 },
        { q:"The 'wilful estrangement' the author recommends is a means of:", options:["predicting future technologies more accurately","recovering a sense of wonder at the familiar","rejecting modern conveniences","returning to the values of the past"], answer:1 }
      ]
    }
  ]);
})();
