(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("vocab","A2",[
    // === Дом / мебель / быт ===
    { id:"v4-A2-01", en:"furniture", ru:"мебель", ex:"We bought new furniture for the living room." },
    { id:"v4-A2-02", en:"wardrobe", ru:"шкаф (для одежды)", ex:"Hang your coat in the wardrobe." },
    { id:"v4-A2-03", en:"drawer", ru:"ящик (комода)", ex:"The keys are in the top drawer." },
    { id:"v4-A2-04", en:"shelf", ru:"полка", ex:"She put the books on the shelf." },
    { id:"v4-A2-05", en:"curtain", ru:"занавеска", ex:"Please close the curtains at night." },
    { id:"v4-A2-06", en:"pillow", ru:"подушка", ex:"This pillow is very soft." },
    { id:"v4-A2-07", en:"blanket", ru:"одеяло", ex:"I need a warm blanket in winter." },
    { id:"v4-A2-08", en:"ceiling", ru:"потолок", ex:"There is a lamp on the ceiling." },
    { id:"v4-A2-09", en:"stairs", ru:"лестница", ex:"Go up the stairs to the second floor." },
    { id:"v4-A2-10", en:"basement", ru:"подвал", ex:"We keep old boxes in the basement." },
    { id:"v4-A2-11", en:"vacuum cleaner", ru:"пылесос", ex:"I use the vacuum cleaner every weekend." },
    { id:"v4-A2-12", en:"rubbish bin", ru:"мусорное ведро", ex:"Throw it in the rubbish bin, please." },

    // === Кухня / еда / напитки ===
    { id:"v4-A2-13", en:"frying pan", ru:"сковорода", ex:"Heat the oil in the frying pan." },
    { id:"v4-A2-14", en:"kettle", ru:"чайник (электрический)", ex:"I'll put the kettle on for tea." },
    { id:"v4-A2-15", en:"fork", ru:"вилка", ex:"Eat the salad with a fork." },
    { id:"v4-A2-16", en:"recipe", ru:"рецепт", ex:"This recipe is easy to follow." },
    { id:"v4-A2-17", en:"flour", ru:"мука", ex:"You need flour to bake bread." },
    { id:"v4-A2-18", en:"vegetable", ru:"овощ", ex:"Carrots are my favourite vegetable." },
    { id:"v4-A2-19", en:"snack", ru:"перекус", ex:"I had a snack before dinner." },
    { id:"v4-A2-20", en:"juice", ru:"сок", ex:"She drinks orange juice in the morning." },
    { id:"v4-A2-21", en:"to boil", ru:"кипятить / варить", ex:"Boil the water before adding the pasta." },
    { id:"v4-A2-22", en:"to taste", ru:"пробовать на вкус", ex:"Taste the soup and add salt." },
    { id:"v4-A2-23", en:"dessert", ru:"десерт", ex:"We had ice cream for dessert." },
    { id:"v4-A2-24", en:"meal", ru:"приём пищи / блюдо", ex:"Breakfast is my favourite meal." },

    // === Город / места / магазины ===
    { id:"v4-A2-25", en:"pharmacy", ru:"аптека", ex:"You can buy medicine at the pharmacy." },
    { id:"v4-A2-26", en:"bakery", ru:"пекарня", ex:"The bakery sells fresh bread every day." },
    { id:"v4-A2-27", en:"library", ru:"библиотека", ex:"I borrowed three books from the library." },
    { id:"v4-A2-28", en:"market", ru:"рынок", ex:"We buy fruit at the local market." },
    { id:"v4-A2-29", en:"square", ru:"площадь", ex:"The market is in the main square." },
    { id:"v4-A2-30", en:"bridge", ru:"мост", ex:"Cross the bridge to reach the park." },
    { id:"v4-A2-31", en:"corner", ru:"угол", ex:"The cafe is on the corner of the street." },
    { id:"v4-A2-32", en:"crossroads", ru:"перекрёсток", ex:"Turn left at the crossroads." },
    { id:"v4-A2-33", en:"neighbourhood", ru:"район / окрестности", ex:"It is a quiet neighbourhood." },
    { id:"v4-A2-34", en:"town hall", ru:"мэрия / ратуша", ex:"The town hall is a very old building." },
    { id:"v4-A2-35", en:"shopping centre", ru:"торговый центр", ex:"Let's meet at the shopping centre." },
    { id:"v4-A2-36", en:"car park", ru:"парковка", ex:"The car park is full today." },

    // === Транспорт / путешествия ===
    { id:"v4-A2-37", en:"platform", ru:"платформа (на вокзале)", ex:"The train leaves from platform two." },
    { id:"v4-A2-38", en:"ticket", ru:"билет", ex:"I bought a return ticket to London." },
    { id:"v4-A2-39", en:"luggage", ru:"багаж", ex:"My luggage is too heavy." },
    { id:"v4-A2-40", en:"passport", ru:"паспорт", ex:"Show your passport at the airport." },
    { id:"v4-A2-41", en:"flight", ru:"рейс / полёт", ex:"Our flight was delayed by an hour." },
    { id:"v4-A2-42", en:"to board", ru:"садиться (в самолёт/поезд)", ex:"Passengers can board the plane now." },
    { id:"v4-A2-43", en:"journey", ru:"поездка / путешествие", ex:"The journey took five hours." },
    { id:"v4-A2-44", en:"map", ru:"карта", ex:"Use the map to find the hotel." },
    { id:"v4-A2-45", en:"traffic", ru:"дорожное движение", ex:"There is a lot of traffic in the morning." },
    { id:"v4-A2-46", en:"abroad", ru:"за границей", ex:"They travel abroad every summer." },
    { id:"v4-A2-47", en:"to get off", ru:"выходить (из транспорта)", ex:"Get off the bus at the next stop." },
    { id:"v4-A2-48", en:"delay", ru:"задержка", ex:"There was a long delay at the station." },

    // === Одежда / аксессуары ===
    { id:"v4-A2-49", en:"jacket", ru:"куртка / пиджак", ex:"Take a jacket, it's cold outside." },
    { id:"v4-A2-50", en:"scarf", ru:"шарф", ex:"She wore a red scarf in winter." },
    { id:"v4-A2-51", en:"gloves", ru:"перчатки", ex:"My gloves keep my hands warm." },
    { id:"v4-A2-52", en:"belt", ru:"ремень", ex:"He needs a belt for these trousers." },
    { id:"v4-A2-53", en:"boots", ru:"ботинки / сапоги", ex:"I wear boots when it rains." },
    { id:"v4-A2-54", en:"jumper", ru:"свитер", ex:"This wool jumper is very warm." },
    { id:"v4-A2-55", en:"to wear", ru:"носить (одежду)", ex:"What will you wear to the party?" },
    { id:"v4-A2-56", en:"to try on", ru:"примерять", ex:"Can I try on these shoes?" },
    { id:"v4-A2-57", en:"size", ru:"размер", ex:"Do you have this in a larger size?" },
    { id:"v4-A2-58", en:"pocket", ru:"карман", ex:"My phone is in my pocket." },
    { id:"v4-A2-59", en:"umbrella", ru:"зонт", ex:"Take an umbrella, it might rain." },
    { id:"v4-A2-60", en:"jewellery", ru:"украшения", ex:"She keeps her jewellery in a small box." },

    // === Тело / здоровье ===
    { id:"v4-A2-61", en:"shoulder", ru:"плечо", ex:"My shoulder hurts after the gym." },
    { id:"v4-A2-62", en:"knee", ru:"колено", ex:"He fell and hurt his knee." },
    { id:"v4-A2-63", en:"throat", ru:"горло", ex:"I have a sore throat today." },
    { id:"v4-A2-64", en:"headache", ru:"головная боль", ex:"I have a headache, I need a pill." },
    { id:"v4-A2-65", en:"fever", ru:"температура / жар", ex:"The child has a high fever." },
    { id:"v4-A2-66", en:"cough", ru:"кашель", ex:"This cough won't go away." },
    { id:"v4-A2-67", en:"to feel", ru:"чувствовать себя", ex:"How do you feel today?" },
    { id:"v4-A2-68", en:"medicine", ru:"лекарство", ex:"Take this medicine twice a day." },
    { id:"v4-A2-69", en:"to rest", ru:"отдыхать", ex:"You should rest when you are ill." },
    { id:"v4-A2-70", en:"healthy", ru:"здоровый", ex:"She eats healthy food every day." },
    { id:"v4-A2-71", en:"injury", ru:"травма", ex:"He has a knee injury from football." },
    { id:"v4-A2-72", en:"appointment", ru:"приём (запись к врачу)", ex:"I have a doctor's appointment at noon." },

    // === Семья / люди ===
    { id:"v4-A2-73", en:"relative", ru:"родственник", ex:"All my relatives came to the wedding." },
    { id:"v4-A2-74", en:"cousin", ru:"двоюродный брат/сестра", ex:"My cousin lives in another city." },
    { id:"v4-A2-75", en:"nephew", ru:"племянник", ex:"My nephew is six years old." },
    { id:"v4-A2-76", en:"niece", ru:"племянница", ex:"I bought a gift for my niece." },
    { id:"v4-A2-77", en:"neighbour", ru:"сосед", ex:"Our neighbour is very friendly." },
    { id:"v4-A2-78", en:"couple", ru:"пара", ex:"They are a lovely young couple." },
    { id:"v4-A2-79", en:"twins", ru:"близнецы", ex:"The twins look exactly the same." },
    { id:"v4-A2-80", en:"adult", ru:"взрослый", ex:"This film is for adults only." },
    { id:"v4-A2-81", en:"to grow up", ru:"расти / взрослеть", ex:"I grew up in a small village." },
    { id:"v4-A2-82", en:"married", ru:"женатый / замужем", ex:"My sister got married last year." },
    { id:"v4-A2-83", en:"guest", ru:"гость", ex:"We have guests for dinner tonight." },
    { id:"v4-A2-84", en:"stranger", ru:"незнакомец", ex:"Don't talk to strangers." },

    // === Школа / предметы ===
    { id:"v4-A2-85", en:"subject", ru:"учебный предмет", ex:"Maths is my favourite subject." },
    { id:"v4-A2-86", en:"homework", ru:"домашнее задание", ex:"I finished my homework after dinner." },
    { id:"v4-A2-87", en:"exam", ru:"экзамен", ex:"She passed her English exam." },
    { id:"v4-A2-88", en:"dictionary", ru:"словарь", ex:"Look up the word in a dictionary." },
    { id:"v4-A2-89", en:"notebook", ru:"тетрадь", ex:"Write the answer in your notebook." },
    { id:"v4-A2-90", en:"rubber", ru:"ластик", ex:"Can I borrow your rubber?" },
    { id:"v4-A2-91", en:"break", ru:"перемена", ex:"We play outside during the break." },
    { id:"v4-A2-92", en:"to study", ru:"учиться / изучать", ex:"I study history at university." },
    { id:"v4-A2-93", en:"mark", ru:"оценка / отметка", ex:"He got a good mark on the test." },
    { id:"v4-A2-94", en:"classmate", ru:"одноклассник", ex:"My classmate helped me with the task." },
    { id:"v4-A2-95", en:"timetable", ru:"расписание", ex:"Check the timetable for tomorrow." },
    { id:"v4-A2-96", en:"to explain", ru:"объяснять", ex:"The teacher explained the rule again." },

    // === Природа / погода / времена года ===
    { id:"v4-A2-97", en:"weather", ru:"погода", ex:"The weather is sunny today." },
    { id:"v4-A2-98", en:"cloud", ru:"облако", ex:"There are dark clouds in the sky." },
    { id:"v4-A2-99", en:"storm", ru:"буря / гроза", ex:"A storm is coming this evening." },
    { id:"v4-A2-100", en:"fog", ru:"туман", ex:"It is hard to drive in the fog." },
    { id:"v4-A2-101", en:"thunder", ru:"гром", ex:"The dog is afraid of thunder." },
    { id:"v4-A2-102", en:"season", ru:"время года", ex:"Autumn is my favourite season." },
    { id:"v4-A2-103", en:"hill", ru:"холм", ex:"We walked up a small hill." },
    { id:"v4-A2-104", en:"lake", ru:"озеро", ex:"We swam in the cold lake." },
    { id:"v4-A2-105", en:"forest", ru:"лес", ex:"They got lost in the forest." },
    { id:"v4-A2-106", en:"wind", ru:"ветер", ex:"The wind is very strong today." },
    { id:"v4-A2-107", en:"to freeze", ru:"замерзать", ex:"The river freezes in winter." },
    { id:"v4-A2-108", en:"sunshine", ru:"солнечный свет", ex:"I love the warm sunshine." },

    // === Животные / растения ===
    { id:"v4-A2-109", en:"rabbit", ru:"кролик", ex:"The rabbit eats fresh carrots." },
    { id:"v4-A2-110", en:"sheep", ru:"овца", ex:"The farmer has many sheep." },
    { id:"v4-A2-111", en:"butterfly", ru:"бабочка", ex:"A butterfly landed on the flower." },
    { id:"v4-A2-112", en:"insect", ru:"насекомое", ex:"This insect has six legs." },
    { id:"v4-A2-113", en:"branch", ru:"ветка", ex:"A bird sat on the branch." },
    { id:"v4-A2-114", en:"leaf", ru:"лист (дерева)", ex:"A yellow leaf fell from the tree." },
    { id:"v4-A2-115", en:"seed", ru:"семя", ex:"Plant the seeds in spring." },
    { id:"v4-A2-116", en:"to feed", ru:"кормить", ex:"We feed the ducks in the park." },
    { id:"v4-A2-117", en:"wild", ru:"дикий", ex:"Wild animals live in the forest." },
    { id:"v4-A2-118", en:"tail", ru:"хвост", ex:"The dog wagged its tail happily." },
    { id:"v4-A2-119", en:"nest", ru:"гнездо", ex:"The bird built a nest in the tree." },
    { id:"v4-A2-120", en:"to grow", ru:"расти", ex:"These plants grow very fast." },

    // === Спорт / хобби / игры ===
    { id:"v4-A2-121", en:"team", ru:"команда", ex:"Our team won the match." },
    { id:"v4-A2-122", en:"coach", ru:"тренер", ex:"The coach trains us twice a week." },
    { id:"v4-A2-123", en:"match", ru:"матч / игра", ex:"The football match starts at six." },
    { id:"v4-A2-124", en:"to win", ru:"выигрывать", ex:"I hope we win the game." },
    { id:"v4-A2-125", en:"to lose", ru:"проигрывать", ex:"Nobody likes to lose." },
    { id:"v4-A2-126", en:"to practise", ru:"тренироваться / практиковать", ex:"I practise the guitar every day." },
    { id:"v4-A2-127", en:"hobby", ru:"увлечение / хобби", ex:"Painting is her favourite hobby." },
    { id:"v4-A2-128", en:"to collect", ru:"коллекционировать", ex:"He collects old coins." },
    { id:"v4-A2-129", en:"board game", ru:"настольная игра", ex:"We played a board game last night." },
    { id:"v4-A2-130", en:"to jog", ru:"бегать трусцой", ex:"I jog in the park every morning." },
    { id:"v4-A2-131", en:"chess", ru:"шахматы", ex:"My grandfather taught me chess." },
    { id:"v4-A2-132", en:"prize", ru:"приз / награда", ex:"She won first prize in the contest." },

    // === Профессии ===
    { id:"v4-A2-133", en:"engineer", ru:"инженер", ex:"My brother is a software engineer." },
    { id:"v4-A2-134", en:"lawyer", ru:"юрист / адвокат", ex:"The lawyer gave us good advice." },
    { id:"v4-A2-135", en:"nurse", ru:"медсестра / медбрат", ex:"The nurse checked my temperature." },
    { id:"v4-A2-136", en:"firefighter", ru:"пожарный", ex:"The firefighter saved the cat." },
    { id:"v4-A2-137", en:"plumber", ru:"сантехник", ex:"We called a plumber to fix the sink." },
    { id:"v4-A2-138", en:"waiter", ru:"официант", ex:"The waiter brought us the menu." },
    { id:"v4-A2-139", en:"manager", ru:"менеджер / руководитель", ex:"The manager is in a meeting now." },
    { id:"v4-A2-140", en:"scientist", ru:"учёный", ex:"The scientist works in a laboratory." },
    { id:"v4-A2-141", en:"electrician", ru:"электрик", ex:"An electrician fixed the lights." },
    { id:"v4-A2-142", en:"salary", ru:"зарплата", ex:"He earns a good salary." },
    { id:"v4-A2-143", en:"to apply", ru:"подавать заявку (на работу)", ex:"I want to apply for this job." },
    { id:"v4-A2-144", en:"colleague", ru:"коллега", ex:"My colleagues are very helpful." },

    // === Чувства / характер ===
    { id:"v4-A2-145", en:"proud", ru:"гордый", ex:"I am proud of my daughter." },
    { id:"v4-A2-146", en:"nervous", ru:"нервный / волнующийся", ex:"She felt nervous before the exam." },
    { id:"v4-A2-147", en:"shy", ru:"застенчивый", ex:"He is too shy to speak in class." },
    { id:"v4-A2-148", en:"polite", ru:"вежливый", ex:"Always be polite to guests." },
    { id:"v4-A2-149", en:"honest", ru:"честный", ex:"She is an honest person." },
    { id:"v4-A2-150", en:"generous", ru:"щедрый", ex:"He is generous with his time." },
    { id:"v4-A2-151", en:"lazy", ru:"ленивый", ex:"Don't be lazy, do your homework." },
    { id:"v4-A2-152", en:"confident", ru:"уверенный в себе", ex:"She feels confident on stage." },
    { id:"v4-A2-153", en:"to worry", ru:"беспокоиться", ex:"Don't worry, everything is fine." },
    { id:"v4-A2-154", en:"calm", ru:"спокойный", ex:"Stay calm and breathe slowly." },
    { id:"v4-A2-155", en:"friendly", ru:"дружелюбный", ex:"The new student is very friendly." },
    { id:"v4-A2-156", en:"brave", ru:"смелый", ex:"The brave boy helped the old man." },

    // === Ежедневные действия / глаголы ===
    { id:"v4-A2-157", en:"to wake up", ru:"просыпаться", ex:"I wake up at seven every day." },
    { id:"v4-A2-158", en:"to brush", ru:"чистить (зубы)", ex:"Brush your teeth before bed." },
    { id:"v4-A2-159", en:"to hurry", ru:"торопиться", ex:"Hurry up, we are late!" },
    { id:"v4-A2-160", en:"to borrow", ru:"брать взаймы", ex:"Can I borrow your pen?" },
    { id:"v4-A2-161", en:"to lend", ru:"давать взаймы", ex:"I can lend you ten pounds." },
    { id:"v4-A2-162", en:"to clean", ru:"убирать / чистить", ex:"I clean my room on Saturdays." },
    { id:"v4-A2-163", en:"to repair", ru:"чинить / ремонтировать", ex:"He repaired my bike yesterday." },
    { id:"v4-A2-164", en:"to choose", ru:"выбирать", ex:"It is hard to choose a present." },
    { id:"v4-A2-165", en:"to remember", ru:"помнить", ex:"I can't remember her name." },
    { id:"v4-A2-166", en:"to forget", ru:"забывать", ex:"Don't forget to call me." },
    { id:"v4-A2-167", en:"to prepare", ru:"готовить / подготавливать", ex:"She prepared dinner for us." },
    { id:"v4-A2-168", en:"to return", ru:"возвращать(ся)", ex:"Please return the book on time." },

    // === Время / числа / даты ===
    { id:"v4-A2-169", en:"century", ru:"век / столетие", ex:"The castle is from the last century." },
    { id:"v4-A2-170", en:"decade", ru:"десятилетие", ex:"We've been friends for a decade." },
    { id:"v4-A2-171", en:"midnight", ru:"полночь", ex:"The party ended at midnight." },
    { id:"v4-A2-172", en:"midday", ru:"полдень", ex:"We had lunch at midday." },
    { id:"v4-A2-173", en:"fortnight", ru:"две недели", ex:"I'll be away for a fortnight." },
    { id:"v4-A2-174", en:"date", ru:"дата", ex:"What's the date today?" },
    { id:"v4-A2-175", en:"quarter", ru:"четверть", ex:"It's a quarter past nine." },
    { id:"v4-A2-176", en:"half", ru:"половина", ex:"I waited half an hour." },
    { id:"v4-A2-177", en:"dozen", ru:"дюжина", ex:"I bought a dozen eggs." },
    { id:"v4-A2-178", en:"early", ru:"рано", ex:"She always arrives early." },
    { id:"v4-A2-179", en:"recently", ru:"недавно", ex:"I saw him recently at the cafe." },
    { id:"v4-A2-180", en:"soon", ru:"скоро", ex:"The train will arrive soon." },

    // === Праздники / события ===
    { id:"v4-A2-181", en:"celebration", ru:"празднование", ex:"The celebration lasted all night." },
    { id:"v4-A2-182", en:"to celebrate", ru:"праздновать", ex:"We celebrate New Year with family." },
    { id:"v4-A2-183", en:"gift", ru:"подарок", ex:"She gave me a lovely gift." },
    { id:"v4-A2-184", en:"to invite", ru:"приглашать", ex:"They invited us to the wedding." },
    { id:"v4-A2-185", en:"fireworks", ru:"фейерверк", ex:"We watched the fireworks at night." },
    { id:"v4-A2-186", en:"anniversary", ru:"годовщина", ex:"It's their tenth wedding anniversary." },
    { id:"v4-A2-187", en:"to decorate", ru:"украшать", ex:"We decorate the house for the holiday." },
    { id:"v4-A2-188", en:"ceremony", ru:"церемония", ex:"The ceremony starts at noon." },

    // === Технологии быта ===
    { id:"v4-A2-189", en:"charger", ru:"зарядное устройство", ex:"I forgot my phone charger at home." },
    { id:"v4-A2-190", en:"screen", ru:"экран", ex:"The screen on my laptop is broken." },
    { id:"v4-A2-191", en:"to download", ru:"скачивать", ex:"I'll download the app tonight." },
    { id:"v4-A2-192", en:"to switch off", ru:"выключать", ex:"Switch off the TV before bed." },
    { id:"v4-A2-193", en:"keyboard", ru:"клавиатура", ex:"This keyboard is easy to type on." },
    { id:"v4-A2-194", en:"battery", ru:"батарея / аккумулятор", ex:"My phone battery is almost dead." },

    // === Прилагательные-описания ===
    { id:"v4-A2-195", en:"narrow", ru:"узкий", ex:"The street is too narrow for cars." },
    { id:"v4-A2-196", en:"heavy", ru:"тяжёлый", ex:"This box is very heavy." },
    { id:"v4-A2-197", en:"empty", ru:"пустой", ex:"The bottle is empty." },
    { id:"v4-A2-198", en:"comfortable", ru:"удобный", ex:"This chair is very comfortable." },
    { id:"v4-A2-199", en:"dangerous", ru:"опасный", ex:"It is dangerous to swim here." },
    { id:"v4-A2-200", en:"useful", ru:"полезный", ex:"This tool is very useful." }
  ]);
})();
