(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P = (track,lvl,arr)=>{C[track]=C[track]||{};C[track][lvl]=C[track][lvl]||[];arr.forEach(x=>C[track][lvl].push(x));};
  P("vocab","C1",[
    { id:"v3-C1-01", en:"to elucidate", ru:"прояснять, разъяснять", ex:"The author elucidates a complex theory in remarkably accessible terms." },
    { id:"v3-C1-02", en:"to underscore", ru:"подчёркивать, акцентировать", ex:"The findings underscore the urgent need for structural reform." },
    { id:"v3-C1-03", en:"to corroborate", ru:"подтверждать, подкреплять (доказательствами)", ex:"Independent studies corroborate the original hypothesis." },
    { id:"v3-C1-04", en:"to substantiate", ru:"обосновывать, подтверждать", ex:"The claim is not substantiated by any reliable evidence." },
    { id:"v3-C1-05", en:"to delineate", ru:"очерчивать, чётко определять", ex:"The report delineates the boundaries between the two jurisdictions." },
    { id:"v3-C1-06", en:"to mitigate", ru:"смягчать, уменьшать (последствия)", ex:"New regulations were introduced to mitigate the environmental impact." },
    { id:"v3-C1-07", en:"to exacerbate", ru:"усугублять, обострять", ex:"Austerity measures only exacerbated the recession." },
    { id:"v3-C1-08", en:"to undermine", ru:"подрывать, ослаблять", ex:"Persistent corruption undermines public trust in institutions." },
    { id:"v3-C1-09", en:"to reconcile", ru:"примирять, согласовывать", ex:"It is difficult to reconcile these conflicting accounts of the event." },
    { id:"v3-C1-10", en:"to constitute", ru:"составлять, представлять собой", ex:"Such behaviour constitutes a serious breach of contract." },
    { id:"v3-C1-11", en:"to encompass", ru:"охватывать, включать в себя", ex:"The survey encompasses a broad range of socioeconomic factors." },
    { id:"v3-C1-12", en:"to attribute (to)", ru:"приписывать, относить (к причине)", ex:"Economists attribute the slowdown to weak consumer demand." },
    { id:"v3-C1-13", en:"to discern", ru:"различать, распознавать", ex:"It is hard to discern a clear pattern in the fragmented data." },
    { id:"v3-C1-14", en:"to advocate (for)", ru:"выступать в защиту, отстаивать", ex:"The committee advocates a more cautious approach to deregulation." },
    { id:"v3-C1-15", en:"to scrutinise", ru:"тщательно изучать, придирчиво проверять", ex:"Regulators scrutinise every transaction above the threshold." },
    { id:"v3-C1-16", en:"to extrapolate", ru:"экстраполировать, прогнозировать по данным", ex:"One should be cautious about extrapolating from such a small sample." },
    { id:"v3-C1-17", en:"to perpetuate", ru:"увековечивать, закреплять", ex:"Stereotypes in the media perpetuate harmful assumptions." },
    { id:"v3-C1-18", en:"to alleviate", ru:"облегчать, смягчать (страдания)", ex:"The programme aims to alleviate poverty in rural regions." },
    { id:"v3-C1-19", en:"to consolidate", ru:"укреплять, консолидировать", ex:"The firm consolidated its position as the market leader." },
    { id:"v3-C1-20", en:"to facilitate", ru:"способствовать, облегчать", ex:"Digital platforms facilitate cross-border collaboration." },
    { id:"v3-C1-21", en:"to relinquish", ru:"отказываться, уступать (права)", ex:"He was reluctant to relinquish control of the family business." },
    { id:"v3-C1-22", en:"to circumvent", ru:"обходить (правила, препятствия)", ex:"The scheme was designed to circumvent existing tax regulations." },
    { id:"v3-C1-23", en:"to galvanise", ru:"побуждать к действию, мобилизовать", ex:"The crisis galvanised public support for renewable energy." },
    { id:"v3-C1-24", en:"to permeate", ru:"пронизывать, проникать повсюду", ex:"A sense of optimism permeated the entire organisation." },
    { id:"v3-C1-25", en:"to oscillate", ru:"колебаться (между состояниями)", ex:"Public opinion oscillated between hope and scepticism." },
    { id:"v3-C1-26", en:"to converge", ru:"сходиться, сближаться", ex:"The two research traditions have gradually begun to converge." },
    { id:"v3-C1-27", en:"to diverge", ru:"расходиться, отклоняться", ex:"Their conclusions diverge sharply on the question of causation." },
    { id:"v3-C1-28", en:"to culminate (in)", ru:"достигать кульминации, завершаться", ex:"Years of negotiation culminated in a landmark agreement." },
    { id:"v3-C1-29", en:"to precipitate", ru:"ускорять, провоцировать (событие)", ex:"The bank's collapse precipitated a wider financial crisis." },
    { id:"v3-C1-30", en:"to engender", ru:"порождать, вызывать", ex:"Transparency tends to engender greater trust among stakeholders." },
    { id:"v3-C1-31", en:"implication", ru:"следствие, скрытый смысл", ex:"The policy carries far-reaching implications for small businesses." },
    { id:"v3-C1-32", en:"discrepancy", ru:"расхождение, несоответствие", ex:"A significant discrepancy emerged between the projected and actual figures." },
    { id:"v3-C1-33", en:"premise", ru:"посылка, исходное допущение", ex:"The argument rests on a questionable premise." },
    { id:"v3-C1-34", en:"paradigm", ru:"парадигма, образец", ex:"The discovery prompted a shift in the dominant scientific paradigm." },
    { id:"v3-C1-35", en:"nuance", ru:"нюанс, тонкое различие", ex:"The translation fails to capture the nuances of the original text." },
    { id:"v3-C1-36", en:"correlation", ru:"корреляция, взаимосвязь", ex:"There is a strong correlation between education and income." },
    { id:"v3-C1-37", en:"causation", ru:"причинность, причинно-следственная связь", ex:"Correlation does not necessarily imply causation." },
    { id:"v3-C1-38", en:"prevalence", ru:"распространённость, преобладание", ex:"The study examines the prevalence of chronic illness among the elderly." },
    { id:"v3-C1-39", en:"threshold", ru:"порог, предельное значение", ex:"Income above a certain threshold is taxed at a higher rate." },
    { id:"v3-C1-40", en:"trajectory", ru:"траектория, путь развития", ex:"The country's economic trajectory remains highly uncertain." },
    { id:"v3-C1-41", en:"ramification", ru:"последствие, разветвление", ex:"The decision has profound ramifications for future legislation." },
    { id:"v3-C1-42", en:"caveat", ru:"оговорка, предостережение", ex:"The recommendation comes with one important caveat." },
    { id:"v3-C1-43", en:"consensus", ru:"консенсус, общее согласие", ex:"There is a broad scientific consensus on the issue." },
    { id:"v3-C1-44", en:"discourse", ru:"дискурс, обсуждение", ex:"The book has reshaped public discourse on inequality." },
    { id:"v3-C1-45", en:"dichotomy", ru:"дихотомия, противопоставление", ex:"The author rejects the dichotomy between theory and practice." },
    { id:"v3-C1-46", en:"surge", ru:"всплеск, резкий рост", ex:"The sector saw a surge in investment last quarter." },
    { id:"v3-C1-47", en:"downturn", ru:"спад, ухудшение (экономики)", ex:"The downturn forced many firms to cut their workforce." },
    { id:"v3-C1-48", en:"volatility", ru:"волатильность, изменчивость", ex:"Market volatility deterred long-term investors." },
    { id:"v3-C1-49", en:"incentive", ru:"стимул, побуждение", ex:"Tax breaks provide a powerful incentive for innovation." },
    { id:"v3-C1-50", en:"constraint", ru:"ограничение, сдерживающий фактор", ex:"Budgetary constraints limited the scope of the project." },
    { id:"v3-C1-51", en:"to plummet", ru:"резко падать, обваливаться", ex:"Share prices plummeted following the announcement." },
    { id:"v3-C1-52", en:"to soar", ru:"стремительно расти, взлетать", ex:"Energy costs soared during the winter months." },
    { id:"v3-C1-53", en:"to taper off", ru:"постепенно снижаться, сходить на нет", ex:"Demand began to taper off towards the end of the year." },
    { id:"v3-C1-54", en:"to level off", ru:"стабилизироваться, выходить на плато", ex:"Inflation levelled off after a turbulent first quarter." },
    { id:"v3-C1-55", en:"to outpace", ru:"опережать, расти быстрее", ex:"Wages have failed to outpace the rising cost of living." },
    { id:"v3-C1-56", en:"a marked increase", ru:"заметное увеличение", ex:"There has been a marked increase in remote working." },
    { id:"v3-C1-57", en:"a steady decline", ru:"устойчивое снижение", ex:"The data reveal a steady decline in birth rates." },
    { id:"v3-C1-58", en:"a profound impact", ru:"глубокое воздействие", ex:"Automation has had a profound impact on the labour market." },
    { id:"v3-C1-59", en:"a compelling argument", ru:"убедительный довод", ex:"She made a compelling argument for fiscal restraint." },
    { id:"v3-C1-60", en:"a vested interest", ru:"кровный/корыстный интерес", ex:"The lobby has a vested interest in maintaining the status quo." },
    { id:"v3-C1-61", en:"to draw a distinction", ru:"проводить различие", ex:"It is vital to draw a distinction between correlation and causation." },
    { id:"v3-C1-62", en:"to pose a threat", ru:"представлять угрозу", ex:"Rising sea levels pose a serious threat to coastal cities." },
    { id:"v3-C1-63", en:"to gain traction", ru:"набирать популярность/обороты", ex:"The proposal is slowly gaining traction among lawmakers." },
    { id:"v3-C1-64", en:"to bear out", ru:"подтверждать (предположение)", ex:"The results bear out the researchers' initial predictions." },
    { id:"v3-C1-65", en:"notwithstanding", ru:"несмотря на, тем не менее", ex:"Notwithstanding these objections, the plan was approved." },
    { id:"v3-C1-66", en:"albeit", ru:"хотя и, пусть и", ex:"The recovery was real, albeit slower than anticipated." },
    { id:"v3-C1-67", en:"conversely", ru:"и наоборот, напротив", ex:"Conversely, smaller firms struggled to absorb the costs." },
    { id:"v3-C1-68", en:"insofar as", ru:"постольку, поскольку", ex:"The theory is valid insofar as the assumptions hold." },
    { id:"v3-C1-69", en:"by the same token", ru:"таким же образом, аналогично", ex:"By the same token, deregulation can heighten systemic risk." },
    { id:"v3-C1-70", en:"to that end", ru:"с этой целью, ради этого", ex:"To that end, the agency established a dedicated task force." },
    { id:"v3-C1-71", en:"in light of", ru:"в свете, учитывая", ex:"In light of recent events, the policy was reconsidered." },
    { id:"v3-C1-72", en:"to a large extent", ru:"в значительной степени", ex:"The outcome depends, to a large extent, on government policy." },
    { id:"v3-C1-73", en:"with respect to", ru:"в отношении, что касается", ex:"With respect to funding, no firm commitments were made." },
    { id:"v3-C1-74", en:"on the grounds that", ru:"на том основании, что", ex:"The appeal was rejected on the grounds that it lacked evidence." },
    { id:"v3-C1-75", en:"a watershed moment", ru:"переломный момент", ex:"The treaty marked a watershed moment in international relations." },
    { id:"v3-C1-76", en:"a double-edged sword", ru:"палка о двух концах", ex:"Automation is a double-edged sword for the workforce." },
    { id:"v3-C1-77", en:"to weigh up the pros and cons", ru:"взвешивать все за и против", ex:"Investors must weigh up the pros and cons before committing capital." },
    { id:"v3-C1-78", en:"unprecedented", ru:"беспрецедентный, небывалый", ex:"The pandemic disrupted supply chains on an unprecedented scale." },
    { id:"v3-C1-79", en:"viable", ru:"жизнеспособный, осуществимый", ex:"Renewable energy is now a commercially viable alternative." },
    { id:"v3-C1-80", en:"inherent", ru:"присущий, неотъемлемый", ex:"There are inherent risks in any speculative investment." }
  ]);
})();
