(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("reading","C1",[
    {
      id:"r4-C1-01",
      title:"The Limits of Reductionism",
      text:"For much of the twentieth century, the dominant assumption in the natural sciences was that any phenomenon, however intricate, could ultimately be understood by decomposing it into its constituent parts. This reductionist programme yielded spectacular triumphs, from the elucidation of the genetic code to the standard model of particle physics. Yet a growing chorus of theorists now contends that reductionism, for all its explanatory power, encounters principled limits when confronted with so-called emergent properties. Consciousness, the behaviour of markets, and the dynamics of ecosystems each exhibit characteristics that cannot be deduced straightforwardly from the properties of their components. Critics of the reductionist orthodoxy do not deny that wholes are composed of parts; rather, they insist that novel laws govern systems at higher levels of organisation, laws that are not reducible to those operating at lower levels. Defenders of reductionism counter that such talk of emergence merely reflects our present ignorance, and that with sufficient computational ingenuity even consciousness will eventually surrender to bottom-up explanation. The dispute, far from being a parochial squabble among philosophers, bears directly on how research is funded, conducted, and interpreted across disciplines as disparate as neuroscience and economics.",
      questions:[
        { q:"What does the passage identify as the central claim of reductionism?", options:["That complex phenomena can be understood by analysing their parts","That higher-level laws are irreducible","That consciousness cannot be explained"], answer:0 },
        { q:"How do critics of reductionism characterise emergent properties?", options:["As illusions produced by faulty instruments","As features not deducible from component properties","As identical to the properties of parts"], answer:1 },
        { q:"What do defenders of reductionism attribute appeals to emergence to?", options:["Deliberate obscurantism","Religious conviction","Current limits of our knowledge"], answer:2 },
        { q:"What does the author suggest about the significance of the debate?", options:["It has practical consequences for how research is conducted","It is confined to academic philosophy","It has already been resolved"], answer:0 }
      ]
    },
    {
      id:"r4-C1-02",
      title:"The Paradox of Choice",
      text:"Conventional economic theory holds that expanding the range of options available to consumers can only enhance their welfare, since a rational agent will simply ignore the alternatives that do not suit their preferences. A body of psychological research has, however, complicated this tidy picture. When confronted with an overabundance of choices, individuals frequently report greater anxiety, diminished satisfaction with whatever they eventually select, and in some cases a paralysis that leads them to defer the decision indefinitely. The phenomenon, sometimes termed choice overload, appears to stem from the cognitive burden of evaluating numerous options and the heightened expectation that, with so many possibilities at hand, the perfect outcome ought to be attainable. Subsequent failure to achieve perfection then breeds regret. Sceptics caution that the effect is fragile, surfacing only under particular conditions and dissolving when consumers are knowledgeable or genuinely care about the category in question. Nevertheless, the findings have prompted retailers and policymakers alike to reconsider the wisdom of relentlessly multiplying alternatives. Designing environments that curate rather than merely accumulate options may, paradoxically, serve human flourishing better than the unfettered abundance that classical economics celebrates as an unalloyed good.",
      questions:[
        { q:"What does classical economic theory predict about additional choices?", options:["They can only improve welfare","They invariably overwhelm consumers","They reduce rational behaviour"], answer:0 },
        { q:"According to the passage, what underlies choice overload?", options:["A lack of available information","The cognitive burden and inflated expectations","An absence of preferences"], answer:1 },
        { q:"What qualification do sceptics raise about the effect?", options:["It applies only to wealthy consumers","It has never been observed experimentally","It appears only under specific conditions"], answer:2 },
        { q:"What can be inferred about the author's view of abundant choice?", options:["It is always preferable to limitation","It may sometimes hinder rather than help","It is irrelevant to policy"], answer:1 }
      ]
    },
    {
      id:"r4-C1-03",
      title:"The Ethics of Algorithmic Decision-Making",
      text:"As institutions increasingly delegate consequential decisions to automated systems, from credit scoring to criminal sentencing, a thorny ethical terrain has come into view. Proponents argue that algorithms, unlike fallible human judges, are immune to the fatigue, prejudice, and inconsistency that plague human deliberation, and that they can process vast quantities of data with a uniformity no person could match. Yet the supposed neutrality of these systems has proven illusory. Because algorithms are trained on historical data, they tend to absorb and perpetuate the very biases embedded in the records on which they learn. A model trained on past hiring decisions may faithfully reproduce the discriminatory patterns of those decisions, all the while cloaking its judgements in the unimpeachable language of mathematics. Compounding the difficulty is the opacity of many sophisticated models, whose internal reasoning resists human interpretation, rendering accountability elusive. When an applicant is denied a loan, neither the applicant nor the institution may be able to articulate precisely why. The challenge facing regulators is therefore twofold: to ensure that automated systems do not entrench existing inequities, and to preserve a meaningful right to explanation in a world where decisions are increasingly made by machines whose logic eludes comprehension.",
      questions:[
        { q:"What advantage do proponents claim for algorithmic decision-making?", options:["It is cheaper than human labour","It avoids human fatigue, prejudice, and inconsistency","It is universally popular"], answer:1 },
        { q:"Why is the neutrality of algorithms described as illusory?", options:["They are deliberately programmed to discriminate","They absorb biases from historical training data","They cannot process large datasets"], answer:1 },
        { q:"What problem does the opacity of models create?", options:["It makes accountability difficult to achieve","It slows down computation","It increases the cost of training"], answer:0 },
        { q:"What twofold challenge does the passage attribute to regulators?", options:["Reducing costs and increasing speed","Preventing entrenched inequity and preserving a right to explanation","Banning algorithms and retraining workers"], answer:1 }
      ]
    },
    {
      id:"r4-C1-04",
      title:"Rewilding and Its Discontents",
      text:"Rewilding, the practice of restoring ecosystems by reintroducing species and allowing natural processes to reassert themselves with minimal human interference, has captured the imagination of conservationists weary of the painstaking management that traditional preservation demands. Advocates point to celebrated successes, such as the reintroduction of wolves to Yellowstone, which is said to have triggered a cascade of beneficial effects rippling through the food web and even altering the course of rivers. The vision is seductive: rather than micromanaging nature, humans step back and permit the land to heal itself. Critics, however, warn against romanticising a wilderness that may never have existed in the form rewilders imagine. Landscapes shaped by millennia of human activity cannot simply revert to some pristine baseline, and the reintroduction of large predators raises legitimate concerns among the rural communities who must live alongside them. Moreover, the notion that nature, left to its own devices, will reliably restore some desirable equilibrium rests on a contested ecological assumption. Ecosystems are dynamic and unpredictable, and the outcomes of removing human management are far from guaranteed. Rewilding thus crystallises a deeper question that haunts environmental thought: what exactly are we trying to restore, and whose vision of nature should prevail?",
      questions:[
        { q:"What does rewilding aim to do?", options:["Maximise agricultural yields","Restore ecosystems with minimal human interference","Eliminate all predator species"], answer:1 },
        { q:"What is cited as a celebrated rewilding success?", options:["The reintroduction of wolves to Yellowstone","The draining of wetlands","The planting of monoculture forests"], answer:0 },
        { q:"What concern do critics raise about the pristine baseline?", options:["That it is too expensive to achieve","That such a wilderness may never have existed as imagined","That it requires too many staff"], answer:1 },
        { q:"What deeper question does rewilding crystallise, according to the author?", options:["What we are restoring and whose vision should prevail","How to increase tourism revenue","Whether wolves are dangerous"], answer:0 }
      ]
    },
    {
      id:"r4-C1-05",
      title:"The Replication Crisis in Psychology",
      text:"A scientific finding is considered robust only if independent researchers, following the same procedures, can reproduce it. Over the past decade, a disquieting realisation has spread through the social sciences: a substantial proportion of published results, including many that had attained the status of textbook orthodoxy, cannot be replicated when subjected to rigorous retesting. The causes of this replication crisis are manifold. Researchers, under intense pressure to publish striking and novel results, may unwittingly engage in questionable practices, such as analysing data in numerous ways and reporting only the combination that yields a statistically significant outcome. Journals, for their part, have historically displayed a marked preference for positive findings, consigning unglamorous null results to oblivion and thereby distorting the published record. Small sample sizes further compound the problem, inflating the likelihood that any apparent effect is merely a statistical fluke. The crisis has, however, catalysed a salutary reckoning. Initiatives promoting the pre-registration of hypotheses, the sharing of data, and the publication of replications, regardless of their outcome, are gradually taking root. Far from signalling the bankruptcy of the discipline, the willingness to confront these failures may ultimately prove a mark of scientific maturity and self-correction.",
      questions:[
        { q:"What makes a scientific finding robust according to the passage?", options:["It is published in a prestigious journal","Independent researchers can reproduce it","It is statistically significant"], answer:1 },
        { q:"What questionable practice does the passage describe?", options:["Reporting only the analysis that yields significance","Fabricating data outright","Refusing to publish at all"], answer:0 },
        { q:"How have journals historically contributed to the crisis?", options:["By demanding excessively large samples","By favouring positive findings over null results","By rejecting all novel claims"], answer:1 },
        { q:"What is the author's overall attitude toward the crisis?", options:["It proves psychology is worthless","It is a sign of self-correction and maturity","It should be concealed from the public"], answer:1 }
      ]
    },
    {
      id:"r4-C1-06",
      title:"The Aesthetics of Imperfection",
      text:"In much of the Western tradition, beauty has been bound up with notions of symmetry, completeness, and the flawless execution of a preconceived ideal. The Japanese aesthetic sensibility known as wabi-sabi offers a striking counterpoint. Rooted in Zen Buddhist thought, it finds profundity precisely in what is impermanent, incomplete, and imperfect. A cracked tea bowl, repaired with a seam of gold rather than discarded, becomes more precious for bearing the visible history of its damage. An asymmetrical garden, a weathered timber, the faded patina of an old surface: these are esteemed not in spite of their irregularity but because of it. Underlying this sensibility is a meditation on transience, a recognition that all things are in flux and that the marks of age and use are not blemishes to be erased but testimonies to a life lived. Some commentators have suggested that wabi-sabi furnishes a quiet rebuke to the contemporary obsession with the new, the pristine, and the endlessly upgradeable. In a culture that prizes the seamless and the disposable, the patient appreciation of imperfection may carry not merely an aesthetic but an ethical and ecological charge, inviting us to cherish what we already possess rather than perpetually craving its replacement.",
      questions:[
        { q:"How does the Western tradition typically conceive of beauty, per the passage?", options:["As symmetry, completeness, and flawless execution","As irregularity and decay","As constant change"], answer:0 },
        { q:"What does the example of the repaired tea bowl illustrate?", options:["That damage diminishes value","That visible history can enhance preciousness","That gold is intrinsically valuable"], answer:1 },
        { q:"What idea underlies the wabi-sabi sensibility?", options:["A meditation on transience and flux","A preference for mass production","A rejection of all tradition"], answer:0 },
        { q:"What broader charge does the author suggest wabi-sabi may carry?", options:["An economic argument for luxury goods","An ethical and ecological appeal to cherish what we have","A political programme for reform"], answer:1 }
      ]
    },
    {
      id:"r4-C1-07",
      title:"The Tragedy of the Commons Revisited",
      text:"The metaphor of the tragedy of the commons, popularised in a famous essay, describes how a shared resource open to all is liable to be exhausted, since each individual, acting in their own rational self-interest, has an incentive to extract as much as possible while bearing only a fraction of the resulting cost. The grazing of cattle on common pasture, the depletion of fisheries, and the saturation of the atmosphere with greenhouse gases have all been invoked as illustrations. The bleak conclusion drawn by many is that only coercion, whether through state regulation or privatisation, can avert ruin. This pessimism, however, has been forcefully challenged. Extensive empirical research has documented numerous communities that have, over centuries, managed common resources sustainably without recourse either to central authority or to private ownership. Such arrangements typically rest on locally devised rules, mechanisms for monitoring compliance, graduated sanctions for transgressors, and trust accumulated through repeated interaction. The lesson is not that the tragedy is a fiction, but that it is not inevitable. Human beings are capable of crafting institutions of remarkable subtlety to govern their shared inheritance, provided the conditions that nurture cooperation are present and are not undermined by external interference.",
      questions:[
        { q:"What drives the tragedy of the commons?", options:["Government overregulation","Individuals extracting resources while bearing only part of the cost","A shortage of natural resources"], answer:1 },
        { q:"What bleak conclusion do many draw from the metaphor?", options:["That only coercion can prevent ruin","That commons are always sustainable","That cooperation is impossible"], answer:0 },
        { q:"What does empirical research reveal about commons?", options:["They are invariably destroyed","Communities can manage them sustainably without state or private ownership","They require advanced technology to survive"], answer:1 },
        { q:"What is the central lesson the author draws?", options:["The tragedy is a complete fiction","The tragedy is not inevitable given the right institutions","Privatisation is always the answer"], answer:1 }
      ]
    },
    {
      id:"r4-C1-08",
      title:"The Mismeasure of Intelligence",
      text:"Few concepts in psychology have proven as contentious as intelligence. The attempt to capture so multifaceted a human capacity in a single number has been both enormously influential and persistently controversial. Proponents of conventional intelligence testing argue that scores predict, with notable reliability, an array of outcomes ranging from academic achievement to occupational success, and that a general factor underlying diverse cognitive tasks does appear to exist. Detractors respond that such tests measure a narrow band of abilities, privileging the analytical and verbal skills cultivated by formal schooling while neglecting creativity, practical wisdom, emotional acuity, and the countless other faculties that distinguish flourishing lives. More troublingly, the history of intelligence testing is entangled with episodes in which its results were marshalled to justify the subordination of entire groups, lending a spurious scientific veneer to prejudice. Contemporary scholars increasingly favour pluralistic conceptions, framing intelligence not as a fixed quantity bestowed at birth but as a constellation of capacities shaped profoundly by environment, opportunity, and culture. Whether a single number can ever do justice to the richness of human cognition remains an open question, but the assumption that it straightforwardly can is one that few thoughtful observers are now prepared to defend.",
      questions:[
        { q:"What do proponents of intelligence testing emphasise?", options:["That scores predict various life outcomes","That tests measure all human abilities","That intelligence is fixed at birth"], answer:0 },
        { q:"What do detractors say such tests neglect?", options:["Mathematical reasoning only","Creativity, practical wisdom, and emotional acuity","Verbal and analytical skills"], answer:1 },
        { q:"Why is the history of intelligence testing described as troubling?", options:["Tests were too expensive to administer","Results were used to justify subordinating groups","Tests took too long to complete"], answer:1 },
        { q:"What conception of intelligence do contemporary scholars increasingly favour?", options:["A single fixed quantity given at birth","A pluralistic set of capacities shaped by environment","A purely genetic trait"], answer:1 }
      ]
    },
    {
      id:"r4-C1-09",
      title:"The Decline of Solitude",
      text:"Solitude, the deliberate withdrawal from the company of others, has long occupied an honoured place in human culture. Philosophers, mystics, artists, and scientists have repeatedly testified that their most fertile insights arrived not amid the clamour of social life but in the quiet of self-imposed seclusion. Yet the conditions favourable to genuine solitude have grown increasingly scarce. The proliferation of devices that tether us to a perpetual stream of notifications has rendered uninterrupted reflection a rare achievement rather than an ordinary occurrence. Even when physically alone, the modern individual is seldom truly unaccompanied, for the murmur of the connected world is never more than a glance away. Some thinkers warn that this erosion carries a hidden cost. The capacity to sit with one's own thoughts, to tolerate the discomfort of an unstimulated mind, and to forge convictions independent of the constant pressure of others' opinions may be atrophying. Solitude, on this view, is not loneliness, which is a deprivation, but a resource, the soil in which originality, moral courage, and a stable sense of self take root. To lose the habit of solitude may therefore be to lose something more consequential than mere peace and quiet.",
      questions:[
        { q:"How is solitude characterised in the passage?", options:["As a deprivation similar to loneliness","As a deliberate and valued withdrawal from others","As an involuntary state"], answer:1 },
        { q:"What has made genuine solitude scarce?", options:["The proliferation of devices and constant connectivity","A decline in personal living space","An increase in working hours"], answer:0 },
        { q:"What distinction does the author draw between solitude and loneliness?", options:["Solitude is a resource, loneliness a deprivation","They are essentially identical","Loneliness is chosen, solitude imposed"], answer:0 },
        { q:"What hidden cost do some thinkers warn about?", options:["A loss of physical health","The atrophy of independent thought and moral courage","A decline in social skills"], answer:1 }
      ]
    },
    {
      id:"r4-C1-10",
      title:"The Economics of Attention",
      text:"In an information economy, the scarce resource is no longer information itself, which exists in superabundance, but the finite human attention required to absorb it. This insight has profound implications for understanding the business models that dominate the digital landscape. Platforms that appear to offer their services at no charge are, in fact, engaged in a transaction of considerable subtlety: they furnish content and connection in exchange for the user's attention, which they then package and sell to advertisers. The user, far from being the customer, is closer to being the product. To maximise the attention they harvest, such platforms have powerful incentives to engineer their services for maximal engagement, deploying sophisticated techniques refined through relentless experimentation to keep users scrolling, clicking, and returning. Critics contend that this arrangement systematically rewards content that provokes strong emotional reactions, since outrage and indignation prove especially adhesive, while measured and nuanced material struggles to compete. The cumulative consequence, they argue, may be a coarsening of public discourse and a fragmenting of shared reality. Whether the attention economy can be reformed without dismantling the conveniences it has delivered remains one of the more vexing questions of the present age.",
      questions:[
        { q:"What is the scarce resource in an information economy?", options:["Information itself","Human attention","Advertising revenue"], answer:1 },
        { q:"What is the user's actual role on free platforms, per the passage?", options:["The customer being served","Closer to being the product","An unpaid employee"], answer:1 },
        { q:"Why do critics say engaging content tends to provoke strong emotions?", options:["Because users prefer calm material","Because outrage proves especially adhesive","Because advertisers demand it directly"], answer:1 },
        { q:"What cumulative consequence do critics fear?", options:["A coarsening of discourse and fragmenting of shared reality","A rise in subscription prices","A shortage of information"], answer:0 }
      ]
    },
    {
      id:"r4-C1-11",
      title:"The Problem of Moral Luck",
      text:"We ordinarily suppose that people can be held responsible only for what lies within their control, and that factors beyond their influence ought not to bear on our moral assessment of them. This intuition, however venerable, dissolves under scrutiny into a thicket of paradox, a difficulty philosophers have labelled moral luck. Consider two equally reckless drivers, identical in their negligence; one happens to strike a pedestrian who steps into the road, while the other, through sheer fortune, arrives home without incident. Both behaved identically, yet we are inclined to judge the first far more harshly, and the law will certainly treat him with greater severity. The element that distinguishes them is precisely a matter of luck, something neither could control, and yet it transforms our verdict. Examples of this kind suggest that our moral judgements are pervaded by factors we simultaneously believe to be irrelevant. The problem cannot be dismissed as a mere quirk of fallible intuition, for to expunge luck entirely from moral evaluation would require us to abandon judgements so deeply woven into ordinary life as to seem indispensable. We are left, uncomfortably, with two compelling principles that cannot both be true, and no obvious way to reconcile them.",
      questions:[
        { q:"What ordinary supposition does the passage begin with?", options:["That people are responsible only for what they control","That luck determines all outcomes","That morality is an illusion"], answer:0 },
        { q:"What distinguishes the two reckless drivers in the example?", options:["Their degree of negligence","A matter of luck beyond their control","Their knowledge of the law"], answer:1 },
        { q:"What does the example reveal about our moral judgements?", options:["They ignore all external factors","They are pervaded by factors we deem irrelevant","They are perfectly consistent"], answer:1 },
        { q:"What predicament does the author conclude with?", options:["Two compelling principles that cannot both be true","A clear solution to the paradox","Proof that luck is irrelevant"], answer:0 }
      ]
    },
    {
      id:"r4-C1-12",
      title:"Genetic Editing and the Question of Limits",
      text:"The advent of precise tools for editing the genome has thrust upon humanity a set of choices once confined to the realm of speculative fiction. The prospect of correcting the mutations responsible for devastating hereditary diseases offers a humanitarian promise difficult to dismiss. Yet the same techniques that might eliminate suffering could in principle be turned toward the enhancement of traits that have nothing to do with disease, raising the spectre of designed offspring selected for height, intelligence, or appearance according to the preferences of those who can afford the procedure. A particularly fraught distinction divides edits to ordinary body cells, whose effects perish with the individual, from edits to the germline, which would be transmitted to all subsequent generations. The latter amounts to a permanent alteration of the human inheritance, undertaken on behalf of descendants who cannot be consulted. Defenders of cautious progress argue that a blanket prohibition would consign future patients to needless suffering, while opponents fear that the boundary between therapy and enhancement will prove impossible to police, and that the wealthy will inevitably purchase advantages that entrench existing inequalities into the very biology of the species. The technology, in short, compels us to decide not merely what we can do but what kind of beings we wish to become.",
      questions:[
        { q:"What humanitarian promise does genome editing offer?", options:["Correcting mutations responsible for hereditary diseases","Increasing global food production","Extending human lifespan indefinitely"], answer:0 },
        { q:"What distinction is described as particularly fraught?", options:["Between cheap and expensive procedures","Between body-cell edits and heritable germline edits","Between plant and animal genetics"], answer:1 },
        { q:"Why is germline editing especially controversial?", options:["It is technically impossible","It permanently alters inheritance for unconsulted descendants","It has no medical benefit"], answer:1 },
        { q:"What broader concern do opponents raise about enhancement?", options:["That it will be too slow to develop","That the wealthy may entrench inequality in biology itself","That it will be banned worldwide"], answer:1 }
      ]
    },
    {
      id:"r4-C1-13",
      title:"The Myth of the Lone Genius",
      text:"Popular accounts of scientific and artistic achievement tend to gravitate toward the figure of the solitary genius, the singular mind whose flashes of inspiration, sprung seemingly from nowhere, reshape our understanding of the world. This narrative is undeniably appealing, for it lends drama to the often plodding reality of discovery and offers a comforting simplicity. Historians and sociologists of knowledge, however, have steadily eroded its foundations. Even the most celebrated breakthroughs, on closer inspection, turn out to be deeply embedded in collaborative networks, building upon the accumulated labour of countless predecessors and contemporaries whose contributions the heroic story conveniently obscures. The phenomenon of simultaneous and independent discovery, in which the same idea surfaces in several minds at once, suggests that ideas ripen when the surrounding intellectual conditions are right, rather than springing fully formed from an isolated brain. Recognising this does not diminish individual brilliance, but it relocates it within a web of relationships, instruments, institutions, and inherited concepts without which no genius could function. The myth of the lone genius persists partly because it flatters our craving for heroes, and partly because crediting a single name is administratively and commercially convenient, even when it does violence to the messy, communal truth of how knowledge actually advances.",
      questions:[
        { q:"Why is the lone-genius narrative appealing?", options:["It is supported by overwhelming evidence","It lends drama and offers comforting simplicity","It is recommended by historians"], answer:1 },
        { q:"What does the phenomenon of simultaneous discovery suggest?", options:["That ideas ripen when conditions are right","That only one person can ever have an idea","That collaboration is impossible"], answer:0 },
        { q:"What does recognising collaboration do to individual brilliance, per the author?", options:["It eliminates it entirely","It relocates it within a web of relationships","It proves it never existed"], answer:1 },
        { q:"Why does the myth persist, according to the passage?", options:["It flatters our craving for heroes and is convenient","It is the only accurate account","Scientists insist upon it"], answer:0 }
      ]
    },
    {
      id:"r4-C1-14",
      title:"Carbon Capture and the Allure of Technological Salvation",
      text:"As the urgency of curbing greenhouse gas emissions has become impossible to ignore, attention has turned to technologies capable of removing carbon dioxide directly from the atmosphere. The appeal is evident: rather than enduring the painful economic and behavioural changes that decarbonisation seems to demand, societies might engineer their way out of the predicament, scrubbing the air of the very pollutant that threatens them. Proponents envisage vast installations drawing down carbon at industrial scale, buying humanity time to transform its energy systems. Yet a chorus of sceptics urges caution. The technologies remain expensive and energy-intensive, and the quantities of carbon they would need to capture to make a meaningful difference are staggering, dwarfing anything yet achieved. More insidious, critics warn, is the moral hazard the prospect creates. The mere promise of a future technological fix may furnish a convenient excuse to defer the difficult work of reducing emissions now, on the comforting assumption that machines will eventually clean up the mess. In this way, an emergent technology that might prove a valuable supplement to mitigation risks becoming instead a rationalisation for inaction, allowing the present generation to discharge its conscience while bequeathing the problem to its successors.",
      questions:[
        { q:"What is the appeal of carbon-capture technology?", options:["Engineering a solution rather than enduring painful changes","Eliminating the need for energy entirely","Reducing the cost of fossil fuels"], answer:0 },
        { q:"What practical objection do sceptics raise?", options:["The technologies are too cheap to be trusted","The technologies are expensive and the required scale is staggering","The technologies have already failed completely"], answer:1 },
        { q:"What is the moral hazard the author describes?", options:["The promise of a fix may excuse deferring emissions cuts","Machines may become self-aware","Carbon capture may harm wildlife"], answer:0 },
        { q:"What does the author imply about the proper role of carbon capture?", options:["It should replace all mitigation efforts","It risks becoming a rationalisation for inaction rather than a supplement","It is wholly without value"], answer:1 }
      ]
    },
    {
      id:"r4-C1-15",
      title:"The Persistence of Superstition",
      text:"One might have expected that the relentless advance of scientific understanding would consign superstition to the museum of obsolete beliefs. The expectation has proven naive. Even individuals well versed in rational thought routinely knock on wood, avoid certain numbers, or carry talismans into situations whose outcomes they cannot control. Far from being a vestige of ignorance soon to be eradicated, superstition appears to answer a durable psychological need. Cognitive scientists suggest that the human mind is predisposed to detect patterns and agency even where none exist, a tendency that may once have conferred a survival advantage, since mistaking a rustle in the grass for a predator costs little, whereas the opposite error could prove fatal. Superstitions also flourish in conditions of uncertainty and high stakes, which helps explain their prevalence among athletes, gamblers, and others whose fortunes hinge on factors beyond their command. By performing a ritual, however objectively futile, the individual recovers a sense of agency and assuages anxiety. The persistence of such beliefs thus illuminates something fundamental about human cognition: we are not the dispassionate reasoning machines we sometimes imagine ourselves to be, but creatures who crave meaning and control, and who will manufacture both when the world declines to supply them.",
      questions:[
        { q:"What expectation does the passage describe as naive?", options:["That science would eliminate superstition","That superstition would increase over time","That rituals would become more elaborate"], answer:0 },
        { q:"Why might pattern-detection have conferred a survival advantage?", options:["It made humans more sociable","Mistaking a rustle for a predator costs little while the reverse is fatal","It improved memory"], answer:1 },
        { q:"Under what conditions do superstitions flourish?", options:["Conditions of certainty and low stakes","Conditions of uncertainty and high stakes","Conditions of complete control"], answer:1 },
        { q:"What does the persistence of superstition reveal about humans, per the author?", options:["That they are dispassionate reasoning machines","That they crave meaning and control and will manufacture both","That they are wholly irrational"], answer:1 }
      ]
    },
    {
      id:"r4-C1-16",
      title:"Universal Basic Income on Trial",
      text:"The proposal to furnish every citizen with an unconditional cash payment, irrespective of need or willingness to work, has migrated from the fringes of economic thought toward the centre of mainstream debate. Its advocates span an unusual political spectrum. Those on the left commend it as a bulwark against poverty and a recognition of work that the market fails to remunerate, while some on the right embrace it as a means of streamlining a sprawling welfare apparatus into a single elegant transfer. The looming displacement of labour by automation has lent the idea fresh impetus, for if machines render swathes of human work redundant, the conventional link between employment and income may require severing. Detractors, however, marshal formidable objections. The fiscal cost of any payment generous enough to live on would be immense, and funding it might necessitate either punishing taxation or the dismantling of existing programmes that target the most vulnerable more efficiently. A deeper worry concerns the psychological and social significance of work, which furnishes not only income but structure, purpose, and identity. Pilot schemes conducted in various jurisdictions have yielded encouraging but inconclusive results, and the experiments remain too limited in scale and duration to settle a question whose ramifications extend to the very foundations of the social contract.",
      questions:[
        { q:"Why does universal basic income attract support across the spectrum?", options:["The left sees a poverty bulwark, the right a streamlined welfare system","Everyone agrees on its precise design","It requires no funding"], answer:0 },
        { q:"What development has lent the idea fresh impetus?", options:["Rising birth rates","The displacement of labour by automation","Falling tax revenues"], answer:1 },
        { q:"What fiscal objection do detractors raise?", options:["The cost is negligible","Funding it might require punishing taxation or dismantling targeted programmes","It would generate excessive surpluses"], answer:1 },
        { q:"Why do pilot schemes fail to settle the question?", options:["They were never actually conducted","They are too limited in scale and duration","They produced uniformly negative results"], answer:1 }
      ]
    },
    {
      id:"r4-C1-17",
      title:"The Architecture of Memory",
      text:"Common intuition pictures memory as a kind of archive, a repository in which experiences are faithfully recorded and from which they may later be retrieved intact. Decades of research have dismantled this comforting image. Remembering, it transpires, is not a passive act of playback but an active and reconstructive process, in which the mind assembles a plausible rendition of the past from fragmentary traces, filling the inevitable gaps with inference, expectation, and the residue of subsequent experience. Each act of recollection subtly alters the memory itself, so that what we retrieve is shaped as much by who we are now as by what actually occurred. This malleability accounts for the unsettling ease with which false memories can be implanted, a finding with grave consequences for the reliability of eyewitness testimony, long regarded by courts as among the most persuasive forms of evidence. Confident, detailed, and sincere recollections may nonetheless be substantially mistaken. Yet the reconstructive character of memory is not a mere defect. The same flexibility that renders memory fallible also enables the mind to extract general lessons from particular episodes, to imagine futures by recombining elements of the past, and to weave the disparate moments of a life into a coherent narrative of the self.",
      questions:[
        { q:"What intuitive image of memory does the passage reject?", options:["Memory as an active reconstruction","Memory as a faithful archive of experiences","Memory as wholly unreliable"], answer:1 },
        { q:"What happens during each act of recollection?", options:["The memory is perfectly preserved","The memory is subtly altered","The memory is permanently erased"], answer:1 },
        { q:"What consequence does memory's malleability have for the courts?", options:["It makes eyewitness testimony potentially unreliable despite confidence","It makes all testimony inadmissible","It has no legal relevance"], answer:0 },
        { q:"What benefit does the author attribute to memory's reconstructive nature?", options:["It guarantees accuracy","It enables imagining futures and forming a coherent self-narrative","It prevents all forgetting"], answer:1 }
      ]
    },
    {
      id:"r4-C1-18",
      title:"The Value of Difficulty in Art",
      text:"There exists a longstanding suspicion of art that demands effort, an assumption that difficulty is a failure of communication, perhaps even a form of elitism designed to exclude the uninitiated. Why, the objection runs, should a poem, a symphony, or a novel withhold its meaning, when clarity and immediacy are surely virtues? Defenders of demanding art mount a vigorous reply. Some experiences, they contend, cannot be conveyed in readily digestible form without being falsified, for the very difficulty of the work enacts the complexity of what it seeks to express. A poem that resists paraphrase may do so because the truth it pursues is itself resistant to paraphrase. Moreover, the labour a challenging work exacts is not gratuitous but constitutive of its reward; the meaning won through struggle is held differently, and more deeply, than meaning handed over without resistance. There is a further consideration. A culture that prizes only the instantly accessible may gradually lose the capacity for the sustained attention that demanding art both requires and cultivates. To dismiss difficulty wholesale, then, is to risk impoverishing not merely our art but the very faculties through which the richest human experiences become available to us at all.",
      questions:[
        { q:"What suspicion of difficult art does the passage describe?", options:["That difficulty is a failure of communication or elitism","That difficulty is always intentional fraud","That difficulty makes art cheaper"], answer:0 },
        { q:"Why might a poem resist paraphrase, according to defenders?", options:["Because the poet is incompetent","Because the truth it pursues is itself resistant to paraphrase","Because paraphrase is illegal"], answer:1 },
        { q:"How does the author characterise the labour a difficult work demands?", options:["As gratuitous and pointless","As constitutive of its reward","As a sign of poor craftsmanship"], answer:1 },
        { q:"What further risk does dismissing difficulty pose?", options:["Losing the capacity for sustained attention","Making art too expensive","Reducing the number of artists"], answer:0 }
      ]
    },
    {
      id:"r4-C1-19",
      title:"The Globalisation of Taste",
      text:"As goods, images, and people circulate ever more freely across borders, a question has arisen about the fate of cultural distinctiveness. One influential view holds that globalisation is steadily homogenising the world, dissolving local particularities into a bland uniformity in which the same brands, films, and culinary chains greet the traveller in every metropolis. On this account, the rich diversity of human cultures is being eroded by the irresistible logic of markets that reward standardisation. A contrary reading, however, complicates this melancholy thesis. The flows of globalisation, it observes, do not merely overwrite local cultures but provoke them into creative response. Imported forms are seldom adopted wholesale; they are appropriated, reinterpreted, and fused with indigenous traditions to yield novel hybrids that belong wholly to neither source. Far from extinguishing difference, the encounter between cultures can generate it anew, as communities define themselves precisely through their distinctive reworking of shared materials. The truth, in all likelihood, resists either tidy verdict. Globalisation simultaneously erodes certain particularities and engenders others, and the cultural landscape it produces is neither the uniform monoculture feared by pessimists nor the flourishing diversity celebrated by optimists, but an unstable and endlessly shifting compound of the two.",
      questions:[
        { q:"What does the first view claim about globalisation?", options:["It homogenises the world into bland uniformity","It strengthens local cultures","It has no cultural effect"], answer:0 },
        { q:"How does the contrary reading describe the reception of imported forms?", options:["They are adopted wholesale and unchanged","They are appropriated and fused into novel hybrids","They are always rejected"], answer:1 },
        { q:"What does the encounter between cultures generate, per the second view?", options:["Only conflict","Difference anew rather than mere erasure","Total uniformity"], answer:1 },
        { q:"What conclusion does the author reach?", options:["The pessimists are entirely correct","The truth is an unstable compound of both views","Globalisation has stopped"], answer:1 }
      ]
    },
    {
      id:"r4-C1-20",
      title:"The Ethics of Future Generations",
      text:"Decisions taken today, concerning the climate, the depletion of resources, or the accumulation of debt, will reverberate through the lives of people not yet born. This obvious fact gives rise to a peculiarly intractable ethical problem, for the beings whose interests are at stake cannot represent themselves, cannot bargain, and cannot hold us to account. Conventional moral frameworks, forged largely to govern relations among contemporaries, strain when extended across the chasm of time. A further perplexity, sometimes called the non-identity problem, deepens the difficulty. The very policies we adopt will influence which individuals come to exist, so that a person born into a degraded world might have no grounds for complaint, since under any alternative policy that particular person would never have existed at all. How, then, can we wrong people by choosing a future in which they, rather than others, are born? Such puzzles can appear to license a comfortable indifference, yet most thinkers recoil from the conclusion that we owe nothing to posterity. The challenge is to articulate the basis of our obligations to those who will inherit the consequences of our choices, a basis robust enough to constrain a present generation perpetually tempted to spend its descendants' inheritance and leave them the bill.",
      questions:[
        { q:"Why are obligations to future generations described as intractable?", options:["Future people cannot represent themselves or hold us to account","Future people are too numerous to count","Future people have no interests"], answer:0 },
        { q:"What is the non-identity problem?", options:["Future people will all be identical","Our policies determine which individuals come to exist","Future people cannot be identified by name"], answer:1 },
        { q:"What conclusion might the puzzles seem to license?", options:["A comfortable indifference toward posterity","An obligation to maximise population","A ban on all resource use"], answer:0 },
        { q:"What do most thinkers do in response to that conclusion?", options:["Embrace it wholeheartedly","Recoil from the idea that we owe nothing to posterity","Ignore the problem entirely"], answer:1 }
      ]
    }
  ]);
})();
