(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P = (track,lvl,arr)=>{C[track]=C[track]||{};C[track][lvl]=C[track][lvl]||[];arr.forEach(x=>C[track][lvl].push(x));};
  P("reading","C2",[
    {
      id:"r3-C2-01",
      title:"The Tyranny of the Measurable",
      text:"A peculiar inversion governs the modern institution. We profess to value what matters most, yet in practice we esteem only what can be counted. The hospital that prides itself on compassion finds itself ranked by readmission rates; the university that aspires to cultivate wisdom is judged by graduate salaries. This is no accident of administration but a structural consequence of accountability itself, for to hold an organisation answerable is, almost inevitably, to demand evidence, and evidence tends to assume numerical form. The trouble is that the unmeasurable does not thereby cease to exist; it merely retreats from view, becoming a kind of dark matter exerting its influence unseen. A teacher who inspires a single pupil to a lifelong love of inquiry has accomplished something no metric will ever register, and which no audit will reward. Over time, the institution learns to optimise for the visible and to neglect the invisible, not from malice but from a quiet, cumulative drift of incentives. What begins as a tool of transparency hardens into an instrument of distortion. The deepest irony is that those who design such systems are frequently aware of their inadequacy, and yet feel powerless to resist, for to abandon measurement altogether seems to invite caprice and corruption. We are left, then, with a dilemma admitting no clean resolution, only the perpetual labour of judgement that no spreadsheet can discharge on our behalf.",
      questions:[
        { q:"What does the author imply by describing the unmeasurable as 'dark matter'?", options:["It continues to shape outcomes despite being absent from records","It is morally corrupt and should be eliminated","It can eventually be quantified with better tools"], answer:0 },
        { q:"The author attributes institutional distortion primarily to:", options:["The deliberate malice of administrators","A gradual accumulation of misaligned incentives","A lack of intelligence among system designers"], answer:1 },
        { q:"What is suggested about those who design measurement systems?", options:["They are oblivious to the systems' flaws","They recognise the flaws yet feel unable to abandon them","They profit knowingly from the distortion"], answer:1 },
        { q:"The closing sentence implies that the dilemma:", options:["Will be solved by future technology","Demands ongoing human judgement rather than a formula","Is exaggerated by critics of accountability"], answer:1 }
      ]
    },
    {
      id:"r3-C2-02",
      title:"On the Persistence of Ruins",
      text:"There is a particular melancholy that attaches to ruins, distinct from the grief we feel before fresh devastation. A building newly destroyed provokes outrage or sorrow, but a ruin matured by centuries elicits something gentler and more ambiguous, a contemplative pleasure that earlier ages dignified with the name of the sublime. The romantic traveller who lingered among broken columns was not mourning the dead so much as savouring the spectacle of time made visible. For a ruin is, in essence, a collaboration between human ambition and natural indifference, the one having raised the structure and the other having patiently unmade it. What survives is neither wholly artefact nor wholly landscape but a hybrid that resists the categories we usually impose. This ambiguity is precisely its appeal. A complete monument insists upon a single interpretation, declaring the intentions of its builders; a ruin, by contrast, throws those intentions open to doubt and invites the imagination to supply what is missing. We become, before a ruin, the unwitting collaborators in a final act of construction, completing in fancy what stone can no longer assert. Perhaps this explains why deliberate ruins, follies erected to appear ancient, so rarely move us. They counterfeit the form but not the substance, offering the appearance of duration without its costly accumulation of vanished time. Authenticity here is not a matter of materials but of the irreversible.",
      questions:[
        { q:"How does the author distinguish a ruin from fresh devastation?", options:["A ruin evokes a contemplative, ambiguous pleasure rather than outrage","A ruin causes deeper grief than recent destruction","A ruin provokes no emotional response at all"], answer:0 },
        { q:"A ruin is described as a 'collaboration' between:", options:["Past and present generations of builders","Human ambition and natural indifference","Architecture and religion"], answer:1 },
        { q:"Why does the author say ruins appeal to the imagination?", options:["They preserve the builders' intentions perfectly","Their incompleteness invites us to supply what is missing","They are easier to understand than whole monuments"], answer:1 },
        { q:"Why do deliberate 'follies' fail to move the author?", options:["They are built from inferior materials","They imitate the form of ruins without genuine accumulated time","They are too recent to be historically significant"], answer:1 }
      ]
    },
    {
      id:"r3-C2-03",
      title:"The Grammar of Birdsong",
      text:"For decades the songs of birds were treated by science as instinctive eruptions, automatic as the beating of a heart, expressive of nothing but the urgencies of mating and territory. Closer attention has overturned this complacent view. Certain species, it transpires, learn their songs much as children acquire speech, passing through a babbling phase of formless experimentation before settling into the conventions of their local dialect. Young birds raised in isolation produce only a degenerate version of the species song, while those exposed to a tutor reproduce its subtleties with fidelity. More provocatively, the songs themselves exhibit a syntax, an ordered combination of discrete elements whose sequence carries meaning that the elements alone do not possess. This is not language in the human sense, for it lacks the open-ended capacity to generate novel propositions about an unbounded world. Yet the discovery unsettles the comfortable boundary we have drawn around our own species. We had assumed that the rudiments of grammar, the recombination of meaningless units into meaningful wholes, were ours alone, a watershed separating us from the animal continuum. The birds suggest instead a gradient, with capacities we deemed uniquely human distributed, in fragments and approximations, across the tree of life. The lesson is humbling and clarifying at once. What makes us distinctive may be not the possession of some faculty utterly absent elsewhere, but the particular intensity with which a widely shared endowment has been elaborated in us.",
      questions:[
        { q:"What was the older scientific view of birdsong that the passage overturns?", options:["That it was a learned cultural tradition","That it was purely instinctive and devoid of acquired learning","That it possessed full human-like language"], answer:1 },
        { q:"What does the isolation experiment demonstrate?", options:["Birdsong is entirely genetically fixed","Exposure to a tutor is necessary for the song's full development","Birds prefer silence when raised alone"], answer:1 },
        { q:"Why is birdsong said not to be language 'in the human sense'?", options:["It lacks the open-ended power to express novel propositions","It contains no ordered sequence of elements","It is produced only during mating"], answer:0 },
        { q:"The author's concluding 'lesson' is that human distinctiveness lies in:", options:["Possessing a faculty wholly absent in other species","The intense elaboration of a broadly shared endowment","Our ability to teach songs to birds"], answer:1 }
      ]
    },
    {
      id:"r3-C2-04",
      title:"The Ethics of the Last Generation",
      text:"Imagine a generation that, through no catastrophe but sheer collective choice, simply declined to reproduce, so that humanity ended not in fire but in a quiet closing of the last door. Most people recoil from such a prospect, yet articulating why is surprisingly difficult. No individual would be harmed, for the unborn cannot be wronged by never existing; there would be no grieving survivors, no widowed planet conscious of its loss. The usual machinery of moral reasoning, which weighs benefits and harms to actual persons, finds nothing to grip. And yet the intuition that something immense would be lost persists, and demands to be honoured rather than dismissed as mere sentiment. Perhaps what such a scenario reveals is that our moral universe is not exhausted by obligations to existing individuals. We seem to feel a responsibility toward projects larger than any person, toward the continuation of inquiry, of art, of the very capacity for valuing that the universe, so far as we know, achieved only here. To extinguish that capacity would be to silence the only voice that ever asked whether anything mattered. This is not a duty owed to anyone in particular; it is, if it exists at all, a duty owed to value itself. The thought experiment thus serves less as a practical worry than as a mirror, showing us the strange and impersonal commitments that lie beneath our ordinary concern for one another.",
      questions:[
        { q:"Why does conventional moral reasoning struggle with this scenario?", options:["Because it harms too many people to calculate","Because no actual individual is harmed by never being born","Because the harm is purely economic"], answer:1 },
        { q:"The author argues that the persistent intuition of loss should be:", options:["Dismissed as irrational sentiment","Honoured as revealing something about morality","Resolved by encouraging reproduction"], answer:1 },
        { q:"What does the author suggest is uniquely lost if the capacity for valuing ends?", options:["The only known voice that asks whether anything matters","A large amount of accumulated wealth","The biological diversity of the planet"], answer:0 },
        { q:"The thought experiment functions chiefly as:", options:["A practical policy recommendation","A mirror exposing impersonal moral commitments","A prediction about humanity's future"], answer:1 }
      ]
    },
    {
      id:"r3-C2-05",
      title:"The Cartographer's Confession",
      text:"Every map is a lie that tells the truth. To render the curved and cluttered surface of the earth upon a flat sheet, the cartographer must distort, and the only question is which distortions to accept and which to refuse. A projection faithful to area betrays shape; one faithful to direction betrays distance; none can honour everything at once. The famous map that hangs in countless classrooms exaggerates the polar regions monstrously, so that an island near the pole appears to rival a continent near the equator, and generations have absorbed, without knowing it, a subtle geography of importance. This is the deeper deception, not the technical impossibility of perfect projection, which is forgivable, but the way distortions accrete meanings their makers never intended. A map is an argument disguised as a description. It selects what to include and what to omit, and these silences speak as loudly as the lines. The road appears; the footpath the road displaced does not. The new border is drawn with confident ink; the older allegiances it overruled dissolve into blankness. To read a map critically is therefore to read it as one reads any rhetoric, attending to its omissions, asking whose purposes it serves, and remembering always that the territory itself remains stubbornly indifferent to our representations of it. The most dangerous maps are the ones we have forgotten are maps at all.",
      questions:[
        { q:"What does the author mean by 'a lie that tells the truth'?", options:["Maps are always intentionally fraudulent","Maps must distort reality in order to represent it usefully","Maps cannot convey any truth"], answer:1 },
        { q:"The 'deeper deception' of maps is identified as:", options:["The technical impossibility of perfect projection","The way distortions acquire unintended meanings","The high cost of producing accurate maps"], answer:1 },
        { q:"Why does the author compare reading a map to reading rhetoric?", options:["Both require attention to omissions and underlying purposes","Both are forms of fiction","Both are usually inaccurate"], answer:0 },
        { q:"The final sentence warns that the most dangerous maps are those:", options:["Drawn by hand","We no longer recognise as maps","Used for navigation at sea"], answer:1 }
      ]
    },
    {
      id:"r3-C2-06",
      title:"The Vanishing Mediator",
      text:"History occasionally produces a figure or institution whose role is to dissolve itself, to make possible a transition and then disappear so completely that later observers scarcely register its existence. The sociologist who coined the phrase 'vanishing mediator' had in mind a religious sensibility that helped usher in a secular and commercial order, only to be discarded once that order could stand on its own feet. The pattern recurs across many domains. A scaffolding enables the construction of an arch and is removed once the stones support themselves; the scaffolding's contribution is total yet invisible in the finished structure. Such mediators pose a problem for any history written in terms of causes and effects, for they belong to neither the world they leave behind nor the world they bring into being, but to the unstable threshold between them. We are tempted to omit them, since they fit no enduring category, and in omitting them we render the great transitions of history more abrupt and inexplicable than they truly were. The lesson extends beyond scholarship. We ourselves, in our individual lives, often pass through convictions and commitments whose function was to carry us from one stable identity to another, and which we then abandon without gratitude, even with embarrassment. To honour the vanishing mediator is to acknowledge that what enabled our arrival need not, and often cannot, accompany us once we have arrived.",
      questions:[
        { q:"What defines a 'vanishing mediator'?", options:["A figure who enables a transition and then disappears","A historian who studies forgotten events","An institution that resists all change"], answer:0 },
        { q:"The scaffolding analogy illustrates that a mediator's contribution is:", options:["Permanent and clearly visible","Total yet invisible in the final result","Minor and easily replaceable"], answer:1 },
        { q:"Why do such mediators trouble cause-and-effect history?", options:["They belong to an unstable threshold between two worlds","They cause too many effects to trace","They never actually existed"], answer:0 },
        { q:"The personal lesson the author draws is that:", options:["We should cling to all our past convictions","What enabled our arrival often cannot accompany us afterward","Embarrassment about the past is always justified"], answer:1 }
      ]
    },
    {
      id:"r3-C2-07",
      title:"Silence and the Machine",
      text:"The composer who once seated an audience before a piano for several minutes during which no note was played intended no mere provocation, though provocation was certainly achieved. His proposition was that silence does not exist, that what we call silence is simply sound we have not yet learned to attend to, the rustle of programmes, the hum of the ventilation, the involuntary murmur of our own bodies. The piece, in this reading, was less a composition than a frame, a way of redirecting attention so that the ambient world might be heard as music. This gesture acquires a new and uneasy resonance in an age of pervasive machinery. The hum that the audience heard was, increasingly, the hum of devices, and the silence we now find hardest to achieve is not acoustic but informational, the absence of the incessant solicitation of our attention by systems engineered precisely to forestall it. To sit in genuine quiet has become a discipline rather than a default, an accomplishment requiring deliberate retreat. One wonders what the composer would have made of a world in which his lesson, that we should attend to what surrounds us, has been weaponised against us, our attention captured not by the contemplative noticing he prized but by an endless engineered novelty that permits no settling, no boredom, and thus, perhaps, no thought. The capacity to be unstimulated may prove the rarest luxury of the coming century.",
      questions:[
        { q:"What was the composer's central proposition about silence?", options:["Silence is the highest form of music","True silence does not exist; it is unattended sound","Silence should be avoided in performance"], answer:1 },
        { q:"The author reframes the piece as essentially:", options:["A frame redirecting attention to ambient sound","A protest against modern technology","A test of the audience's patience"], answer:0 },
        { q:"What 'new resonance' does the author find in the modern age?", options:["Machines have made concerts obsolete","The hardest silence is now informational, not acoustic","Audiences have grown more appreciative of quiet"], answer:1 },
        { q:"How has the composer's lesson supposedly been 'weaponised'?", options:["Our attention is captured by engineered novelty rather than contemplation","People now refuse to attend concerts","Silence has been outlawed in public spaces"], answer:0 }
      ]
    },
    {
      id:"r3-C2-08",
      title:"The Counterfeit and the Original",
      text:"A perfect forgery raises a question that the imperfect kind never could. If an imitation is indistinguishable from the original by any test we can devise, in what does the superiority of the original consist? The pigments are identical, the brushwork flawless, the canvas appropriately aged; an expert, shown the two without provenance, cannot tell them apart. Yet we feel, almost universally, that the genuine work possesses a value the copy lacks, and our task is to say what this value is without lapsing into superstition. The answer cannot lie in any perceptible property, for by hypothesis none distinguishes them. It must lie instead in history, in the relation each object bears to the moment of its making. The original was the site of a creative act; it was where the artist's intention met resistance and was realised. The copy, however accomplished, merely traces the outcome of that struggle without having undergone it. To value the original is thus to value not an appearance but an event, and to insist that objects are not exhausted by how they look but are constituted also by where they come from. This insight reaches beyond the gallery. It suggests that authenticity is everywhere a matter of lineage rather than appearance, and that a culture able to reproduce any surface flawlessly may find itself peculiarly anxious about the depths that surfaces conceal.",
      questions:[
        { q:"What special question does a perfect forgery raise?", options:["How to detect it using better technology","Wherein the original's superiority lies if it is imperceptible","Whether forgery should be legal"], answer:1 },
        { q:"The author locates the original's value in:", options:["Its superior physical materials","Its history and relation to the creative act","Its higher market price"], answer:1 },
        { q:"To value the original is described as valuing:", options:["An appearance rather than an event","An event rather than a mere appearance","The skill of the forger"], answer:1 },
        { q:"What broader cultural anxiety does the author foresee?", options:["A culture that can copy any surface grows anxious about hidden depths","People will stop visiting galleries","Originals will become physically indistinguishable from forgeries"], answer:0 }
      ]
    },
    {
      id:"r3-C2-09",
      title:"The Burden of Indifference",
      text:"It is commonly assumed that the opposite of love is hatred, but reflection suggests a less obvious candidate. Hatred, after all, is a form of attention, an acknowledgement that its object matters enough to be opposed. The person we hate occupies our thoughts, disturbs our sleep, shapes our conduct; in hating, we remain bound to them by a perverse intimacy. Indifference severs even this bond. To be regarded with indifference is to be denied not merely affection but significance itself, to be treated as though one's existence made no perceptible difference to the world. This is why the gravest cruelties are often perpetrated not by the passionate but by the bureaucratically detached, those for whom their victims have become items rather than persons, entries to be processed rather than faces to be met. The machinery of large-scale harm runs not on hatred, which is exhausting and difficult to sustain, but on indifference, which requires no effort at all and can be maintained indefinitely. If this is so, then the cultivation of attention, the deliberate refusal to let others fade into the background of our concern, may be a more fundamental moral achievement than the suppression of hostile feeling. To notice is already to begin to care, and to care is to make oneself vulnerable to claims one might prefer to ignore.",
      questions:[
        { q:"Why does the author argue hatred is closer to love than indifference is?", options:["Both hatred and love involve sustained attention to their object","Hatred and love feel physically similar","Both are easy to maintain"], answer:0 },
        { q:"Indifference is described as denying its object:", options:["Only affection","Significance and acknowledgement of mattering","Physical safety alone"], answer:1 },
        { q:"According to the passage, large-scale harm typically runs on:", options:["Intense and exhausting hatred","Detached indifference requiring no effort","Misguided love"], answer:1 },
        { q:"The author implies that the key moral achievement is:", options:["Suppressing all hostile emotion","Cultivating attention and refusing to let others fade","Avoiding emotional involvement entirely"], answer:1 }
      ]
    },
    {
      id:"r3-C2-10",
      title:"The Recursive Mind",
      text:"What permits a being to reflect upon its own reflecting, to hold its own thoughts as objects of further thought? This recursive capacity, the mind turning upon itself, may be the quiet engine behind the more conspicuous achievements we celebrate. Mathematics is recursion made explicit, a tower of abstractions each resting upon the one below; grammar embeds clause within clause without evident limit; and morality itself depends upon our ability to imagine how our actions appear from a standpoint not our own, and then to judge that imagining in turn. Yet recursion exacts a price seldom acknowledged. The same faculty that lets us examine our beliefs lets us doubt them; the same detachment that yields self-knowledge yields also self-estrangement, the uncanny sensation of being a stranger to oneself. The creature that can ask whether its desires are worth having has opened a door that cannot be closed, for no answer it reaches is immune from the further question of whether that answer, too, is worth accepting. There is no final level at which reflection comes to rest, no vantage exempt from being itself surveyed. Some have seen in this an infinite freedom, the refusal of any given identity as final; others have seen a peculiar torment, the impossibility of simple, unselfconscious being. Both, perhaps, are right. The recursive mind is at once our glory and our affliction, and we possess no instrument finer than itself with which to weigh the bargain.",
      questions:[
        { q:"What capacity does the passage identify as a 'quiet engine'?", options:["Memory of past events","Recursion, the mind reflecting on its own reflecting","Rapid calculation"], answer:1 },
        { q:"How is morality linked to recursion?", options:["It requires imagining and then judging an external standpoint","It depends on suppressing all reflection","It is unrelated to recursive thought"], answer:0 },
        { q:"The 'price' of recursion described by the author is:", options:["Reduced intelligence","Self-doubt and self-estrangement","Loss of memory"], answer:1 },
        { q:"Why is there 'no final level at which reflection comes to rest'?", options:["Any answer can itself be questioned further","The mind eventually grows too tired","Recursion is forbidden by logic"], answer:0 }
      ]
    },
    {
      id:"r3-C2-11",
      title:"Weather and the Limits of Knowing",
      text:"There is a humility built into the science of weather that the older, deterministic sciences never had to learn. The mathematician who first noticed that minute differences in initial conditions could swell into vast divergences of outcome had stumbled upon a boundary that no increase in computational power could ever erase. It was not that our instruments were too crude or our equations too simple; it was that the system itself amplified uncertainty without limit, so that a forecast reaching far enough into the future was not merely difficult but, in principle, impossible. This discovery dealt a quiet blow to a dream that had animated science since its origins, the dream of a universe transparent to a sufficiently powerful intellect, every future state deducible from a complete description of the present. The dream had always conceded that we were ignorant; it had never conceded that ignorance might be structural, woven into the fabric of certain systems rather than reflecting a remediable deficiency in us. What chaos revealed was a third category between the knowable and the random, a realm governed by perfectly deterministic laws yet practically unpredictable, lawful in essence and unforeseeable in effect. To inhabit such a world is to relinquish a certain fantasy of mastery and to accept instead a posture of attentive provisionality, forecasting bravely but briefly, acting decisively while holding our predictions loosely, and finding, perhaps, a strange liberation in the discovery that not even God's calculator could tell us with certainty what tomorrow's sky will hold.",
      questions:[
        { q:"What boundary did the mathematician discover?", options:["A limit that more computing power could eventually overcome","An in-principle limit caused by the system amplifying uncertainty","A flaw in measuring instruments"], answer:1 },
        { q:"What 'dream' did the discovery undermine?", options:["The dream of a universe fully deducible by a powerful intellect","The dream of faster computers","The dream of controlling the weather directly"], answer:0 },
        { q:"The 'third category' the author describes is best summarised as:", options:["Systems that are both random and lawless","Systems that are deterministic in law yet practically unpredictable","Systems that are entirely knowable"], answer:1 },
        { q:"What posture does the author recommend in such a world?", options:["Abandoning forecasting altogether","Attentive provisionality, acting decisively while holding predictions loosely","Demanding certainty before acting"], answer:1 }
      ]
    },
    {
      id:"r3-C2-12",
      title:"The Afterlife of Languages",
      text:"When a language ceases to be spoken, what exactly dies? The romantic answer speaks of a unique vision of the world, a way of carving reality at joints no other tongue perceives, lost forever when the last speaker falls silent. There is truth in this, though it is easily sentimentalised. Languages do encode distinctions their neighbours lack, finer gradations of kinship, of colour, of evidential certainty, of the relation between speaker and the source of a claim. To lose a language is to lose not merely a vocabulary but a sedimented intelligence, the accumulated discriminations of generations who found certain features of experience worth marking. Yet the sterner truth is that languages rarely die of natural causes. They are, far more often, abandoned under duress, surrendered by communities who learn that the language of their ancestors is a liability in a world organised around other tongues, an obstacle to advancement, even a mark of shame deliberately instilled. The death of a language is thus seldom a tragedy of nature and almost always a symptom of power, the quiet residue of conquests and humiliations whose grosser violences have long since faded from memory. To mourn a vanished language without attending to the asymmetries that doomed it is to indulge in a melancholy that conveniently forgets its own causes, weeping over the corpse while ignoring the hand that held the knife.",
      questions:[
        { q:"What does the author say is lost beyond vocabulary when a language dies?", options:["Nothing of real consequence","A sedimented intelligence of accumulated distinctions","Only the ability to read old texts"], answer:1 },
        { q:"The author cautions that the 'romantic answer' is:", options:["Entirely false","True but easily sentimentalised","Irrelevant to linguistics"], answer:1 },
        { q:"What is the 'sterner truth' about how languages usually die?", options:["They die of natural evolutionary causes","They are abandoned under duress linked to power","They are deliberately destroyed by linguists"], answer:1 },
        { q:"The final image of 'the hand that held the knife' implies that mourners should:", options:["Avoid studying dead languages","Attend to the power asymmetries that caused the loss","Focus only on preserving vocabulary"], answer:1 }
      ]
    }
  ]);
})();
