(() => { const C = window.CONTENT || (window.CONTENT = {});
  const P=(t,l,a)=>{C[t]=C[t]||{};C[t][l]=C[t][l]||[];a.forEach(x=>C[t][l].push(x));};
  P("vocab","C1",[
    { id:"v4-C1-01", en:"elucidate", ru:"разъяснять, проливать свет", ex:"The author elucidates a complex theory with remarkable clarity." },
    { id:"v4-C1-02", en:"corroborate", ru:"подтверждать (доказательствами)", ex:"Independent studies corroborate the original findings." },
    { id:"v4-C1-03", en:"delineate", ru:"очерчивать, обозначать", ex:"The report delineates the boundaries of the proposed reform." },
    { id:"v4-C1-04", en:"substantiate", ru:"обосновывать, доказывать", ex:"The claim cannot be accepted unless it is properly substantiated." },
    { id:"v4-C1-05", en:"underpin", ru:"лежать в основе, подкреплять", ex:"Several assumptions underpin this economic model." },
    { id:"v4-C1-06", en:"posit", ru:"постулировать, выдвигать (тезис)", ex:"The philosopher posits that consciousness is irreducible." },
    { id:"v4-C1-07", en:"reconcile", ru:"примирять, согласовывать", ex:"It is difficult to reconcile these two conflicting accounts." },
    { id:"v4-C1-08", en:"extrapolate", ru:"экстраполировать", ex:"We should be cautious about extrapolating from such a small sample." },
    { id:"v4-C1-09", en:"discern", ru:"различать, распознавать", ex:"It is hard to discern any clear pattern in the data." },
    { id:"v4-C1-10", en:"contend", ru:"утверждать, отстаивать", ex:"Critics contend that the policy is fundamentally flawed." },
    { id:"v4-C1-11", en:"refute", ru:"опровергать", ex:"The new evidence effectively refutes the earlier hypothesis." },
    { id:"v4-C1-12", en:"epitomize", ru:"воплощать, быть образцом", ex:"This building epitomizes the architectural ideals of the era." },
    { id:"v4-C1-13", en:"engender", ru:"порождать, вызывать", ex:"Such measures may engender resentment among employees." },
    { id:"v4-C1-14", en:"precipitate", ru:"ускорять, провоцировать", ex:"The decision precipitated a wave of resignations." },
    { id:"v4-C1-15", en:"mitigate", ru:"смягчать, уменьшать", ex:"Reforestation can help mitigate the effects of climate change." },
    { id:"v4-C1-16", en:"exacerbate", ru:"усугублять, обострять", ex:"Austerity measures exacerbated the social crisis." },
    { id:"v4-C1-17", en:"attenuate", ru:"ослаблять, смягчать", ex:"Regulation may attenuate but not eliminate the risk." },
    { id:"v4-C1-18", en:"facilitate", ru:"способствовать, облегчать", ex:"Digital tools facilitate collaboration across borders." },
    { id:"v4-C1-19", en:"constitute", ru:"составлять, представлять собой", ex:"These factors collectively constitute a serious threat." },
    { id:"v4-C1-20", en:"encompass", ru:"охватывать, включать", ex:"The framework encompasses both legal and ethical dimensions." },
    { id:"v4-C1-21", en:"culminate in", ru:"завершаться, достигать кульминации", ex:"Years of negotiation culminated in a historic agreement." },
    { id:"v4-C1-22", en:"give rise to", ru:"приводить к, порождать", ex:"Industrialisation gave rise to new social classes." },
    { id:"v4-C1-23", en:"account for", ru:"объяснять; составлять (долю)", ex:"This sector accounts for nearly half of national exports." },
    { id:"v4-C1-24", en:"hinge on", ru:"зависеть от, держаться на", ex:"The whole argument hinges on a single questionable premise." },
    { id:"v4-C1-25", en:"stem from", ru:"проистекать из", ex:"Many of these problems stem from inadequate funding." },
    { id:"v4-C1-26", en:"ramification", ru:"последствие, разветвление", ex:"The legal ramifications of the ruling are far-reaching." },
    { id:"v4-C1-27", en:"premise", ru:"предпосылка, посылка", ex:"The conclusion follows logically from the initial premise." },
    { id:"v4-C1-28", en:"paradigm", ru:"парадигма, образец", ex:"The discovery prompted a paradigm shift in the field." },
    { id:"v4-C1-29", en:"nuance", ru:"нюанс, оттенок", ex:"The translation fails to capture the nuances of the original." },
    { id:"v4-C1-30", en:"discrepancy", ru:"расхождение, несоответствие", ex:"There is a notable discrepancy between theory and practice." },
    { id:"v4-C1-31", en:"caveat", ru:"оговорка, предостережение", ex:"The findings come with an important caveat about sample size." },
    { id:"v4-C1-32", en:"premise", ru:"исходное допущение", ex:"His entire case rests on a flawed premise." },
    { id:"v4-C1-33", en:"corollary", ru:"следствие, вывод", ex:"A natural corollary of the theory is increased uncertainty." },
    { id:"v4-C1-34", en:"dichotomy", ru:"дихотомия, противопоставление", ex:"The dichotomy between nature and nurture is overly simplistic." },
    { id:"v4-C1-35", en:"juxtaposition", ru:"сопоставление, соседство", ex:"The juxtaposition of wealth and poverty is striking." },
    { id:"v4-C1-36", en:"proponent", ru:"сторонник, защитник (идеи)", ex:"Proponents of the reform cite improved efficiency." },
    { id:"v4-C1-37", en:"adversary", ru:"противник, оппонент", ex:"He treated every critic as a personal adversary." },
    { id:"v4-C1-38", en:"consensus", ru:"консенсус, единое мнение", ex:"There is broad scientific consensus on this point." },
    { id:"v4-C1-39", en:"premise", ru:"основание для суждения", ex:"We must scrutinise the premise before accepting the verdict." },
    { id:"v4-C1-40", en:"connotation", ru:"коннотация, подтекст", ex:"The word carries strongly negative connotations." },
    { id:"v4-C1-41", en:"notwithstanding", ru:"несмотря на", ex:"Notwithstanding these objections, the plan was approved." },
    { id:"v4-C1-42", en:"albeit", ru:"хотя и, пусть и", ex:"The results were positive, albeit modest." },
    { id:"v4-C1-43", en:"hitherto", ru:"до сих пор, доныне", ex:"The technique revealed details hitherto invisible." },
    { id:"v4-C1-44", en:"henceforth", ru:"впредь, отныне", ex:"Henceforth, all submissions must be made online." },
    { id:"v4-C1-45", en:"insofar as", ru:"постольку, поскольку", ex:"The model is useful insofar as it predicts behaviour." },
    { id:"v4-C1-46", en:"conversely", ru:"наоборот, и напротив", ex:"Conversely, lower taxes may stimulate investment." },
    { id:"v4-C1-47", en:"thereby", ru:"тем самым, таким образом", ex:"Costs were cut, thereby improving profitability." },
    { id:"v4-C1-48", en:"whereby", ru:"посредством чего, при котором", ex:"They devised a system whereby disputes are resolved quickly." },
    { id:"v4-C1-49", en:"in light of", ru:"в свете, ввиду", ex:"In light of recent events, the policy was revised." },
    { id:"v4-C1-50", en:"by virtue of", ru:"в силу, благодаря", ex:"She qualifies by virtue of her extensive experience." },
    { id:"v4-C1-51", en:"with respect to", ru:"что касается, в отношении", ex:"With respect to costs, the proposal is unrealistic." },
    { id:"v4-C1-52", en:"as a corollary", ru:"как следствие", ex:"As a corollary, demand for skilled labour will rise." },
    { id:"v4-C1-53", en:"to that end", ru:"с этой целью", ex:"To that end, a special committee was established." },
    { id:"v4-C1-54", en:"in essence", ru:"по сути, в сущности", ex:"In essence, the two arguments amount to the same thing." },
    { id:"v4-C1-55", en:"on balance", ru:"в целом, взвесив всё", ex:"On balance, the advantages outweigh the drawbacks." },
    { id:"v4-C1-56", en:"all things considered", ru:"с учётом всего", ex:"All things considered, the project was a success." },
    { id:"v4-C1-57", en:"to a certain extent", ru:"в известной степени", ex:"To a certain extent, the criticism is justified." },
    { id:"v4-C1-58", en:"for the most part", ru:"по большей части", ex:"For the most part, the reforms have been welcomed." },
    { id:"v4-C1-59", en:"in stark contrast", ru:"в резком контрасте", ex:"In stark contrast, rural areas saw little growth." },
    { id:"v4-C1-60", en:"more often than not", ru:"чаще всего", ex:"More often than not, the predictions proved accurate." },
    { id:"v4-C1-61", en:"ambiguity", ru:"двусмысленность, неоднозначность", ex:"The wording leaves room for considerable ambiguity." },
    { id:"v4-C1-62", en:"autonomy", ru:"автономия, самостоятельность", ex:"Employees value autonomy in how they organise their work." },
    { id:"v4-C1-63", en:"coherence", ru:"связность, согласованность", ex:"The essay lacks coherence between its sections." },
    { id:"v4-C1-64", en:"contingency", ru:"непредвиденное обстоятельство", ex:"The plan includes a contingency for budget overruns." },
    { id:"v4-C1-65", en:"credibility", ru:"достоверность, доверие", ex:"The scandal damaged the institution's credibility." },
    { id:"v4-C1-66", en:"disparity", ru:"неравенство, диспропорция", ex:"There is a growing disparity in income across regions." },
    { id:"v4-C1-67", en:"feasibility", ru:"осуществимость, реализуемость", ex:"A study assessed the feasibility of the merger." },
    { id:"v4-C1-68", en:"inception", ru:"возникновение, начало", ex:"The fund has tripled in size since its inception." },
    { id:"v4-C1-69", en:"legitimacy", ru:"легитимность, законность", ex:"The election restored the government's legitimacy." },
    { id:"v4-C1-70", en:"plausibility", ru:"правдоподобность", ex:"The theory's plausibility rests on untested assumptions." },
    { id:"v4-C1-71", en:"prevalence", ru:"распространённость", ex:"Researchers measured the prevalence of the condition." },
    { id:"v4-C1-72", en:"propensity", ru:"склонность, предрасположенность", ex:"Some investors show a propensity for excessive risk." },
    { id:"v4-C1-73", en:"resilience", ru:"устойчивость, жизнестойкость", ex:"The economy showed surprising resilience during the downturn." },
    { id:"v4-C1-74", en:"scarcity", ru:"дефицит, нехватка", ex:"Water scarcity threatens agriculture in the region." },
    { id:"v4-C1-75", en:"transparency", ru:"прозрачность, открытость", ex:"Voters are demanding greater transparency from officials." },
    { id:"v4-C1-76", en:"volatility", ru:"волатильность, нестабильность", ex:"Market volatility deterred long-term investment." },
    { id:"v4-C1-77", en:"viability", ru:"жизнеспособность", ex:"The financial viability of the venture is in doubt." },
    { id:"v4-C1-78", en:"adversity", ru:"невзгоды, трудности", ex:"She displayed remarkable composure in the face of adversity." },
    { id:"v4-C1-79", en:"intricacy", ru:"сложность, запутанность", ex:"Few fully grasp the intricacy of the tax system." },
    { id:"v4-C1-80", en:"susceptibility", ru:"подверженность, уязвимость", ex:"Stress increases susceptibility to illness." },
    { id:"v4-C1-81", en:"raise awareness", ru:"повышать осведомлённость", ex:"The campaign aims to raise awareness of mental health." },
    { id:"v4-C1-82", en:"draw a distinction", ru:"проводить различие", ex:"We must draw a distinction between cause and correlation." },
    { id:"v4-C1-83", en:"reach a consensus", ru:"достичь консенсуса", ex:"The committee eventually reached a consensus." },
    { id:"v4-C1-84", en:"pose a threat", ru:"представлять угрозу", ex:"Rising sea levels pose a serious threat to coastal cities." },
    { id:"v4-C1-85", en:"meet a demand", ru:"удовлетворять спрос", ex:"Production was scaled up to meet growing demand." },
    { id:"v4-C1-86", en:"play a pivotal role", ru:"играть ключевую роль", ex:"Technology plays a pivotal role in modern logistics." },
    { id:"v4-C1-87", en:"bear the brunt", ru:"принимать на себя основной удар", ex:"Low-income families bear the brunt of inflation." },
    { id:"v4-C1-88", en:"strike a balance", ru:"находить баланс", ex:"Policymakers must strike a balance between growth and equity." },
    { id:"v4-C1-89", en:"shed light on", ru:"проливать свет на", ex:"The study sheds light on a long-standing puzzle." },
    { id:"v4-C1-90", en:"lay the foundation", ru:"закладывать основу", ex:"These reforms laid the foundation for future growth." },
    { id:"v4-C1-91", en:"address an issue", ru:"решать проблему", ex:"The new law fails to address the underlying issue." },
    { id:"v4-C1-92", en:"yield results", ru:"приносить результаты", ex:"The strategy is finally beginning to yield results." },
    { id:"v4-C1-93", en:"undermine confidence", ru:"подрывать доверие", ex:"The leak undermined public confidence in the agency." },
    { id:"v4-C1-94", en:"exert influence", ru:"оказывать влияние", ex:"Lobbyists exert considerable influence over legislation." },
    { id:"v4-C1-95", en:"impose restrictions", ru:"вводить ограничения", ex:"The government imposed strict restrictions on imports." },
    { id:"v4-C1-96", en:"vested interest", ru:"корыстный/личный интерес", ex:"Some firms have a vested interest in maintaining the status quo." },
    { id:"v4-C1-97", en:"compelling evidence", ru:"убедительные доказательства", ex:"There is compelling evidence linking the two events." },
    { id:"v4-C1-98", en:"underlying cause", ru:"глубинная причина", ex:"The report identifies the underlying causes of unrest." },
    { id:"v4-C1-99", en:"far-reaching consequences", ru:"далеко идущие последствия", ex:"The decision had far-reaching consequences for the industry." },
    { id:"v4-C1-100", en:"sustained growth", ru:"устойчивый рост", ex:"The country enjoyed a decade of sustained growth." },
    { id:"v4-C1-101", en:"it is widely held that", ru:"широко распространено мнение, что", ex:"It is widely held that early intervention is most effective." },
    { id:"v4-C1-102", en:"a compelling case can be made", ru:"можно привести веские доводы", ex:"A compelling case can be made for stricter regulation." },
    { id:"v4-C1-103", en:"there is little doubt that", ru:"едва ли можно сомневаться, что", ex:"There is little doubt that the situation will worsen." },
    { id:"v4-C1-104", en:"this is borne out by", ru:"это подтверждается", ex:"This conclusion is borne out by recent surveys." },
    { id:"v4-C1-105", en:"it would be misleading to suggest", ru:"было бы ошибочно полагать", ex:"It would be misleading to suggest that growth is universal." },
    { id:"v4-C1-106", en:"by the same token", ru:"равным образом, точно так же", ex:"By the same token, lax oversight invites abuse." },
    { id:"v4-C1-107", en:"a case in point", ru:"показательный пример", ex:"A case in point is the collapse of the regional bank." },
    { id:"v4-C1-108", en:"this raises the question", ru:"это ставит вопрос", ex:"This raises the question of who bears responsibility." },
    { id:"v4-C1-109", en:"it follows that", ru:"из этого следует, что", ex:"It follows that the policy must be reconsidered." },
    { id:"v4-C1-110", en:"to put it another way", ru:"иначе говоря", ex:"To put it another way, the costs are simply unsustainable." },
    { id:"v4-C1-111", en:"a counterargument holds that", ru:"контраргумент гласит, что", ex:"A counterargument holds that regulation stifles innovation." },
    { id:"v4-C1-112", en:"on the one hand", ru:"с одной стороны", ex:"On the one hand, the plan is ambitious." },
    { id:"v4-C1-113", en:"granted that", ru:"допустим, что", ex:"Granted that resources are limited, priorities must be set." },
    { id:"v4-C1-114", en:"the crux of the matter", ru:"суть дела", ex:"The crux of the matter is a lack of accountability." },
    { id:"v4-C1-115", en:"weigh the evidence", ru:"взвешивать доказательства", ex:"The jury must carefully weigh the evidence." },
    { id:"v4-C1-116", en:"a tenuous link", ru:"слабая, шаткая связь", ex:"The study draws only a tenuous link between the variables." },
    { id:"v4-C1-117", en:"open to interpretation", ru:"допускающий разные толкования", ex:"The clause is unfortunately open to interpretation." },
    { id:"v4-C1-118", en:"the prevailing view", ru:"преобладающая точка зрения", ex:"The prevailing view favours gradual reform." },
    { id:"v4-C1-119", en:"a fundamental flaw", ru:"коренной недостаток", ex:"The methodology contains a fundamental flaw." },
    { id:"v4-C1-120", en:"beyond reasonable doubt", ru:"вне разумных сомнений", ex:"Guilt must be established beyond reasonable doubt." },
    { id:"v4-C1-121", en:"surge", ru:"резкий рост, всплеск", ex:"There was a surge in online sales over the holidays." },
    { id:"v4-C1-122", en:"plummet", ru:"резко падать", ex:"Share prices plummeted after the announcement." },
    { id:"v4-C1-123", en:"soar", ru:"взлетать, стремительно расти", ex:"Energy costs soared during the winter months." },
    { id:"v4-C1-124", en:"dwindle", ru:"сокращаться, истощаться", ex:"Reserves have dwindled to a critical level." },
    { id:"v4-C1-125", en:"taper off", ru:"постепенно снижаться", ex:"Demand began to taper off in the second quarter." },
    { id:"v4-C1-126", en:"level off", ru:"стабилизироваться, выравниваться", ex:"Inflation finally levelled off after months of rises." },
    { id:"v4-C1-127", en:"fluctuate", ru:"колебаться", ex:"Exchange rates fluctuated wildly throughout the year." },
    { id:"v4-C1-128", en:"stagnate", ru:"стагнировать, застаиваться", ex:"Wages have stagnated despite rising productivity." },
    { id:"v4-C1-129", en:"escalate", ru:"обостряться, нарастать", ex:"The conflict escalated rapidly into open warfare." },
    { id:"v4-C1-130", en:"rebound", ru:"восстанавливаться, отскакивать", ex:"The market rebounded sharply after the slump." },
    { id:"v4-C1-131", en:"a marked increase", ru:"заметный рост", ex:"There was a marked increase in life expectancy." },
    { id:"v4-C1-132", en:"a steady decline", ru:"устойчивое снижение", ex:"The data show a steady decline in birth rates." },
    { id:"v4-C1-133", en:"a sharp downturn", ru:"резкий спад", ex:"The sector suffered a sharp downturn last year." },
    { id:"v4-C1-134", en:"a gradual shift", ru:"постепенный сдвиг", ex:"There has been a gradual shift towards remote work." },
    { id:"v4-C1-135", en:"reach a peak", ru:"достигать пика", ex:"Unemployment reached a peak in early 2009." },
    { id:"v4-C1-136", en:"hit a low", ru:"достигать минимума", ex:"Consumer confidence hit a record low." },
    { id:"v4-C1-137", en:"upward trajectory", ru:"восходящая траектория", ex:"The company remains on an upward trajectory." },
    { id:"v4-C1-138", en:"trend reversal", ru:"разворот тенденции", ex:"Analysts noted a trend reversal in housing prices." },
    { id:"v4-C1-139", en:"exponential growth", ru:"экспоненциальный рост", ex:"Data storage needs are growing exponentially." },
    { id:"v4-C1-140", en:"negligible change", ru:"незначительное изменение", ex:"There was a negligible change in overall output." },
    { id:"v4-C1-141", en:"empirical", ru:"эмпирический, опытный", ex:"The claim is supported by strong empirical evidence." },
    { id:"v4-C1-142", en:"hypothesis", ru:"гипотеза", ex:"The experiment was designed to test the hypothesis." },
    { id:"v4-C1-143", en:"correlation", ru:"корреляция, взаимосвязь", ex:"Correlation does not necessarily imply causation." },
    { id:"v4-C1-144", en:"variable", ru:"переменная (величина)", ex:"Researchers controlled for several confounding variables." },
    { id:"v4-C1-145", en:"causality", ru:"причинность, причинная связь", ex:"Establishing causality requires careful experimental design." },
    { id:"v4-C1-146", en:"scalability", ru:"масштабируемость", ex:"The scalability of the system remains unproven." },
    { id:"v4-C1-147", en:"disruptive innovation", ru:"подрывная инновация", ex:"Streaming was a disruptive innovation in the media industry." },
    { id:"v4-C1-148", en:"infrastructure", ru:"инфраструктура", ex:"The country invested heavily in digital infrastructure." },
    { id:"v4-C1-149", en:"obsolescence", ru:"устаревание", ex:"Rapid technological change accelerates obsolescence." },
    { id:"v4-C1-150", en:"interoperability", ru:"совместимость, взаимодействие систем", ex:"Interoperability between platforms remains a challenge." },
    { id:"v4-C1-151", en:"fiscal", ru:"налогово-бюджетный, фискальный", ex:"The government pursued an expansionary fiscal policy." },
    { id:"v4-C1-152", en:"monetary policy", ru:"денежно-кредитная политика", ex:"The central bank tightened monetary policy to curb inflation." },
    { id:"v4-C1-153", en:"recession", ru:"рецессия, экономический спад", ex:"The economy slipped into a deep recession." },
    { id:"v4-C1-154", en:"liquidity", ru:"ликвидность", ex:"The crisis exposed a severe shortage of liquidity." },
    { id:"v4-C1-155", en:"depreciation", ru:"обесценивание; амортизация", ex:"The currency suffered a sharp depreciation." },
    { id:"v4-C1-156", en:"subsidy", ru:"субсидия, дотация", ex:"Farmers rely heavily on government subsidies." },
    { id:"v4-C1-157", en:"deficit", ru:"дефицит (бюджетный)", ex:"The budget deficit widened to a record level." },
    { id:"v4-C1-158", en:"incentive", ru:"стимул, побуждение", ex:"Tax incentives encouraged investment in renewables." },
    { id:"v4-C1-159", en:"deregulation", ru:"дерегулирование", ex:"Deregulation of the sector spurred fierce competition." },
    { id:"v4-C1-160", en:"diversification", ru:"диверсификация", ex:"Diversification reduces a portfolio's overall risk." },
    { id:"v4-C1-161", en:"legislation", ru:"законодательство", ex:"New legislation tightened controls on data privacy." },
    { id:"v4-C1-162", en:"mandate", ru:"мандат, полномочие", ex:"The party claimed a clear mandate for reform." },
    { id:"v4-C1-163", en:"sanction", ru:"санкция; одобрение", ex:"The council imposed economic sanctions on the regime." },
    { id:"v4-C1-164", en:"sovereignty", ru:"суверенитет", ex:"The treaty was seen as a threat to national sovereignty." },
    { id:"v4-C1-165", en:"accountability", ru:"подотчётность, ответственность", ex:"Voters are demanding greater accountability from leaders." },
    { id:"v4-C1-166", en:"bureaucracy", ru:"бюрократия", ex:"Excessive bureaucracy hampers small businesses." },
    { id:"v4-C1-167", en:"partisan", ru:"пристрастный, партийный", ex:"The debate quickly became bitterly partisan." },
    { id:"v4-C1-168", en:"electorate", ru:"электорат, избиратели", ex:"The electorate punished the incumbent for broken promises." },
    { id:"v4-C1-169", en:"coalition", ru:"коалиция", ex:"A fragile coalition formed the new government." },
    { id:"v4-C1-170", en:"constituency", ru:"избирательный округ; круг сторонников", ex:"The reform appealed to his core constituency." },
    { id:"v4-C1-171", en:"meticulous", ru:"скрупулёзный, дотошный", ex:"The research was praised for its meticulous methodology." },
    { id:"v4-C1-172", en:"ostensible", ru:"мнимый, кажущийся", ex:"The ostensible reason for the trip was a conference." },
    { id:"v4-C1-173", en:"tenable", ru:"состоятельный, обоснованный", ex:"That position is no longer tenable given the new data." },
    { id:"v4-C1-174", en:"salient", ru:"заметный, существенный", ex:"The report highlights the most salient findings." },
    { id:"v4-C1-175", en:"pervasive", ru:"всепроникающий, повсеместный", ex:"Corruption was pervasive throughout the administration." },
    { id:"v4-C1-176", en:"inherent", ru:"присущий, неотъемлемый", ex:"There are risks inherent in any speculative venture." },
    { id:"v4-C1-177", en:"negligible", ru:"ничтожный, пренебрежимо малый", ex:"The difference between the groups was negligible." },
    { id:"v4-C1-178", en:"robust", ru:"надёжный, устойчивый", ex:"The conclusions rest on a robust statistical foundation." },
    { id:"v4-C1-179", en:"unprecedented", ru:"беспрецедентный", ex:"The pandemic posed unprecedented logistical challenges." },
    { id:"v4-C1-180", en:"detrimental", ru:"вредный, пагубный", ex:"Prolonged stress is detrimental to health." },
    { id:"v4-C1-181", en:"superfluous", ru:"излишний, ненужный", ex:"The editor removed several superfluous paragraphs." },
    { id:"v4-C1-182", en:"contentious", ru:"спорный, вызывающий разногласия", ex:"Immigration remains a highly contentious issue." },
    { id:"v4-C1-183", en:"ubiquitous", ru:"вездесущий, повсеместный", ex:"Smartphones have become virtually ubiquitous." },
    { id:"v4-C1-184", en:"viable", ru:"жизнеспособный, осуществимый", ex:"Wind power is now a viable alternative to coal." },
    { id:"v4-C1-185", en:"a watershed moment", ru:"переломный момент", ex:"The verdict marked a watershed moment for civil rights." },
    { id:"v4-C1-186", en:"a double-edged sword", ru:"палка о двух концах", ex:"Automation is a double-edged sword for the workforce." },
    { id:"v4-C1-187", en:"the tip of the iceberg", ru:"верхушка айсберга", ex:"These complaints are only the tip of the iceberg." },
    { id:"v4-C1-188", en:"a grey area", ru:"серая зона, неопределённость", ex:"The legality of the practice falls into a grey area." },
    { id:"v4-C1-189", en:"a vicious circle", ru:"порочный круг", ex:"Debt and poverty can create a vicious circle." },
    { id:"v4-C1-190", en:"a level playing field", ru:"равные условия", ex:"Regulators aim to ensure a level playing field for competitors." },
    { id:"v4-C1-191", en:"to bridge the gap", ru:"преодолеть разрыв", ex:"The initiative seeks to bridge the gap between rich and poor." },
    { id:"v4-C1-192", en:"to take its toll", ru:"сказываться, брать своё", ex:"The long hours began to take their toll on staff." },
    { id:"v4-C1-193", en:"to gain traction", ru:"набирать обороты, получать поддержку", ex:"The proposal slowly gained traction among lawmakers." },
    { id:"v4-C1-194", en:"to set a precedent", ru:"создавать прецедент", ex:"The ruling set an important legal precedent." },
    { id:"v4-C1-195", en:"a paradigm shift", ru:"смена парадигмы", ex:"Remote work represents a paradigm shift in employment." },
    { id:"v4-C1-196", en:"to err on the side of caution", ru:"проявлять осторожность", ex:"Regulators chose to err on the side of caution." },
    { id:"v4-C1-197", en:"a sweeping reform", ru:"масштабная реформа", ex:"The minister announced a sweeping reform of the system." },
    { id:"v4-C1-198", en:"to weather the storm", ru:"пережить трудности", ex:"Well-capitalised firms managed to weather the storm." },
    { id:"v4-C1-199", en:"the bigger picture", ru:"общая картина", ex:"Critics urged the board to consider the bigger picture." },
    { id:"v4-C1-200", en:"to come to fruition", ru:"воплотиться, осуществиться", ex:"Years of planning finally came to fruition." }
  ]);
})();
