(() => {
  const C = window.CONTENT || (window.CONTENT = {});
  const P = (track, lvl, arr) => { C[track]=C[track]||{}; C[track][lvl]=C[track][lvl]||[]; arr.forEach(x=>C[track][lvl].push(x)); };

  P("vocab","C2",[
    { id:"v2c-C2-01", en:"perspicacious", ru:"проницательный, прозорливый", ex:"Her perspicacious analysis exposed flaws everyone else had overlooked." },
    { id:"v2c-C2-02", en:"obfuscate", ru:"запутывать, затемнять смысл", ex:"The report seemed deliberately written to obfuscate the company's losses." },
    { id:"v2c-C2-03", en:"sycophant", ru:"льстец, подхалим", ex:"The minister surrounded himself with sycophants who never questioned him." },
    { id:"v2c-C2-04", en:"ineluctable", ru:"неотвратимый, неизбежный", ex:"Ageing is an ineluctable consequence of being alive." },
    { id:"v2c-C2-05", en:"pellucid", ru:"кристально ясный, прозрачный", ex:"His prose is pellucid, never sacrificing clarity for ornament." },
    { id:"v2c-C2-06", en:"recondite", ru:"малопонятный, эзотерический", ex:"The lecture descended into recondite arguments only specialists could follow." },
    { id:"v2c-C2-07", en:"sanguine", ru:"оптимистичный, уверенный", ex:"Despite the setbacks, she remained sanguine about the project's future." },
    { id:"v2c-C2-08", en:"truculent", ru:"агрессивный, воинственный", ex:"He grew truculent whenever his authority was challenged." },
    { id:"v2c-C2-09", en:"vituperative", ru:"бранный, поносящий", ex:"The debate degenerated into a vituperative exchange of insults." },
    { id:"v2c-C2-10", en:"limn", ru:"живописать, обрисовывать", ex:"The novel limns the decay of an aristocratic family with great delicacy." },
    { id:"v2c-C2-11", en:"quotidian", ru:"будничный, повседневный", ex:"She found unexpected beauty in the quotidian rituals of village life." },
    { id:"v2c-C2-12", en:"inveigle", ru:"завлекать обманом, выманивать", ex:"He managed to inveigle his way into the exclusive gathering." },
    { id:"v2c-C2-13", en:"fulsome", ru:"чрезмерный, приторный (о похвале)", ex:"His fulsome praise struck everyone as insincere." },
    { id:"v2c-C2-14", en:"obstreperous", ru:"шумный, буйный, непокорный", ex:"The teacher struggled to control an obstreperous class." },
    { id:"v2c-C2-15", en:"propitiate", ru:"умилостивлять, задабривать", ex:"They offered concessions to propitiate the angry shareholders." },
    { id:"v2c-C2-16", en:"refractory", ru:"упрямый, неподатливый", ex:"The disease proved refractory to every available treatment." },
    { id:"v2c-C2-17", en:"sententious", ru:"нравоучительный, склонный к нравоучениям", ex:"His sententious remarks about morality bored the audience." },
    { id:"v2c-C2-18", en:"perfidious", ru:"вероломный, коварный", ex:"The perfidious ally betrayed them at the decisive moment." },
    { id:"v2c-C2-19", en:"meretricious", ru:"показной, мишурный, фальшиво-привлекательный", ex:"Behind its meretricious glamour, the resort was shoddily built." },
    { id:"v2c-C2-20", en:"adumbrate", ru:"намечать в общих чертах, предвещать", ex:"The opening chapter adumbrates themes developed throughout the book." },
    { id:"v2c-C2-21", en:"contumacious", ru:"непокорный, неповинующийся (часто суду)", ex:"The contumacious witness refused to answer any of the court's questions." },
    { id:"v2c-C2-22", en:"desuetude", ru:"состояние неупотребления, заброшенность", ex:"Many old customs have fallen into desuetude." },
    { id:"v2c-C2-23", en:"eleemosynary", ru:"благотворительный", ex:"The foundation operates on a purely eleemosynary basis." },
    { id:"v2c-C2-24", en:"feckless", ru:"никчёмный, безответственный", ex:"His feckless management drove the firm into bankruptcy." },
    { id:"v2c-C2-25", en:"grandiloquent", ru:"высокопарный, напыщенный", ex:"The speech was grandiloquent but devoid of substance." },
    { id:"v2c-C2-26", en:"hagiography", ru:"житие, чрезмерно хвалебная биография", ex:"The biography read more like hagiography than honest scholarship." },
    { id:"v2c-C2-27", en:"importune", ru:"назойливо упрашивать, домогаться", ex:"Beggars importuned the tourists at every corner." },
    { id:"v2c-C2-28", en:"jejune", ru:"пресный, наивный, незрелый", ex:"His jejune observations added nothing to the discussion." },
    { id:"v2c-C2-29", en:"lugubrious", ru:"мрачный, скорбный", ex:"He delivered the news in a lugubrious tone." },
    { id:"v2c-C2-30", en:"mendacious", ru:"лживый, склонный ко лжи", ex:"The tabloid was notorious for its mendacious reporting." },
    { id:"v2c-C2-31", en:"nugatory", ru:"ничтожный, не имеющий силы", ex:"Without enforcement, the regulation is effectively nugatory." },
    { id:"v2c-C2-32", en:"obloquy", ru:"поношение, бесчестье", ex:"The scandal heaped obloquy upon the once-revered statesman." },
    { id:"v2c-C2-33", en:"pusillanimous", ru:"малодушный, трусливый", ex:"His pusillanimous refusal to act cost them dearly." },
    { id:"v2c-C2-34", en:"quiescent", ru:"бездействующий, спокойный", ex:"The volcano had remained quiescent for centuries." },
    { id:"v2c-C2-35", en:"rebarbative", ru:"отталкивающий, неприятный", ex:"His rebarbative manner alienated potential allies." },
    { id:"v2c-C2-36", en:"saturnine", ru:"угрюмый, мрачный (о характере)", ex:"A saturnine man, he rarely smiled or spoke without prompting." },
    { id:"v2c-C2-37", en:"tergiversation", ru:"увиливание, отступничество", ex:"His constant tergiversation made negotiations impossible." },
    { id:"v2c-C2-38", en:"usufruct", ru:"узуфрукт, право пользования чужим имуществом", ex:"The will granted her usufruct of the estate during her lifetime." },
    { id:"v2c-C2-39", en:"vatic", ru:"пророческий, вдохновенный", ex:"The poet wrote in a vatic, almost prophetic, voice." },
    { id:"v2c-C2-40", en:"welter", ru:"мешанина, беспорядочное скопление", ex:"She was lost in a welter of conflicting emotions." },
    { id:"v2c-C2-41", en:"animadversion", ru:"порицание, осуждающее замечание", ex:"His essay drew sharp animadversions from the critics." },
    { id:"v2c-C2-42", en:"cavil", ru:"придираться, выискивать недостатки", ex:"Rather than engage with the argument, he merely cavilled at minor errors." },
    { id:"v2c-C2-43", en:"deracinate", ru:"искоренять, отрывать от корней", ex:"War had deracinated whole communities from their homeland." },
    { id:"v2c-C2-44", en:"effulgent", ru:"сияющий, лучезарный", ex:"The cathedral's effulgent stained glass dazzled the visitors." },
    { id:"v2c-C2-45", en:"farrago", ru:"мешанина, путаница (часто нелепиц)", ex:"The pamphlet was a farrago of half-truths and innuendo." },
    { id:"v2c-C2-46", en:"gainsay", ru:"отрицать, оспаривать", ex:"No one could gainsay the elegance of her solution." },
    { id:"v2c-C2-47", en:"hidebound", ru:"косный, узколобый", ex:"The institution was too hidebound to embrace reform." },
    { id:"v2c-C2-48", en:"inchoate", ru:"зачаточный, неоформленный", ex:"He struggled to articulate his inchoate sense of unease." },
    { id:"v2c-C2-49", en:"kibosh", ru:"конец, крах (put the kibosh on)", ex:"The funding cuts put the kibosh on the entire expedition." },
    { id:"v2c-C2-50", en:"lambent", ru:"мерцающий, играющий (о свете, остроумии)", ex:"His prose has a lambent wit that delights the reader." },
    { id:"v2c-C2-51", en:"maunder", ru:"бормотать, говорить бессвязно", ex:"He maundered on about the past, losing his thread repeatedly." },
    { id:"v2c-C2-52", en:"noisome", ru:"зловонный, вредоносный", ex:"A noisome stench rose from the neglected canal." },
    { id:"v2c-C2-53", en:"opprobrium", ru:"позор, всеобщее осуждение", ex:"His remarks brought down public opprobrium upon him." },
    { id:"v2c-C2-54", en:"palliate", ru:"смягчать, облегчать (не устраняя причину)", ex:"The measures only palliated the symptoms of a deeper crisis." },
    { id:"v2c-C2-55", en:"rodomontade", ru:"бахвальство, хвастливые речи", ex:"His speech was empty rodomontade, all bluster and no plan." },
    { id:"v2c-C2-56", en:"supererogatory", ru:"сверхдолжный, излишний", ex:"Her supererogatory kindness went far beyond what duty required." },
    { id:"v2c-C2-57", en:"thaumaturgy", ru:"чудотворство, магия", ex:"The crowd treated his feats of engineering as a kind of thaumaturgy." },
    { id:"v2c-C2-58", en:"velleity", ru:"слабое желание без воли к действию", ex:"His resolve never rose above a faint velleity." },
    { id:"v2c-C2-59", en:"wonted", ru:"привычный, обыкновенный", ex:"She resumed her wonted seat by the window." },
    { id:"v2c-C2-60", en:"zugzwang", ru:"цугцванг, вынужденный невыгодный ход", ex:"Politically, the leader found himself in a zugzwang where every option worsened his position." }
  ]);
})();
